### ISSUE TITLE
ItemResourceOSGiTest fails on Windows

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1002]
```
09:18:19.524 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ItemProvider$MockitoMock$2094127727" has been removed.
TEST shouldReturnUnicodeItems(org.eclipse.smarthome.io.rest.core.internal.item.ItemResourceOSGiTest) <<< ERROR:
Expected: (a collection containing "Test ▒▒▒▒")
     but: a collection containing "Test ▒▒▒▒" was "Test äöü▒?"
java.lang.AssertionError:
Expected: (a collection containing "Test ▒▒▒▒")
     but: a collection containing "Test ▒▒▒▒" was "Test äöü▒?"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.eclipse.smarthome.io.rest.core.internal.item.ItemResourceOSGiTest.shouldReturnUnicodeItems(ItemResourceOSGiTest.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
```

**Comment by lolodomo** [comment]
@cweitkamp : the failing test was recently added by you in your PR #982. Any iodea what's wrong ?

**Comment by cweitkamp** [comment]
Probably something related to a local charset / locale configuration. I initially thought about using real unicode representation of the characters for the test cases ... I will give it a try.

**Comment by cweitkamp** [comment]
Can you give https://github.com/openhab/openhab-core/commit/afdc2f9f472893513206f13b83ae64133fea26bc a try?

**Comment by lolodomo** [comment]
I applied your change in my local branch but it does not resolve the issue, the test is still failing:
```
TEST shouldReturnUnicodeItems(org.eclipse.smarthome.io.rest.core.internal.item.ItemResourceOSGiTest) <<< ERROR:
Expected: (a collection containing "Test ▒▒▒▒")
     but: a collection containing "Test ▒▒▒▒" was "Test äöü▒?"
java.lang.AssertionError:
Expected: (a collection containing "Test ▒▒▒▒")
     but: a collection containing "Test ▒▒▒▒" was "Test äöü▒?"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.eclipse.smarthome.io.rest.core.internal.item.ItemResourceOSGiTest.shouldReturnUnicodeItems(ItemResourceOSGiTest.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
```
```
$ git diff  src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java
diff --git a/itests/org.openhab.core.io.rest.core.tests/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java b/itests/org.openhab.core.io.rest.core.tests/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java
index ff0f67f9..417f341a 100644
--- a/itests/org.openhab.core.io.rest.core.tests/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java
+++ b/itests/org.openhab.core.io.rest.core.tests/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java
@@ -61,7 +61,7 @@ public class ItemResourceOSGiTest extends JavaOSGiTest {
     private static final String ITEM_NAME2 = "Item2";
     private static final String ITEM_NAME3 = "Item3";
     private static final String ITEM_NAME4 = "Item4";
-    private static final String ITEM_LABEL4 = "Test äöüß";
+    private static final String ITEM_LABEL4 = "Test \u00e4\u00f6\u00fc\u00df"; // Test äöüß

     private GenericItem item1;
     private GenericItem item2;
```

**Comment by lolodomo** [comment]
This is now the only remaining problem when I build the core framework on Windows 10.
All other tests are OK.
