### ISSUE TITLE
Exception on 2.5M3 start

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#1026]
Not sure but I think I've seen it on M2 or M1 milestones, too

```
2019-09-08 13:19:21.130 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] - Refreshing bundles:
2019-09-08 13:19:21.132 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.apache.commons.codec/1.6.0 (Bundle will be uninstalled)
2019-09-08 13:19:21.134 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.apache.karaf.shell.ssh/4.2.6 (Wired to org.apache.servicemix.bundles.not-yet-commons-ssl/0.3.11.1 which is being refreshed)
2019-09-08 13:19:21.135 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.apache.servicemix.bundles.commons-httpclient/3.1.0.7 (Wired to org.apache.commons.codec/1.6.0 which is being refreshed)
2019-09-08 13:19:21.137 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.apache.servicemix.bundles.not-yet-commons-ssl/0.3.11.1 (Wired to org.apache.servicemix.bundles.commons-httpclient/3.1.0.7 which is being refreshed)
2019-09-08 13:19:21.138 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.openhab.binding.lghombot/2.5.0.201906182057 (Wired to org.openhab.core.config.discovery/2.5.0.M3 which is being refreshed)
2019-09-08 13:19:21.140 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.openhab.core.compat1x/2.5.0.M3 (Wired to org.apache.servicemix.bundles.commons-httpclient/3.1.0.7 which is being refreshed)
2019-09-08 13:19:21.141 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.openhab.core.config.discovery/2.5.0.M3 (Should be wired to: org.jupnp/2.5.2 (through [org.openhab.core.config.discovery/2.5.0.M3] osgi.wiring.package; resolution:=optional; filter:="(osgi.wiring.package=org.jupnp.model.meta)"))
2019-09-08 13:19:21.142 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.openhab.core.config.discovery.mdns/2.5.0.M3 (Wired to org.openhab.core.config.discovery/2.5.0.M3 which is being refreshed)
2019-09-08 13:19:21.144 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.openhab.core.io.rest.core/2.5.0.M3 (Wired to org.openhab.core.config.discovery/2.5.0.M3 which is being refreshed)
2019-09-08 13:19:21.146 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.openhab.core.io.rest.mdns/2.5.0.M3 (Wired to org.openhab.core.io.transport.mdns/2.5.0.M3 which is being refreshed)
2019-09-08 13:19:21.147 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.openhab.core.io.rest.sitemap/2.5.0.M3 (Wired to org.openhab.core.io.rest.core/2.5.0.M3 which is being refreshed)
2019-09-08 13:19:21.148 [INFO] [g.apache.karaf.features.internal.service.FeaturesServiceImpl] -     org.openhab.core.io.transport.mdns/2.5.0.M3 (Wired to org.openhab.core.config.discovery/2.5.0.M3 which is being refreshed)
2019-09-08 13:19:23.262 [INFO] [org.openhab.ui.paper                ] - FrameworkEvent INFO - org.openhab.ui.paper
org.osgi.framework.BundleException: The bundle class path entry "patch/" could not be found for the bundle "osgi.identity; osgi.identity="org.openhab.ui.paper"; type="osgi.bundle"; version:Version="2.5.0.M3""
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassPathEntry(ClasspathManager.java:174) ~[?:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.buildClasspath(ClasspathManager.java:152) ~[?:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.<init>(ClasspathManager.java:81) ~[?:?]
        at org.eclipse.osgi.internal.loader.EquinoxClassLoader.<init>(EquinoxClassLoader.java:43) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.createClassLoaderPrivledged(BundleLoader.java:316) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.getModuleClassLoader(BundleLoader.java:233) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$1.run(EquinoxBundle.java:595) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$1.run(EquinoxBundle.java:1) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.getModuleClassLoader(EquinoxBundle.java:588) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.getResource(EquinoxBundle.java:530) ~[?:?]
        at org.apache.servicemix.specs.activation.Activator.register(Activator.java:58) ~[?:?]
        at org.apache.servicemix.specs.locator.Activator.bundleChanged(Activator.java:95) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[?:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:719) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:511) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:457) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1001) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1382) ~[?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1) ~[?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
2019-09-08 13:19:23.426 [WARN] [org.openhab.binding.lghombot.internal.LGHomBotHandler] - Channel refresh for pause not implemented!
2019-09-08 13:19:23.806 [DEBUG] [org.openhab.action.telegram         ] - BundleEvent RESOLVED - org.openhab.action.telegram
2019-09-08 13:19:23.838 [DEBUG] [org.openhab.binding.zwave           ] - BundleEvent RESOLVED - org.openhab.binding.zwave
2019-09-08 13:19:23.941 [DEBUG] [org.openhab.binding.gpstracker      ] - BundleEvent RESOLVED - org.openhab.binding.gpstracker

```

**Comment by openhab-5iver** [comment]
https://github.com/openhab/openhab-distro/pull/910

You might have skipped changes to org.ops4j.pax.logging.cfg during upgrade?

**Comment by mstormi** [comment]
> You might have skipped changes to org.ops4j.pax.logging.cfg during upgrade?

Apparently so, thanks for pointing there.
I think there's usually a warning to *exchange* the file on upgrading which of course isn't what I want. Shall I open another issue in openhab-distro to at least reword that ?

**Comment by openhab-5iver** [comment]
I'm not sure what you'd reword... I've not used the update script... but openhab-distro is where you'd need to do something like that.
