### ISSUE TITLE
JuPnP SSLContextFactory Error

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-core#1028]
After upgrading to M2 I started to get these messages:

```
2019-09-10 10:05:37.310 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@5829532b failed
java.lang.NullPointerException: Missing SslContextFactory
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:?]
        at org.eclipse.jetty.io.ssl.SslClientConnectionFactory.<init>(SslClientConnectionFactory.java:55) ~[80:org.eclipse.jetty.io:9.4.18.v20190429]
        at org.eclipse.jetty.client.HttpClient.newSslClientConnectionFactory(HttpClient.java:1170) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.eclipse.jetty.client.HttpDestination.newSslClientConnectionFactory(HttpDestination.java:137) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.eclipse.jetty.client.HttpDestination.<init>(HttpDestination.java:94) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.eclipse.jetty.client.PoolingHttpDestination.<init>(PoolingHttpDestination.java:25) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.<init>(HttpDestinationOverHTTP.java:32) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.eclipse.jetty.client.http.HttpClientTransportOverHTTP.newHttpDestination(HttpClientTransportOverHTTP.java:51) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.eclipse.jetty.client.HttpClient.destinationFor(HttpClient.java:542) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:575) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:726) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:679) ~[76:org.eclipse.jetty.client:9.4.18.v20190429]
        at org.jupnp.transport.impl.jetty.JettyStreamClientImpl$1.call(JettyStreamClientImpl.java:155) [234:org.jupnp:2.5.2]
        at org.jupnp.transport.impl.jetty.JettyStreamClientImpl$1.call(JettyStreamClientImpl.java:1) [234:org.jupnp:2.5.2]
        at org.jupnp.transport.spi.AbstractStreamClient$RequestWrapper.call(AbstractStreamClient.java:204) [234:org.jupnp:2.5.2]
        at org.jupnp.transport.spi.AbstractStreamClient$RequestWrapper.call(AbstractStreamClient.java:1) [234:org.jupnp:2.5.2]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-09-10 10:05:37.317 [WARN ] [org.jupnp.transport.spi.StreamClient] - HTTP request failed: (StreamRequestMessage) GET https://[REDACTED]:8888/capability (Missing SslContextFactory)
2019-09-10 10:05:37.317 [WARN ] [p.protocol.RetrieveRemoteDescriptors] - Device descriptor retrieval failed, no response: https://[REDACTED]:8888/capability
```

For reference, the device in question is my Samsung Refrigerator.  I don't do anything with it from an OH perspective at all so I have no idea why OH is trying to connect to it.

**Comment by kaikreuzer** [comment]
This is a known issue, see https://github.com/jupnp/jupnp/issues/109.
You can ignore it and change your log setting as suggested by that issue.

**Comment by lolodomo** [comment]
Ok @morph166955 is multiplying the same issue ;) Can you close this one @kaikreuzer ?

**Comment by morph166955** [comment]
Sorry, completely forgot I opened this one last year.  My bad on the dupe.
