### ISSUE TITLE
GenericItemProviderTest fails on Windows

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1071]
When run on Windows 10:
```
19:25:50.680 [main] INFO org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl - Loading model 'testModel.items'
19:25:50.680 [main] DEBUG org.eclipse.smarthome.model.item.internal.GenericItemProvider - Read items from model 'testModel.items'
19:25:50.680 [main] DEBUG org.eclipse.smarthome.model.item.internal.GenericItemProvider - Processing binding configs for items from model 'testModel.items'
19:25:50.680 [main] DEBUG org.eclipse.smarthome.model.item.internal.GenericItemProvider - Processing binding configs for items from model 'testModel.items'
19:25:50.680 [main] DEBUG org.eclipse.smarthome.model.item.internal.GenericItemProvider - Read items from model 'testModel.items'
19:25:50.680 [main] WARN org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl - Configuration model 'testModel.items' has errors, therefore ignoring it: [2,8]: extraneous input '{' expecting RULE_ID

19:25:50.680 [main] INFO org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl - Loading model 'testModel.items'
19:25:50.696 [main] DEBUG org.eclipse.smarthome.model.item.internal.GenericItemProvider - Read items from model 'testModel.items'
19:25:50.696 [main] DEBUG org.eclipse.smarthome.model.item.internal.GenericItemProvider - Processing binding configs for items from model 'testModel.items'
19:25:50.962 [Timer-2] DEBUG org.quartz.utils.UpdateChecker - Checking for available updated version of Quartz...
19:25:51.040 [Timer-2] DEBUG org.quartz.utils.UpdateChecker - Quartz version update check failed: Server returned HTTP response code: 403 for URL: http://www.terracotta.org/kit/reflector?kitID=quartz&pageID=update.properties&id=-1062731492&os-name=Windows+10&jvm-name=Java+HotSpot%28TM%29+64-Bit+Server+VM&jvm-version=1.8.0_131&platform=amd64&tc-version=2.2.1&tc-product=Quartz&source=Quartz&uptime-secs=1&patch=UNKNOWN
19:25:55.710 [DefaultQuartzScheduler_QuartzSchedulerThread] DEBUG org.quartz.core.QuartzSchedulerThread - batch acquisition of 0 triggers
19:25:55.710 [OH-ruleEngine-3] INFO org.quartz.core.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
19:26:03.193 [main] DEBUG org.eclipse.smarthome.model.item.internal.GenericItemProvider - Processing binding configs for items from model 'testModel.items'
19:26:03.193 [main] DEBUG org.eclipse.smarthome.model.item.internal.GenericItemProvider - Read items from model 'testModel.items'
TEST assertThatItemEventsAreSentCorrectly(org.eclipse.smarthome.model.item.internal.GenericItemProviderTest) <<< ERROR:
Expected: is <2>
     but: was <3>
java.lang.AssertionError:
Expected: is <2>
     but: was <3>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.eclipse.smarthome.model.item.internal.GenericItemProviderTest.lambda$1(GenericItemProviderTest.java:212)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:152)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:120)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:73)
        at org.eclipse.smarthome.model.item.internal.GenericItemProviderTest.assertThatItemEventsAreSentCorrectly(GenericItemProviderTest.java:210)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
```

**Comment by lolodomo** [comment]
Do not occur anymore.
