### ISSUE TITLE
HostFragmentSupportTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1089]
This test failed on Travis with the following stack trace:

```
TEST assertThatTheUpdateOfTheFragmentHostProvidesTheResourcesCorrectly(org.openhab.core.automation.integration.test.HostFragmentSupportTest) <<< ERROR: 
Expected: is <1>
     but: was <32>
java.lang.AssertionError: 
Expected: is <1>
     but: was <32>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.openhab.core.automation.integration.test.HostFragmentSupportTest.assertThatTheUpdateOfTheFragmentHostProvidesTheResourcesCorrectly(HostFragmentSupportTest.java:397)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at aQute.junit.Activator.test(Activator.java:340)
	at aQute.junit.Activator.automatic(Activator.java:236)
	at aQute.junit.Activator.run(Activator.java:177)
	at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
	at aQute.launcher.Launcher.run(Launcher.java:352)
	at aQute.launcher.Launcher.main(Launcher.java:152)
```

**Comment by cweitkamp** [comment]
One more - or a change - Jenkins failed (see [Job 1823](https://ci.openhab.org/job/PR-openHAB-Core/1823/console) or [Job 1825](https://ci.openhab.org/job/PR-openHAB-Core/1825/console))

```
13:07:03 TEST assertThatTheUpdateOfTheFragmentHostProvidesTheResourcesCorrectly(org.openhab.core.automation.integration.test.HostFragmentSupportTest) <<< ERROR: null
13:07:03 java.lang.NullPointerException
13:07:03 	at org.openhab.core.automation.integration.test.HostFragmentSupportTest.lambda$7(HostFragmentSupportTest.java:258)
13:07:03 	at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:136)
13:07:03 	at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:120)
13:07:03 	at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:84)
13:07:03 	at org.openhab.core.automation.integration.test.HostFragmentSupportTest.assertThatTheUpdateOfTheFragmentHostProvidesTheResourcesCorrectly(HostFragmentSupportTest.java:254)
13:07:03 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:07:03 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:07:03 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:07:03 	at java.lang.reflect.Method.invoke(Method.java:498)
13:07:03 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
13:07:03 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
13:07:03 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
13:07:03 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
13:07:03 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
13:07:03 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
13:07:03 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
13:07:03 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
13:07:03 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
13:07:03 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
13:07:03 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
13:07:03 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
13:07:03 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
13:07:03 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
13:07:03 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
13:07:03 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
13:07:03 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
13:07:03 	at junit.framework.TestSuite.run(TestSuite.java:247)
13:07:03 	at aQute.junit.Activator.test(Activator.java:340)
13:07:03 	at aQute.junit.Activator.automatic(Activator.java:236)
13:07:03 	at aQute.junit.Activator.run(Activator.java:177)
13:07:03 	at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
13:07:03 	at aQute.launcher.Launcher.run(Launcher.java:352)
13:07:03 	at aQute.launcher.Launcher.main(Launcher.java:152)
```

**Comment by wborn** [comment]
I haven't seen this test fail for a while now, so let's close this issue until further notice.

**Comment by wborn** [comment]
The unstability is back from its holiday, so lets reopen the issue.

https://travis-ci.com/github/openhab/openhab-core/builds/160413363

```
TEST assertThatTheUpdateOfTheFragmentHostProvidesTheResourcesCorrectly(org.openhab.core.automation.integration.test.HostFragmentSupportTest) <<< ERROR: null
java.lang.NullPointerException
	at org.openhab.core.automation.integration.test.HostFragmentSupportTest.lambda$7(HostFragmentSupportTest.java:274)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:136)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:84)
	at org.openhab.core.automation.integration.test.HostFragmentSupportTest.assertThatTheUpdateOfTheFragmentHostProvidesTheResourcesCorrectly(HostFragmentSupportTest.java:269)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at aQute.junit.Activator.test(Activator.java:326)
	at aQute.junit.Activator.automatic(Activator.java:220)
	at aQute.junit.Activator.run(Activator.java:176)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at aQute.launcher.Launcher.launch(Launcher.java:385)
	at aQute.launcher.Launcher.run(Launcher.java:143)
	at aQute.launcher.Launcher.main(Launcher.java:121)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:154)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:119)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:51)
Tests run  : 19
Passed     : 18
Errors     : 1
Failures   : 0
```

**Comment by wborn** [comment]
It's still with us in 2021, see [build 666](https://ci.openhab.org/job/openHAB-Core/666/):

```
TEST org.openhab.core.automation.integration.test.HostFragmentSupportTest#assertThatTheUpdateOfTheFragmentHostProvidesTheResourcesCorrectly() <<< ERROR: null
java.lang.NullPointerException
	at org.openhab.core.automation.integration.test.HostFragmentSupportTest.lambda$7(HostFragmentSupportTest.java:279)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:136)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:84)
	at org.openhab.core.automation.integration.test.HostFragmentSupportTest.assertThatTheUpdateOfTheFragmentHostProvidesTheResourcesCorrectly(HostFragmentSupportTest.java:269)
```

**Comment by J-N-K** [comment]
The NPE occurs at this line:

```
assertThat(registry.get(condition1, DEFAULT).getLabel(), is(registry.get(condition1).getLabel()));
```

so either of the registry get-calls is null. But immediately before this assertion,

```
assertThatModuleAndLocalizationsAreNotNull(condition1);
```

is called, which asserts that these values are not null:

```
    private void assertThatModuleAndLocalizationsAreNotNull(String uid) {
        assertThat(registry.get(uid), is(notNullValue()));
        for (Locale locale : LOCALES) {
            assertThat(registry.get(uid, locale), is(notNullValue()));
        }
    }
```

So it seems that the registry is modified in between. How is that possible? In my understanding the tests are not run in parallel within one class.
