### ISSUE TITLE
SafeCallerImplTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1113]
This test failed on [Jenkins](https://ci.openhab.org/job/PR-openHAB-Core/1719/console) (https://github.com/openhab/openhab-core/pull/1110#issuecomment-540485847) with the following stack trace:

```
00:15:44 TEST testAsyncExceptionHandler(org.eclipse.smarthome.core.internal.common.SafeCallerImplTest) <<< ERROR: 
00:15:44 No interactions wanted here:
00:15:44 -> at org.eclipse.smarthome.core.internal.common.SafeCallerImplTest.testAsyncExceptionHandler(SafeCallerImplTest.java:407)
00:15:44 But found this interaction on mock 'mockTimeoutHandler':
00:15:44 -> at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.handleTimeout(AbstractInvocationHandler.java:121)
00:15:44 Actually, above is the only interaction with this mock.
00:15:44 org.mockito.exceptions.verification.NoInteractionsWanted: 
00:15:44 No interactions wanted here:
00:15:44 -> at org.eclipse.smarthome.core.internal.common.SafeCallerImplTest.testAsyncExceptionHandler(SafeCallerImplTest.java:407)
00:15:44 But found this interaction on mock 'mockTimeoutHandler':
00:15:44 -> at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.handleTimeout(AbstractInvocationHandler.java:121)
00:15:44 Actually, above is the only interaction with this mock.
00:15:44 	at org.eclipse.smarthome.core.internal.common.SafeCallerImplTest.testAsyncExceptionHandler(SafeCallerImplTest.java:407)
00:15:44 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:15:44 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:15:44 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:15:44 	at java.lang.reflect.Method.invoke(Method.java:498)
00:15:44 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
00:15:44 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
00:15:44 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
00:15:44 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
00:15:44 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
00:15:44 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
00:15:44 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
00:15:44 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
00:15:44 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
00:15:44 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
00:15:44 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
00:15:44 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
00:15:44 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
00:15:44 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
00:15:44 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
00:15:44 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
00:15:44 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
00:15:44 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
00:15:44 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
00:15:44 	at junit.framework.TestSuite.run(TestSuite.java:247)
00:15:44 	at aQute.junit.Activator.test(Activator.java:340)
00:15:44 	at aQute.junit.Activator.automatic(Activator.java:236)
00:15:44 	at aQute.junit.Activator.run(Activator.java:177)
00:15:44 	at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
00:15:44 	at aQute.launcher.Launcher.run(Launcher.java:352)
00:15:44 	at aQute.launcher.Launcher.main(Launcher.java:152)
```

**Comment by wborn** [comment]
There's also another test in this class that's unstable on [Jenkins](https://ci.openhab.org/job/PR-openHAB-Core/1727/console):

```
22:46:20 TEST testSecondCallGetsAcceptedDifferentIdentifier(org.eclipse.smarthome.core.internal.common.SafeCallerImplTest) <<< ERROR: Duration should have been below 400 but was 407
22:46:20 java.lang.AssertionError: Duration should have been below 400 but was 407
22:46:20 	at org.junit.Assert.fail(Assert.java:88)
22:46:20 	at org.junit.Assert.assertTrue(Assert.java:41)
22:46:20 	at org.eclipse.smarthome.core.internal.common.SafeCallerImplTest.assertDurationBetween(SafeCallerImplTest.java:548)
22:46:20 	at org.eclipse.smarthome.core.internal.common.SafeCallerImplTest.testSecondCallGetsAcceptedDifferentIdentifier(SafeCallerImplTest.java:279)
22:46:20 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:46:20 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:46:20 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:46:20 	at java.lang.reflect.Method.invoke(Method.java:498)
22:46:20 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
22:46:20 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
22:46:20 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
22:46:20 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
22:46:20 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
22:46:20 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
22:46:20 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
22:46:20 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
22:46:20 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
22:46:20 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
22:46:20 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
22:46:20 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
22:46:20 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
22:46:20 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
22:46:20 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
22:46:20 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
22:46:20 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
22:46:20 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
22:46:20 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
22:46:20 	at junit.framework.TestSuite.run(TestSuite.java:247)
22:46:20 	at aQute.junit.Activator.test(Activator.java:340)
22:46:20 	at aQute.junit.Activator.automatic(Activator.java:236)
22:46:20 	at aQute.junit.Activator.run(Activator.java:177)
22:46:20 	at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
22:46:20 	at aQute.launcher.Launcher.run(Launcher.java:352)
22:46:20 	at aQute.launcher.Launcher.main(Launcher.java:152)
```

**Comment by wborn** [comment]
I haven't seen this test fail for a while now, so let's close this issue until further notice.
