### ISSUE TITLE
[ephemeris] IllegalArgumentException when trying to save configuration on German Windows

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-core#1116]
Environment: Windows 10 1090 German with Java 8
openHAB Version: 2.5 - Build 1716

When I try to change the ephemeris configuration I always get the following exception:
```
11:12:28.247 [ERROR] [org.openhab.core.ephemeris           ] - bundle org.openhab.core.ephemeris:2.5.0.201910110308 (143)[org.openhab.ephemeris(61)] : The modified method has thrown an exception
java.lang.IllegalArgumentException: No enum constant java.time.DayOfWeek.SATURDAY,SUNDAY
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:?]
        at java.time.DayOfWeek.valueOf(DayOfWeek.java:109) ~[?:?]
        at org.eclipse.smarthome.core.ephemeris.internal.EphemerisManagerImpl.addDayset(EphemerisManagerImpl.java:291) ~[?:?]
        at org.eclipse.smarthome.core.ephemeris.internal.EphemerisManagerImpl.lambda$2(EphemerisManagerImpl.java:143) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:?]
        at org.eclipse.smarthome.core.ephemeris.internal.EphemerisManagerImpl.modified(EphemerisManagerImpl.java:123) ~[?:?]
```

The list of weekdays is also not consistent. It looks like this:
![image](https://user-images.githubusercontent.com/616792/66640224-d6e1c000-ec18-11e9-9d52-fd3def7792bd.png)

BTW: The "Save" button is not enabled if I only change the weekdays. I always have to perform additional changes to make this button visible.

**Comment by cweitkamp** [comment]
Thanks for reporting. Please have a look here: https://github.com/openhab/openhab-core/issues/903 and https://github.com/openhab/openhab-core/pull/919#issuecomment-538686290.
