### ISSUE TITLE
Failed to install org.openhab.ephemeris.cfg due to NPE

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1121]
On recent snapshot builds (e.g. build 1719), the default [Ephemeris configuration](https://github.com/openhab/openhab-core/blob/91617d8af81dfa36cfd9514a379c7893b1de5ebd/features/karaf/openhab-core/src/main/feature/feature.xml#L122-L125) is causing a stacktrace at startup. See also this [community thread](https://community.openhab.org/t/failed-to-install-artifact-var-lib-openhab2-etc-org-openhab-ephemeris-cfg/83238?u=wborn).

```
Configuring openHAB
Launching the openHAB runtime...
09:47:50.483 [Start Level: Equinox Container: e482c900-3702-4070-9891-7e5e1ce3ee73] ERROR org.apache.felix.fileinstall - Failed to install artifact: /home/wouter/software/openhab/instance/userdata/etc/org.openhab.ephemeris.cfg
java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:460) ~[?:?]
	at org.apache.felix.fileinstall.internal.ConfigInstaller.setConfig(ConfigInstaller.java:277) ~[10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.ConfigInstaller.install(ConfigInstaller.java:99) ~[10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:950) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:884) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:489) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.start(DirectoryWatcher.java:247) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.FileInstall.updated(FileInstall.java:254) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.FileInstall.start(FileInstall.java:138) [10:org.apache.felix.fileinstall:3.6.4]
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779) [?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772) [?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309) [?:?]
	at org.eclipse.osgi.container.Module.doStart(Module.java:581) [?:?]
	at org.eclipse.osgi.container.Module.start(Module.java:449) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```

The configuration in `userdata/etc/org.openhab.ephemeris.cfg` is:

```

dayset-weekend=[SATURDAY,SUNDAY]
dayset-school=[MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY]

```

**Comment by cweitkamp** [comment]
FTR: There is a manual workaround available (see https://github.com/openhab/openhab-core/issues/903#issuecomment-539569492) but that is probably not the final solution.

**Comment by kaikreuzer** [comment]
I just tested a plain install of the latest snapshot build and ran across the same.
As every user will come across this, I consider it rather important to be fixed before M4.

Do you happen to know what exactly causes this issue and why the workaround might help?
Packaging the file in the `conf/services` folder does not seem to help either as if it is there on the very first start, I was seeing other weird error messages and openHAB didn't even fully start up.

Any suggestion how we should handle this?

**Comment by kaikreuzer** [comment]
@cweitkamp [here](https://community.openhab.org/t/general-openhab2-addons-discussions/42813/275?u=kai):

"I did some brainstorming over the day. Beside removing the default configuration from the feature I think there could be some other options:

1. We can specify a `<configfile />` element like we do with openHAB 1 Add-ons and place a predefined ephemeris.cfg directly into the conf/services/ folder (see related section in Karaf docs)

2. We can put the default configuration for the service into the runtime.cfg of openHAB distribution.
```
org.openhab.ephemeris:dayset-weekend = [SATURDAY,SUNDAY]
org.openhab.ephemeris:dayset-school = [MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY]  
```

3. We can implement default values in the EphemerisManagerImpl by using the OSGi ConfigurationAdmin.

Something interesting?"

**Comment by kaikreuzer** [comment]
@J-N-K [here](https://community.openhab.org/t/general-openhab2-addons-discussions/42813/276?u=kai):

"3 is distribution independent, right? I would prefer that. If the distribution (openhab or another one) needs to be adapted anyway, I would select 1."

**Comment by kaikreuzer** [comment]
Interesting. I would actually vote for 2 as this is the currently standard way of setting default values for any core system services. See how it also contains i18n, persistence and audio settings, so why not put ephemeris in there as well?

**Comment by J-N-K** [comment]
Good point. Ok for me as well.

**Comment by cweitkamp** [comment]
#2 seems to be the "easiest" way to. Isn't it? Shall I take care of it?

**Comment by kaikreuzer** [comment]
Yes, please!

**Comment by cweitkamp** [comment]
Done. See https://github.com/openhab/openhab-distro/pull/984 and https://github.com/openhab/openhab-core/pull/1135.

**Comment by kaikreuzer** [comment]
Thanks!
