### ISSUE TITLE
Groups cannot have binding configurations for 1.x bindings

### ISSUE THREAD

**Issue by macmeck** [openhab/openhab-core#113]
In openHAB 1.x also groups could have bindings which seem not to be working any more in openHAB 2.0.

The follwing item definition worked fine in openHAB 1.x
`Group:Switch:OR(ON,OFF) gPresence	"Presence [MAP(presence_display.map):%s]"		{mqtt=">[broker:presence/status:command:*:MAP(presence_out.map)]"}`

In openHAB 2.0 the binding is not accepted and the logs give
```
2017-01-25 13:44:03.630 [ERROR] [el.item.internal.GenericItemProvider] - Binding configuration of type 'mqtt' of item 'gPresence' could not be parsed correctly.
org.eclipse.smarthome.model.item.BindingConfigParseException: cannot process unknown item type Group
	at org.openhab.core.binding.internal.BindingConfigReaderDelegate.getOpenHABItem(BindingConfigReaderDelegate.java:84)[176:org.openhab.core.compat1x:2.0.0]
	at org.openhab.core.binding.internal.BindingConfigReaderDelegate.getOpenHABItem(BindingConfigReaderDelegate.java:56)[176:org.openhab.core.compat1x:2.0.0]
	at org.openhab.core.binding.internal.BindingConfigReaderDelegate.validateItemType(BindingConfigReaderDelegate.java:37)[176:org.openhab.core.compat1x:2.0.0]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:311)[123:org.eclipse.smarthome.model.item:0.9.0.b4]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:284)[123:org.eclipse.smarthome.model.item:0.9.0.b4]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:167)[123:org.eclipse.smarthome.model.item:0.9.0.b4]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:347)[123:org.eclipse.smarthome.model.item:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:120)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:272)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.access$1(FolderObserver.java:265)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$WatchQueueReader.processWatchEvent(FolderObserver.java:146)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
	at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(AbstractWatchQueueReader.java:122)[98:org.eclipse.smarthome.core:0.9.0.b4]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
```

**Comment by kaikreuzer** [comment]
Thanks for your report and sorry for having that unresolved for so long - the fix was actually pretty easy, I have created #205 for it.

**Comment by macmeck** [comment]
Hm @kaikreuzer, sure this #205 is working properly? It doesn't give errors any more but it seems to me that it's also not firing the binding for the group.

Using the latest unstable version of OH2, I have a test setup as follows:
`Switch helloSwitch "Hello Switch" (helloGroup) {exec=">[*:echo Hello switch]"}
Group:Switch:OR(ON,OFF) helloGroup "Hello Group" {exec=">[*:echo Hello group]"}`

Toggeling the switch shows that the group is being properly updated but the log only shows 

    2017-11-30 16:22:13.354 [INFO ] [ab.binding.exec.internal.ExecBinding] - executed commandLine 'echo Hello switch'
    2017-11-30 16:22:16.032 [INFO ] [ab.binding.exec.internal.ExecBinding] - executed commandLine 'echo Hello switch'

So no exec binding is fired for the group. I also tested other bindings with just the same behaviour.
