### ISSUE TITLE
MqttBrokerConnectionTests unstable

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-core#1139]
See e.g. Travis https://travis-ci.org/openhab/openhab-core/jobs/598834457

```
[ERROR] timeoutWhenNotReachableFuture(org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests)  Time elapsed: 0.205 s  <<< FAILURE!
org.mockito.exceptions.verification.NeverWantedButInvoked: 
connectionCallback.onFailure(<any>, <any>);
Never wanted here:
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests.timeoutWhenNotReachableFuture(MqttBrokerConnectionTests.java:225)
But invoked here:
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection.lambda$1(MqttBrokerConnection.java:733)
	at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests.timeoutWhenNotReachableFuture(MqttBrokerConnectionTests.java:225)
```

**Comment by cweitkamp** [comment]
One more (see Travis https://travis-ci.org/openhab/openhab-core/jobs/600039891).

```
[ERROR] reconnectPolicy(org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests)  Time elapsed: 0.067 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:

mqttBrokerConnectionEx.start();
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests.reconnectPolicy(MqttBrokerConnectionTests.java:167)

However, there were exactly 7 interactions with this mock:
mqttBrokerConnectionEx.setConnectionCallback(
    org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionEx$MockitoMock$1253350811@4aa3d36
);
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests.reconnectPolicy(MqttBrokerConnectionTests.java:143)

mqttBrokerConnectionEx.setReconnectStrategy(
    org.eclipse.smarthome.io.transport.mqtt.reconnect.PeriodicReconnectStrategy@2d140a7
);
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests.reconnectPolicy(MqttBrokerConnectionTests.java:146)

mqttBrokerConnectionEx.getReconnectStrategy();
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests.reconnectPolicy(MqttBrokerConnectionTests.java:147)

mqttBrokerConnectionEx.setReconnectStrategy(
    org.eclipse.smarthome.io.transport.mqtt.reconnect.PeriodicReconnectStrategy$MockitoMock$1533906995@2aa27288
);
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests.reconnectPolicy(MqttBrokerConnectionTests.java:156)

mqttBrokerConnectionEx.cancelTimeoutFuture();
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection$ConnectionCallback.onFailure(MqttBrokerConnection.java:148)

mqttBrokerConnectionEx.connectionState();
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection$ConnectionCallback.onFailure(MqttBrokerConnection.java:152)

mqttBrokerConnectionEx.getHost();
-> at org.eclipse.smarthome.io.transport.mqtt.reconnect.PeriodicReconnectStrategy.lambda$0(PeriodicReconnectStrategy.java:116)

	at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnectionTests.reconnectPolicy(MqttBrokerConnectionTests.java:167)
```

**Comment by wborn** [comment]
Hopefully https://github.com/openhab/openhab-core/pull/1125 is merged soon so we can see if it is still an issue and fix it without causing merge conflicts.
