### ISSUE TITLE
[automation] During start the Automation Provider Processing Queue throws an IAE

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-core#1163]
I can see this in my IDE and the unit / integration tests too.

```
15:35:09.731 [Automation Provider Processing Queue] ERROR org.openhab.core.automation.internal.provider.AbstractResourceBundleProvider - [Module Type] java.lang.IllegalArgumentException: The type must not be null!

org.openhab.core.automation.parser.ParsingException: [Module Type] java.lang.IllegalArgumentException: The type must not be null!

	at org.openhab.core.automation.internal.parser.gson.ModuleTypeGSONParser.parse(ModuleTypeGSONParser.java:61)
	at org.openhab.core.automation.internal.provider.AbstractResourceBundleProvider.parseData(AbstractResourceBundleProvider.java:410)
	at org.openhab.core.automation.internal.provider.AbstractResourceBundleProvider.processAutomationProvider(AbstractResourceBundleProvider.java:255)
	at org.openhab.core.automation.internal.provider.AutomationResourceBundlesEventQueue.processBundleChanged(AutomationResourceBundlesEventQueue.java:218)
	at org.openhab.core.automation.internal.provider.AutomationResourceBundlesEventQueue.run(AutomationResourceBundlesEventQueue.java:120)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Hilbrand** [comment]
Did you already fix this otherwise I'll provide a pr with a fix?
