### ISSUE TITLE
[lsp] Mousing-over an action in VS Code  generates CompletionException

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-core#1206]
Now that LSP is working again (thanks @wborn!!!), I'm see the following.

When mousing-over an action call in VS Code, a CompletionException is thrown. In the example below, this exception was thrown when I moused-over the `sendMail` part of the following statement:

```
mailActions.sendMail(address, subject, body)
```

```
2019-11-12 09:27:18.609 [ERROR] [eclipse.lsp4j.jsonrpc.RemoteEndpoint] - Internal error: java.lang.RuntimeException: Cannot create a resource for 'java:/Objects/org.openhab.binding.mail.action.SendMailActions'; a registered resource factory is needed
java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot create a resource for 'java:/Objects/org.openhab.binding.mail.action.SendMailActions'; a registered resource factory is needed
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_222]
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:43) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.RuntimeException: Cannot create a resource for 'java:/Objects/org.openhab.binding.mail.action.SendMailActions'; a registered resource factory is needed
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:262) ~[?:?]
	at org.eclipse.xtext.ide.server.ProjectManager.getResource(ProjectManager.java:174) ~[?:?]
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:327) ~[?:?]
	at org.eclipse.xtext.ide.server.findReferences.WorkspaceResourceAccess.readOnly(WorkspaceResourceAccess.java:42) ~[?:?]
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.doRead(DocumentSymbolService.java:363) ~[?:?]
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getDefinitions(DocumentSymbolService.java:125) ~[?:?]
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getDefinitions(DocumentSymbolService.java:106) ~[?:?]
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$37(LanguageServerImpl.java:623) ~[?:?]
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:334) ~[?:?]
	at org.eclipse.xtext.ide.server.LanguageServerImpl.definition(LanguageServerImpl.java:625) ~[?:?]
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$36(LanguageServerImpl.java:606) ~[?:?]
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37) ~[?:?]
	... 4 more```

**Comment by wborn** [comment]
I had a look and it was already an issue in 2.4.0 (see also, https://github.com/openhab/openhab-vscode/issues/131). It looks like there was never a resource factory set for java (actions, thing actions etc.).

For me these exceptions only show up in VS Code because the [lsp4j logger is turned off by default](https://github.com/openhab/openhab-distro/blob/df22e286746720dda793f68f8b1c0fa50f324313/distributions/openhab/src/main/resources/userdata/etc/org.ops4j.pax.logging.cfg#L74-L80).

Perhaps the VS Code extension can catch these exception and not show a stack trace @Confectrician?

The issue is not specific to actions because it can also be reproduced when CTRL clicking (or right clicking and choosing "Go to Definition" / F12) on methods like `postUpdate`, `forEach`, `maximumSince`, etc.

## Example VS Code errors

### postUpdate

```
[Error - 4:02:27 PM] Request textDocument/definition failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot create a resource for 'java:/Objects/org.eclipse.smarthome.model.script.actions.BusEvent'; a registered resource factory is needed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:43)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Cannot create a resource for 'java:/Objects/org.eclipse.smarthome.model.script.actions.BusEvent'; a registered resource factory is needed
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:262)
	at org.eclipse.xtext.ide.server.ProjectManager.getResource(ProjectManager.java:174)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:327)
	at org.eclipse.xtext.ide.server.findReferences.WorkspaceResourceAccess.readOnly(WorkspaceResourceAccess.java:42)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.doRead(DocumentSymbolService.java:363)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getDefinitions(DocumentSymbolService.java:125)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getDefinitions(DocumentSymbolService.java:106)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$37(LanguageServerImpl.java:623)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:334)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.definition(LanguageServerImpl.java:625)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$36(LanguageServerImpl.java:606)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
	... 4 more
```

### forEach

```
[Error - 4:03:39 PM] Request textDocument/definition failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot create a resource for 'java:/Objects/java.lang.Iterable'; a registered resource factory is needed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:43)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Cannot create a resource for 'java:/Objects/java.lang.Iterable'; a registered resource factory is needed
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:262)
	at org.eclipse.xtext.ide.server.ProjectManager.getResource(ProjectManager.java:174)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:327)
	at org.eclipse.xtext.ide.server.findReferences.WorkspaceResourceAccess.readOnly(WorkspaceResourceAccess.java:42)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.doRead(DocumentSymbolService.java:363)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getDefinitions(DocumentSymbolService.java:125)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getDefinitions(DocumentSymbolService.java:106)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$37(LanguageServerImpl.java:623)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:334)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.definition(LanguageServerImpl.java:625)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$36(LanguageServerImpl.java:606)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
	... 4 more
```

**Comment by mhilbush** [comment]
> For me these exceptions only show up in VS Code because the lsp4j logger is turned off by default.

Ah, I had those lines, but I also had it set to INFO level later in the file, which explains why I was seeing the exceptions.

**Comment by Confectrician** [comment]
>Perhaps the VS Code extension can catch these exception and not show a stack trace @Confectrician?

I am still avoiding looking into the LSP parts wherever i can. 🤷‍♂ 
But if i remember correctly, there is just a connection that is started and everything else (including those outputs) is done within the lsp client node package.

So i doubt, that we can influence this behavior with the standard toolbox.

**Comment by maisun** [comment]
Still no solution?
