### ISSUE TITLE
ChannelItemProviderTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1220]
This test failed in the Travis CI Java 11 build:

```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.501 s <<< FAILURE! - in org.eclipse.smarthome.core.thing.internal.ChannelItemProviderTest
[ERROR] testDisableBeforeDelayedInitialization(org.eclipse.smarthome.core.thing.internal.ChannelItemProviderTest)  Time elapsed: 0.143 s  <<< FAILURE!
org.mockito.exceptions.verification.NeverWantedButInvoked: 

listener.added(
    same(org.eclipse.smarthome.core.thing.internal.ChannelItemProvider@6dba847b),
    same(test (Type=NumberItem, State=NULL, Label=null, Category=null))
);
Never wanted here:
-> at org.eclipse.smarthome.core.thing.internal.ChannelItemProviderTest.testDisableBeforeDelayedInitialization(ChannelItemProviderTest.java:139)
But invoked here:
-> at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider.createItemForLink(ChannelItemProvider.java:289)

	at org.eclipse.smarthome.core.thing.internal.ChannelItemProviderTest.testDisableBeforeDelayedInitialization(ChannelItemProviderTest.java:139)
```

**Comment by J-N-K** [comment]
I have not seen this exception for quite a while now. Let's close it and re-open if it occurs again.
