### ISSUE TITLE
StringIndexOutOfBoundsException when converting 'DecimalType' to 'DateTimeType'

### ISSUE THREAD

**Issue by radokristof** [openhab/openhab-core#1231]
I get the following error since I updated to M5:

```
2019-11-20 16:32:15.390 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: String index out of range: 10

java.lang.StringIndexOutOfBoundsException: String index out of range: 10

	at java.lang.String.substring(String.java:1963) ~[?:1.8.0_222]

	at org.eclipse.smarthome.core.library.types.DateTimeType.<init>(DateTimeType.java:121) ~[?:?]

	at org.eclipse.smarthome.core.library.types.DecimalType.as(DecimalType.java:173) ~[?:?]

	at org.eclipse.smarthome.core.internal.items.ItemStateConverterImpl.convertToAcceptedState(ItemStateConverterImpl.java:64) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.sendUpdate(ProfileCallbackImpl.java:134) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onStateUpdateFromHandler(SystemDefaultProfile.java:53) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$9(CommunicationManager.java:467) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$11(CommunicationManager.java:487) ~[?:?]

	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_222]

	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.handleCallFromHandler(CommunicationManager.java:483) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.stateUpdated(CommunicationManager.java:465) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.stateUpdated(ThingManagerImpl.java:168) ~[?:?]

	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:257) ~[?:?]

	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:276) ~[?:?]

	at org.openhab.binding.kodi.internal.handler.KodiHandler.updateRating(KodiHandler.java:805) ~[?:?]

	at org.openhab.binding.kodi.internal.protocol.KodiConnection.requestPlayerItemUpdate(KodiConnection.java:672) ~[?:?]

	at org.openhab.binding.kodi.internal.protocol.KodiConnection.requestPlayerUpdate(KodiConnection.java:518) ~[?:?]

	at org.openhab.binding.kodi.internal.protocol.KodiConnection.updatePlayerStatus(KodiConnection.java:509) ~[?:?]

	at org.openhab.binding.kodi.internal.handler.KodiHandler.handleCommand(KodiHandler.java:306) ~[?:?]

	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:203) ~[?:?]

	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:267) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
This error happens on startup or at bundle refresh.

Also it doesn't update some chanels after this error.

**Comment by cweitkamp** [comment]
Probably related to #1158 .

FTR: https://community.openhab.org/t/2-5-milestone-5-issues/85680/55

Can you add an abstract of your item configuration for the channels you are talking about? Thanks.

**Comment by radokristof** [comment]
Sure! I haven't had much time to investigate it further yet, but 'CurrentTime', 'Duration' and 'Thumbnail', 'Fanart' are seems to be the ones which doesn't update after this. Interesting but for example the 'Title' seem to work even after this.

`Image                   KodiMediacenter_Fanart              "Fanart"                                                (gKodi) { channel="kodi:kodi:0d7b0ec3:fanart" }

Number:Time             KodiMediacenter_CurrentTime         "Current Time [JS(getMinutes.js):%s]"   <duration>      (gKodi) { channel="kodi:kodi:0d7b0ec3:currenttime" }

Image                   KodiMediacenter_Thumbnail           "Thumbnail"                                             (gKodi) { channel="kodi:kodi:0d7b0ec3:thumbnail" }
`

**Comment by cweitkamp** [comment]
Can you please check your item bound to the `rating` channel?

**Comment by radokristof** [comment]
Yes I have that channel linked with an item, here it is:

`String                  KodiMediacenter_Rating              "Rating"                                                (gKodi) { channel="kodi:kodi:0d7b0ec3:rating" }`

What else should I check on this?

**Comment by cweitkamp** [comment]
The the expected item type for the channel type `rating` is `Number`. The binding updates the items state with a `DecimalType`. The framework tries to convert the updated state to one off the accepted states of the `String` item which includes `DateTimeType`.

The conversion from `DecimalType` to `DateTimeType` is working unless the value for `DecimalType` is defined with decimal places.

@clinique Might I as you to have a look into it? Thanks.

```
    @Test
    public void testConversionToDateTimeTypeWorking() {
        assertEquals(new DateTimeType("2014-03-30T10:58:47+0000"),
                new DecimalType("1396177127").as(DateTimeType.class));

        assertEquals(new DateTimeType("1969-12-31T23:59:59+0000"), new DecimalType("-1").as(DateTimeType.class));
        assertEquals(new DateTimeType("1970-01-01T00:00:00+0000"), DecimalType.ZERO.as(DateTimeType.class));
        assertEquals(new DateTimeType("1970-01-01T00:00:01+0000"), new DecimalType("1").as(DateTimeType.class));
    }

    @Test
    public void testConversionToDateTimeTypeFailed() {
        assertEquals(new DateTimeType("1970-01-01T00:00:01+0000"), new DecimalType("1.0").as(DateTimeType.class));
        assertEquals(new DateTimeType("1970-01-01T00:00:01+0000"), new DecimalType("1.5").as(DateTimeType.class));
    }
```

**Comment by radokristof** [comment]
I have changed the item type to Number and I don't get that error. I don't know why it was String. This was changed in one of the previous Milestone versions?

**Comment by cweitkamp** [comment]
`rating` is a new channel. It always required item type `Number` (see https://github.com/openhab/openhab2-addons/pull/5510/files#diff-d4e03a6f88c0893c7ac8c189a97d606dR538). But do not mind about that. It revealed a bug in the framework which could be fixed before next release.

**Comment by radokristof** [comment]
I don't know why I had String instead of Number. But now it seems working. I will report here if not...

**Comment by cweitkamp** [comment]
The root cause is not solved yet.
