### ISSUE TITLE
nrjavaserial -> /dev/ttyUSB0 does not exist

### ISSUE THREAD

**Issue by jhlweb** [openhab/openhab-core#124]
Hi fairly new to OH2 but getting up to speed the last couple a weeks. 
I'm running OH2 on a Synology NAS (x86) with DSM 6.1 and i'm using the syno_spk pack installer. I got the latest version to work and updated my OH2 to build 814.
This al works fine but when trying to use the DSMR1 Binding I got the nvjavaserial exception NoSuchPortException.
After some reaching I found the DSMR2 Binding hoping this would solve it but no .. this needed a nrjavaserial. I found the original en tested it .. It did not work. 
Today I found issue #101 and #111 where  3.12.0-OH and 3.12.1-OH where posted. I put them in the addons dit beside the "org.openhab.binding.dsmr-2.1.0-SNAPSHOT" and got the same error.

> 2017-03-01 22:39:36.175 [INFO ] [org.apache.felix.fileinstall        ] - Installing bundle com.neuronrobotics.nrjavaserial / 3.12.1.OH
2017-03-01 22:39:36.249 [DEBUG] [com.neuronrobotics.nrjavaserial     ] - BundleEvent INSTALLED - com.neuronrobotics.nrjavaserial
2017-03-01 22:39:36.303 [DEBUG] [com.neuronrobotics.nrjavaserial     ] - BundleEvent RESOLVED - com.neuronrobotics.nrjavaserial
2017-03-01 22:39:36.308 [DEBUG] [com.neuronrobotics.nrjavaserial     ] - BundleEvent STARTING - com.neuronrobotics.nrjavaserial
2017-03-01 22:39:36.311 [DEBUG] [com.neuronrobotics.nrjavaserial     ] - BundleEvent STARTED - com.neuronrobotics.nrjavaserial
2017-03-01 22:39:36.313 [INFO ] [org.apache.felix.fileinstall        ] - Started bundle: file:/volume1/public/openHAB2/addons/nrjavaserial-3.12.1-OH.jar
2017-03-01 22:39:39.327 [INFO ] [org.apache.felix.fileinstall        ] - Installing bundle org.openhab.binding.dsmr;singleton:=true / 2.1.0.201702282146
2017-03-01 22:39:39.665 [INFO ] [org.apache.felix.fileinstall        ] - Started bundle: file:/volume1/public/openHAB2/addons/org.openhab.binding.dsmr-2.1.0-SNAPSHOT.jar
2017-03-01 22:39:39.924 [ERROR] [inding.dsmr.internal.device.DSMRPort] - Port /dev/ttyUSB0 does not exists
gnu.io.NoSuchPortException
        at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:273)[237:com.neuronrobotics.nrjavaserial:3.12.1.OH]
        at org.openhab.binding.dsmr.internal.device.DSMRPort.open(DSMRPort.java:176)[238:org.openhab.binding.dsmr:2.1.0.201702282146]
        at org.openhab.binding.dsmr.internal.device.DSMRDevice.handleInitializeDSMRDevice(DSMRDevice.java:353)[238:org.openhab.binding.dsmr:2.1.0.201702282146]
        at org.openhab.binding.dsmr.internal.device.DSMRDevice.handleDeviceState(DSMRDevice.java:228)[238:org.openhab.binding.dsmr:2.1.0.201702282146]
        at org.openhab.binding.dsmr.internal.device.DSMRDevice.access$1(DSMRDevice.java:215)[238:org.openhab.binding.dsmr:2.1.0.201702282146]
        at org.openhab.binding.dsmr.internal.device.DSMRDevice$1.run(DSMRDevice.java:193)[238:org.openhab.binding.dsmr:2.1.0.201702282146]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2017-03-01 22:39:39.931 [WARN ] [nding.dsmr.handler.DSMRBridgeHandler] - Received unknown state CONFIGURATION_PROBLEM

I'll also posted on the OH forum [post](https://community.openhab.org/t/help-wanted-dev-ttyusb0-does-not-exsits/24192) 

I checked with dmesg if the driver was faulty and it was and fixed that.
I set permissons for /dev/ttyUSB0 to 666 and added the -Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0 the the runtime/bin/setenv file 
And I added the openhad2 users to the root group hope that this would solve some.
Every time I restarted OH2 but still got the same problem over and over.

I'm now getting out of ideas what todo or to check. As I said my linux knowledge is not that good as it was 20years ago.

**Comment by jhlweb** [comment]
Oke I found the solution. Don't know why and how... but giving the users openhab access to the http users opened al port to be found by OH2

found this solution by asking synology for some help about this problem.
