### ISSUE TITLE
IllegalStateException in SseBroadcaster

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#1499]
Testing an openHAB3 distro, I just found this in my log, which should not occur:

 ```
11:55:46.801 [WARN ] [apache.cxf.jaxrs.sse.SseEventSinkImpl] - There are still SSE events the queue which may not be delivered (closing now)
11:55:46.802 [WARN ] [g.openhab.core.io.rest.SseBroadcaster] - failure
java.lang.IllegalStateException: The sink has been already closed
        at org.apache.cxf.jaxrs.sse.SseEventSinkImpl.close(SseEventSinkImpl.java:157) [bundleFile:1.0.8]
        at org.openhab.core.io.rest.SseBroadcaster.close(SseBroadcaster.java:148) [bundleFile:?]
        at org.openhab.core.io.rest.SseBroadcaster.lambda$2(SseBroadcaster.java:109) [bundleFile:?]
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986) [?:?]
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) [?:?]
        at org.apache.cxf.jaxrs.sse.SseEventSinkImpl.dequeue(SseEventSinkImpl.java:256) [bundleFile:1.0.8]
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1392) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.AsyncContextState$1.run(AsyncContextState.java:149) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) [bundleFile:9.4.20.v20190813]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by clinique** [comment]
I think I'm facing same or related issue with VolvoOnCall binding :
````
java.io.IOException: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@29cf3ad4::DecryptedEndPoint@243a7fcf{vocapi.wirelesscar.net/170.102.194.8:443<->/10.0.2.15:58372,OPEN,fill=-,flush=-,to=59/0}
````

````
2020-09-24 14:56:32.634 [WARN ] [pache.cxf.jaxrs.sse.SseEventSinkImpl] - There are still SSE events the queue which may not be delivered (closing now)
2020-09-24 14:57:52.611 [WARN ] [pache.cxf.jaxrs.sse.SseEventSinkImpl] - Prematurely completing the AsyncContext due to error encountered: org.eclipse.jetty.io.EofException
````

**Comment by schrej-zz** [comment]
Hi,
I still have warnings
[WARN ] [pache.cxf.jaxrs.sse.SseEventSinkImpl] - There are still SSE events the queue which may not be delivered (closing now)`
in my log. (OH 3.3.0-SNAPSHOT/Windows)
