### ISSUE TITLE
NPE When loading sitemap in 3.x

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-core#1624]
Attempting to migrate my home system this weekend to 3.x .  When loading a legacy sitemap I am getting a NPE when it tries to load some widgets. Looks like a null check was overlooked when migrating away from using apache-utils here:

https://github.com/openhab/openhab-core/blob/f52af0b7486de648185fd8b1318a461f9771cba1/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java#L1368

I would submit a PR as well, but i don't have my 3.x build environment yet working.  Stack trace below. 

```
java.lang.NullPointerException
	at org.openhab.core.ui.internal.items.ItemUIRegistryImpl.getUnitFromLabel(ItemUIRegistryImpl.java:1368)
	at org.openhab.core.ui.internal.items.ItemUIRegistryImpl.getUnitForWidget(ItemUIRegistryImpl.java:1344)
	at org.openhab.ui.basic.internal.render.AbstractWidgetRenderer.getUnitForWidget(AbstractWidgetRenderer.java:309)
	at org.openhab.ui.basic.internal.render.SetpointRenderer.renderWidget(SetpointRenderer.java:73)
	at org.openhab.ui.basic.internal.render.PageRenderer.renderWidget(PageRenderer.java:189)
	at org.openhab.ui.basic.internal.render.PageRenderer.processChildren(PageRenderer.java:155)
	at org.openhab.ui.basic.internal.render.PageRenderer.processChildren(PageRenderer.java:176)
	at org.openhab.ui.basic.internal.render.PageRenderer.processPage(PageRenderer.java:119)
	at org.openhab.ui.basic.internal.servlet.WebAppServlet.service(WebAppServlet.java:203)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:293)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kaikreuzer** [comment]
I've created https://github.com/openhab/openhab-core/pull/1625 for it.

**Comment by digitaldan** [comment]
Thanks!!!
