### ISSUE TITLE
GenericItemProviderTest unstable

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-core#1640]
These test failed on the Jenkins PR build ([#508](https://ci.openhab.org/job/openHAB-Core/508/console)) with the following stacktrace:

```
TEST org.openhab.core.model.item.internal.GenericItemProviderTest#assertThatTheItemRegistryGetsTheSameInstanceOnItemUpdatesWithoutChanges() <<< ERROR: 
Expected: a collection with size <1>
     but: collection size was <3>
java.lang.AssertionError: 
Expected: a collection with size <1>
     but: collection size was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.model.item.internal.GenericItemProviderTest.lambda$2(GenericItemProviderTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:73)
	at org.openhab.core.model.item.internal.GenericItemProviderTest.tearDown(GenericItemProviderTest.java:151)
        ...
```

**Comment by wborn** [comment]
Today `tearDown` failed for me locally:

```
TEST org.openhab.core.model.item.internal.GenericItemProviderTest#assertThatItemsAreRemovedCorrectlyIfTheModelGetsBroken() <<< ERROR: 
Expected: a collection with size <2>
     but: collection size was <3>
java.lang.AssertionError: 
Expected: a collection with size <2>
     but: collection size was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.model.item.internal.GenericItemProviderTest.lambda$2(GenericItemProviderTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:73)
	at org.openhab.core.model.item.internal.GenericItemProviderTest.tearDown(GenericItemProviderTest.java:151)
```
