### ISSUE TITLE
FolderObserverTest unstable

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-core#1653]
This test failed on the Jenkins PR build ([#2513](https://ci.openhab.org/job/PR-openHAB-Core/2513/)) with the following stacktrace:

```
TEST org.openhab.core.model.core.internal.folder.FolderObserverTest#testModification() <<< ERROR: 
Expected: is <true>
     but: was <false>
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.model.core.internal.folder.FolderObserverTest.lambda$7(FolderObserverTest.java:223)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:84)
	at org.openhab.core.model.core.internal.folder.FolderObserverTest.testModification(FolderObserverTest.java:223)
        ...
```

**Comment by wborn** [comment]
It's still occurring and didn't get fixed by itself, see this GHA build: https://github.com/openhab/openhab-core/runs/4092543361:

```
TEST org.openhab.core.model.core.internal.folder.FolderObserverTest#testModification() <<< ERROR: 
Expected: is <true>
     but: was <false>
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.model.core.internal.folder.FolderObserverTest.lambda$7(FolderObserverTest.java:216)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:84)
	at org.openhab.core.model.core.internal.folder.FolderObserverTest.testModification(FolderObserverTest.java:216)
```

**Comment by cweitkamp** [comment]
One more time - I think we have to look into it soon if we want to harden our builds:

https://github.com/openhab/openhab-core/runs/4117247956

**Comment by J-N-K** [comment]
Could this be fixed with the latest improvements to the `AbstractWatchService`?

**Comment by wborn** [comment]
Let's reopen this issue the next time it occurs.
