### ISSUE TITLE
ThingTypeXmlProvider : java.lang.ClassCastException: class org.openhab.core.config.xml.util.NodeList cannot be cast to class java.util.List

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-core#1771]
For a binding under development (fork of the knx binding) in the 3.0.0 branch, with a .xml containing a bunch of <config-description:config-descriptions>, during XML parsing the following is thrown:

```
[le-processing-4] WARN  o.o.c.c.x.o.XmlDocumentBundleTracker:406 - The XML document '/OH-INF/thing/channels.xml' in module 'org.openhab.binding.knx' could not be parsed: class org.openhab.core.config.xml.util.NodeList cannot be cast to class java.util.List (org.openhab.core.config.xml.util.NodeList is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @280d5a82; java.util.List is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class org.openhab.core.config.xml.util.NodeList cannot be cast to class java.util.List (org.openhab.core.config.xml.util.NodeList is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @280d5a82; java.util.List is in module java.base of loader 'bootstrap')
	at org.openhab.core.thing.xml.internal.ThingTypeXmlProvider.addingObject(ThingTypeXmlProvider.java:1)
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker.addingObject(XmlDocumentBundleTracker.java:237)
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker.parseDocuments(XmlDocumentBundleTracker.java:398)
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker.processBundle(XmlDocumentBundleTracker.java:382)
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker$2.run(XmlDocumentBundleTracker.java:347)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kgoderis** [comment]
When I move the offending XML to a different subfolder, for example from OH-INF\thing to OH-INF\channnels, this problem goes away. When I put it back in its original folder (OH-INF\thing), the problem resurrects. It seems to indicate that mingling XMLs with different types of content (config-description, thing-description,...) is  causing the issue, which is hard to believe.

**Comment by kaikreuzer** [comment]
Do you still see this? If so, can you post files and instructions to reproduce it?

**Comment by J-N-K** [comment]
No feedback for over a year, if this pops up again, please provide the offending file and open a new issue. Thanks.
