### ISSUE TITLE
[OH3] NullPointerException with rule trigger "a member of an item group receives a command" and empty command

### ISSUE THREAD

**Issue by MikeJMajor** [openhab/openhab-core#1793]
Attempting to use `a member of an item group receives a command` rule trigger without specifying a command results in a NullPointerException when the rule runs:

![image](https://user-images.githubusercontent.com/24585489/98017421-20d6ae80-1df7-11eb-8849-089c9e12526d.png)

```
java.lang.NullPointerException: null
        at org.openhab.core.automation.internal.module.handler.GroupCommandTriggerHandler.receive(GroupCommandTriggerHandler.java:102) ~[?:?]
        at org.openhab.core.internal.events.EventHandler.lambda$0(EventHandler.java:152) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by HazeHunter11** [comment]
I can confirm this bug, noticed the same right now on OH3 M2 release. I tested this with a nearly empty rule. The rule should only write a logger entry, but it is not fired due to the error.

The following error message appears:

```
2020-11-07 13:05:27.993 [WARN ] [ab.core.internal.events.EventHandler] - Dispatching/filtering event for subscriber 'org.openhab.core.events.EventSubscriber' failed: null
java.lang.NullPointerException: null
	at org.openhab.core.automation.internal.module.handler.GroupCommandTriggerHandler.receive(GroupCommandTriggerHandler.java:102) ~[?:?]
	at org.openhab.core.internal.events.EventHandler.lambda$0(EventHandler.java:152) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```
