### ISSUE TITLE
[OH3] DSL rule: newState invalid value for rule trigger "received update"

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1802]
The implicit variable `newState` is providing the state of another item (not the one triggering the rule) when used in a DSL rule with trigger "received update".
Example of rule:
```
rule "Minimote"
when
	Item MinimoteScene received update
then
	logInfo("Rule","rule Minimote - scene number " + newState.toString)
	var Number bouton = newState as DecimalType
end
```
Here are logs:
```
12:09:07.532 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'DetecteurChambre' changed from NULL to OPEN
12:09:21.826 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'MinimoteScene' changed from NULL to 1
12:09:21.840 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
12:09:21.862 [ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'maison3-8' failed: Could not cast OPEN to org.openhab.core.library.types.DecimalType; line 205, column 22, length 23 in maison3
...
12:18:18.805 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'MinimoteScene' changed from 3 to 1
12:18:18.819 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number 107
```

**Comment by kaikreuzer** [comment]
Is this reliably reproducible or might it only happen on race conditions?

**Comment by lolodomo** [comment]
For me, it is systematic and reliably reproducible.

**Comment by kaikreuzer** [comment]
So which event do you reliably get? The one that was sent just before the one you expect?

**Comment by lolodomo** [comment]
No it is not always the previous one. My feeling is that it can even be an old state. 
I can try to investigate a little more in this director if you think it is important.

**Comment by lolodomo** [comment]
I find no logic. Here are the logs when I call several times the rules:
```
14:47:36.123 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'Detecteur2Chambre' changed from OFF to ON
14:47:36.138 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'DetecteurChambre' changed from CLOSED to OPEN
14:47:37.712 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'DetecteurSalon' changed from OPEN to CLOSED
14:47:45.156 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'MinimoteScene' changed from 2 to 1
14:47:45.164 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:47:49.498 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:47:51.577 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'Date' changed from 2020-11-08T14:46:51.566+0100 to 2020-11-08T14:47:51.568+0100
14:47:52.268 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'LampeChevet1' changed from 0 to 100
14:47:52.283 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'LampeChevet2' changed from 0 to 100
14:47:52.385 [INFO ] [home.event.GroupItemStateChangedEvent] - Item 'GEclairage' changed from OFF to ON through LampesHueChambre
14:47:52.394 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'LampesHueChambre' changed from 0 to 100
14:47:52.678 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:47:58.207 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:48:01.549 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:48:06.141 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:48:09.594 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:48:15.145 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:48:24.053 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'TemperatureVeranda' changed from 23.1 to 23.0
14:48:32.098 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'MinimoteScene' changed from 1 to 2
14:48:32.104 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:48:32.122 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
14:48:32.930 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'LampeChevet1' changed from 100 to 0
14:48:32.947 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'LampeChevet2' changed from 100 to 75
14:48:33.052 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'LampesHueChambre' changed from 100 to 75
14:48:42.672 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'MinimoteScene' changed from 2 to 1
14:48:42.673 [INFO ] [org.openhab.core.model.script.Rule   ] - rule Minimote - scene number OPEN
```
Just to be clear in these logs, the scene number displayed by the rule should be the state of item MinimoteScene.
As you can see, it looks like the variable is first set incorrectly with the value of an unexpected item and then it looks like it is not updated.

**Comment by lolodomo** [comment]
@kaikreuzer : just an idea because I am not at all aware of the automation code.
At this line, I am asking myself if you should not add an entry "state" mapping "newState" ?
https://github.com/openhab/openhab-core/blob/749b8f17fef8e8c8ac602be8d2a43925b11310fd/bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java#L57

**Comment by kaikreuzer** [comment]
@lolodomo Your analysis is absolutely correct. 👍 
I was able to reproduce it and can confirm that this fixes the issue - I have created #1809 for it.

**Comment by lolodomo** [comment]
@kaikreuzer : is the fix included in snapshot 2008 ? Because it still does not work for me.

**Comment by kaikreuzer** [comment]
Have a look at the version of the bundles and find the answer yourself 😎 
```
openhab> list -s | grep openhab.core
128 │ Active   │  80 │ 3.0.0.202011120732      │ org.openhab.core
```

**Comment by cribskip** [comment]
With snapshot 2009 I'm not able to run ANY DSL rule anymore.
openhab.log outputs simply:
`2020-11-15 10:43:52.390 [ERROR] [e.automation.internal.RuleEngineImpl] - Failed to execute rule '9ca9284fc8': Fail to execute action: 2
`

But when the rule is run by clicking Run in the web ui I get a full stack trace presumable referencing this patch:
```
2020-11-15 10:42:45.373 [WARN ] [e.automation.internal.RuleEngineImpl] - Fail to execute action: 2
java.lang.IllegalStateException: Cannot create a duplicate value 'newState'.
        at org.eclipse.xtext.xbase.interpreter.impl.DefaultEvaluationContext.newValue(DefaultEvaluationContext.java:46) ~[?:?]
        at org.openhab.core.model.script.runtime.internal.engine.DSLScriptEngine.createEvaluationContext(DSLScriptEngine.java:143) ~[?:?]
        at org.openhab.core.model.script.runtime.internal.engine.DSLScriptEngine.eval(DSLScriptEngine.java:118) ~[?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:62) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.execute(ScriptActionHandler.java:59) ~[?:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1179) [bundleFile:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.runNow(RuleEngineImpl.java:1031) [bundleFile:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.runNow(RuleEngineImpl.java:1047) [bundleFile:?]
        at org.openhab.core.automation.rest.internal.RuleResource.runNow(RuleResource.java:305) [bundleFile:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [bundleFile:1.0.9]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [bundleFile:1.0.9]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [bundleFile:1.0.9]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [bundleFile:1.0.9]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:1.0.9]
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [bundleFile:1.0.9]
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [bundleFile:1.0.9]
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [bundleFile:1.0.9]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [bundleFile:1.0.9]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [bundleFile:1.0.9]
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [bundleFile:1.0.9]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [bundleFile:1.0.9]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220) [bundleFile:1.0.9]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [bundleFile:3.1.0]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [bundleFile:1.0.9]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544) [bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [bundleFile:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307) [bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:293) [bundleFile:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [bundleFile:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.Server.handle(Server.java:494) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) [bundleFile:9.4.20.v20190813]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

I did not declare or even use newState in any rule present, so this has to be the implicit one causing the problem.

**Comment by kaikreuzer** [comment]
@cribskip See https://github.com/openhab/openhab-core/issues/1818

**Comment by lolodomo** [comment]
I can confirm that the issue is fixed in snapshot 2010. Great ;)

**Comment by DJPsycho82** [comment]
As addition at openhab-bot (that was my post on the Community), some extra info regarding the wrong newState value:

The strange thing is, newState works for both types of state changes ('received update' and 'changed'). I use it on rules with only “changed” triggers and rules with only “received update” triggers. Both work perfectly in a lot of my rules. But if I combine “changed” and “received update” in a rule with two triggers for 2 types of items the state of newState is incorrect and doesn't change anymore after another state change.
