### ISSUE TITLE
Rule condition with DSL script results in error.

### ISSUE THREAD

**Issue by gnlpfjh** [openhab/openhab-core#1946]
I get the folowing error if I use a DSL script as condition ("But only if") in a rule.

```
16:10:52.358 [ERROR] [re.automation.internal.RuleEngineImpl] - Failed to execute rule 'eba3ad4b4b': null
16:10:52.359 [DEBUG] [re.automation.internal.RuleEngineImpl] -
java.lang.NullPointerException: null
        at org.openhab.core.automation.module.script.internal.handler.ScriptConditionHandler.isSatisfied(ScriptConditionHandler.java:58) ~[?:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.calculateConditions(RuleEngineImpl.java:1147) ~[bundleFile:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.runRule(RuleEngineImpl.java:983) [bundleFile:?]
        at org.openhab.core.automation.internal.TriggerHandlerCallbackImpl$TriggerData.run(TriggerHandlerCallbackImpl.java:89) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
1
```

**Test case** (tested with Build 2050 and 2081):
I've created two Switch Items `TestItem1` and `TestItem2` to trigger the folowing rule.

```
triggers:
  - id: "1"
    configuration:
      itemName: TestItem1
    type: core.ItemStateChangeTrigger
conditions:
  - inputs: {}
    id: "3"
    configuration:
      type: application/vnd.openhab.dsl.rule
      script: "true"
    type: script.ScriptCondition
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: TestItem1
      command: ON
    type: core.ItemCommandAction
```

I've tried it with different scripts: 'true', 'return true'... I can log some message but at the end it always results in the same error.

 
 
I briefly looked in the source code and found that the eval method in *DSLScriptEngine.java* always returns null. I'm not sure but it looks to me like that is the problem.

**Comment by cweitkamp** [comment]
I have to admit that I do not know how the script should look like. But I submitted #1948 to prevent the NPE.
