### ISSUE TITLE
AutomationIntegrationTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1949]
This test failed in [openHAB-Core #619](https://ci.openhab.org/job/openHAB-Core/619) with the following stack trace:

```
TEST org.openhab.core.automation.integration.test.AutomationIntegrationTest#testChainOfCompositeModules() <<< ERROR: 
Expected: is not null
     but: was null
java.lang.AssertionError: 
Expected: is not null
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.automation.integration.test.AutomationIntegrationTest.lambda$19(AutomationIntegrationTest.java:626)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:84)
	at org.openhab.core.automation.integration.test.AutomationIntegrationTest.testChainOfCompositeModules(AutomationIntegrationTest.java:625)
```

**Comment by kaikreuzer** [comment]
I am pretty sure that this is fixed by https://github.com/openhab/openhab-core/pull/1944 as well. Feel free to re-open if it indeed still occurs.
