### ISSUE TITLE
exception on rollershutter status

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#200]
I hope openhab-core is the right place to address this issue to. I don't know where the problem ultimately is, might be inside ESH as well,

Using recent 2.2 snapshots (currently #1020), I keep getting the exception below whenever a ZWave rollershutter actuator of mine reports its state. FWIW, I also included the message causing this.
I still believe 96 to be between 0 and 100 unless we operate in some strange mathmatical dimension.
But it happens with various actuators and different values, too.

`Rollershutter EG_Wohnen_Jalousie_links "Raffstore links [%.0f %%]"          <rollershutter> (EG_Wohnen,Rolladen,Jalousien) { zwave="113:command=switch_multilevel,invert_state=false,invert_percent=true" }
`
(note it's %.0f now but %d before didn't make a difference)

```
2017-08-24 08:00:08.156 [DEBUG] [l.ZWaveController$ZWaveReceiveThread] - Receive Message = 01 09 00 04 00 71 03 26 03 60 C5
2017-08-24 08:00:08.183 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
2017-08-24 08:00:08.183 [DEBUG] [l.ZWaveController$ZWaveReceiveThread] - Receive queue ADD: Length=1
2017-08-24 08:00:08.186 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 09 00 04 00 71 03 26 03 60 C5
2017-08-24 08:00:08.189 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 09 00 04 00 71 03 26 03 60 C5
2017-08-24 08:00:08.192 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 71 03 26 03 60 , callbackid = 0
2017-08-24 08:00:08.195 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 113: Application Command Request (ALIVE:DONE)
2017-08-24 08:00:08.199 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 113: Incoming command class SWITCH_MULTILEVEL (0x26)
2017-08-24 08:00:08.202 [DEBUG] [ss.ZWaveMultiLevelSwitchCommandClass] - NODE 113: Received Switch Multi Level Request
2017-08-24 08:00:08.204 [DEBUG] [ss.ZWaveMultiLevelSwitchCommandClass] - NODE 113: Switch Multi Level report, value = 96
2017-08-24 08:00:08.207 [DEBUG] [ve.internal.protocol.ZWaveController] - NODE 113: Notifying event listeners: ZWaveCommandClassValueEvent
2017-08-24 08:00:08.210 [DEBUG] [ng.zwave.internal.ZWaveActiveBinding] - ZwaveIncomingEvent
2017-08-24 08:00:08.212 [DEBUG] [ng.zwave.internal.ZWaveActiveBinding] - NODE 113: Got a value event from Z-Wave network, endpoint = 0, command class = SWITCH_MULTILEVEL, value = 96


2017-08-24 08:00:08.221 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener '[Jalousien (Type=GroupItem, BaseType=RollershutterItem, Members=6, State=100.00000000, Label=Jalousien, Category=rollershutter, Groups=[All]), EG_Wohnen_Jalousie_links, Value must be between 0 and 100]' about state update of item {}: {}
java.lang.IllegalArgumentException: Value must be between 0 and 100
        at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:50) [98:org.eclipse.smarthome.core:0.9.0.201708151402]
        at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:45) [98:org.eclipse.smarthome.core:0.9.0.201708151402]
        at org.eclipse.smarthome.core.library.types.DecimalType.as(DecimalType.java:153) [98:org.eclipse.smarthome.core:0.9.0.201708151402]
        at org.eclipse.smarthome.core.items.ItemUtil.convertToAcceptedState(ItemUtil.java:87) [98:org.eclipse.smarthome.core:0.9.0.201708151402]
        at org.eclipse.smarthome.core.items.GroupItem.stateUpdated(GroupItem.java:322) [98:org.eclipse.smarthome.core:0.9.0.201708151402]
        at org.eclipse.smarthome.core.items.GenericItem$1.run(GenericItem.java:227) [98:org.eclipse.smarthome.core:0.9.0.201708151402]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by kaikreuzer** [comment]
As you can see from the stacktrace, ESH would indeed be the better place.
But anyhow, I cannot reproduce the issue. Note that it happens when updating your "Jalousien" group item, not the EG_Wohnen_Jalousie_links itself.

Please try to come up with a simple reproducible setup. Here is mine:
```
Group:Rollershutter gShutters
Rollershutter DemoRollershutter (gShutters)
```
Sending a state update on the console gives:
```
openhab> smarthome:update DemoRollershutter 96
Update has been sent successfully.
10:47:28.487 INFO  smarthome.event.ItemStateEvent[:47] - DemoRollershutter updated to 96
10:47:28.489 INFO  s.event.ItemStateChangedEvent[:47] - DemoRollershutter changed from 100 to 96
10:47:28.489 INFO  s.e.GroupItemStateChangedEvent[:47] - gShutters changed from 100 to 96 through DemoRollershutter
```

**Comment by mstormi** [comment]
Thanks for pointing out it's the group, I hadn't noticed.
Ok, I had this definition:
`//Group:Rollershutter:SUM Jalousien             "Jalousien"                                   <rollershutter>         (All)`

Now unlike with contacts, to have a sum on _closing percentages_ of a group of shutters does not make much sense anyway, so I removed the :SUM. That seems to have fixed it, no more exceptions.

Now I'm unsure if that's a (ESH) bug we should have the ESH people hunt down, or just ignore it, but maybe there's groups of other item types affected, too.
what do you think? Please either close or forward this issue. Thanks for your help.

**Comment by kaikreuzer** [comment]
Well, no need to report any bug because the behavior is imho fully correct: The sum of your rollershutter states is clearly more than 100 and thus an invalid state. Fully correct behavior of the system therefore (and the log message is already fixed and will look a bit nicer in future builds).
