### ISSUE TITLE
File Not Found Exception of rule file in correct folder OH3.0.0

### ISSUE THREAD

**Issue by JAMESBOWLER** [openhab/openhab-core#2042]
Had a problem with rule file not working found entry in log `Error during request: `

`/etc/openhab/etc/openhab/rules/JSON_MAGIC.rules (No such file or directory)`

I edited the rule file adding a new line and the rule started working again.

## Log
```javascript
2021-01-01 20:55:10.571 [ERROR] [xt.ide.server.concurrent.ReadRequest] - Error during request: 

org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /etc/openhab/etc/openhab/rules/JSON_MAGIC.rules (No such file or directory)

	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319) ~[bundleFile:?]

	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278) ~[bundleFile:?]

	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:266) ~[bundleFile:?]

	at org.eclipse.xtext.ide.server.ProjectManager.getResource(ProjectManager.java:169) ~[bundleFile:?]

	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:436) ~[bundleFile:?]

	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$doRead$1(LanguageServerImpl.java:1093) ~[bundleFile:?]

	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:66) [bundleFile:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:834) [?:?]

Caused by: java.io.FileNotFoundException: /etc/openhab/etc/openhab/rules/JSON_MAGIC.rules (No such file or directory)

	at java.io.FileInputStream.open0(Native Method) ~[?:?]

	at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]

	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]

	at org.eclipse.emf.ecore.resource.impl.FileURIHandlerImpl.createInputStream(FileURIHandlerImpl.java:99) ~[bundleFile:?]

	at org.eclipse.xtext.resource.ExternalContentSupport$ExternalContentAwareURIHandler.createInputStream(ExternalContentSupport.java:75) ~[bundleFile:?]

	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360) ~[bundleFile:?]

	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:299) ~[bundleFile:?]

	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314) ~[bundleFile:?]

	at org.eclipse.xtext.resource.persistence.StorageAwareResource.load(StorageAwareResource.java:64) ~[bundleFile:?]

	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259) ~[bundleFile:?]

	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274) ~[bundleFile:?]
```	

## Environment

```YAML
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_AU
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 71651928
  totalMemory: 201326592
bindings:
  - bluetooth
  - mqtt
  - sensibo
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2021-01-01T14:15:09.760Z
```

**Comment by kaikreuzer** [comment]
Did you use the VS Code extension when editing the file? The exception looks related to that.
I doubt that we can do much about it, since there isn't a single class of openHAB involved in the stacktrace...

**Comment by JAMESBOWLER** [comment]
Kai thankyou for looking at this. Yes I do use the VS Code extension. As the issue is not with openHAB I will look elsewhere and close issue.
