### ISSUE TITLE
Concurrency errors when editing files with VS Code on shared folder

### ISSUE THREAD

**Issue by assert-not-singularity** [openhab/openhab-core#2111]
Hi everyone!

On my fresh OH3 installation the following errors are spammed to the console when trying to edit rule files in VS Code: 

```text
18:35:56.886 [ERROR] [ext.ide.server.concurrent.ReadRequest] - Error during request:
java.lang.IndexOutOfBoundsException: Position [
  line = 24
  character = 50
] text was : val int HeatingLeadTimeMinutes = 60

var Timer timer = null
var Timer delayedTimer = null
var DateTimeType preStart = null
var DateTimeType wakeupTime = null

// <remaining content of rule file>

        at org.eclipse.xtext.ide.server.Document.getOffSet(Document.java:62) ~[bundleFile:?]
        at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getDefinitions(DocumentSymbolService.java:98) ~[bundleFile:?]
        at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$24(LanguageServerImpl.java:603) ~[bundleFile:?]
        at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:438) ~[bundleFile:?]
        at org.eclipse.xtext.ide.server.LanguageServerImpl.definition(LanguageServerImpl.java:602) ~[bundleFile:?]
        at org.eclipse.xtext.ide.server.LanguageServerImpl.definition(LanguageServerImpl.java:590) ~[bundleFile:?]
        at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$23(LanguageServerImpl.java:581) ~[bundleFile:?]
        at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:66) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

For the errors to occur I don't necessarily need to save the file, they even occur when clicking or typing in the rule file. The rapid and repeated output of this error makes the console quite unreadable.

The environment I've experiencing this errors in is the official latest (3.0.0) OpenHAB docker image running on a Synology Diskstation. The volumes are mounted as a shared folder which is accessed via Visual Studio Code with the latest OpenHAB extension (0.8.0) installed. I also noticed a lot of errors of this kind:

```[ERROR] [pse.xtext.ide.server.WorkspaceManager] - The document file:///openhab/conf/rules/alarms.rules has not been opened.```

These are sometimes spammed about ~40 times within an interval of ~10 seconds.

**Comment by assert-not-singularity** [comment]
Any news on this? The issue is still present and just added ~10 k lines of errors to my openhab.log in a short period of time.

**Comment by mpmario** [comment]
Similar to me, but I tried to change an item file. Really annoying...

 ```
[Error - 10:32:05 PM] Request textDocument/completion failed.

  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Position [
  line = 11
  character = 1
] text was : 

// several item descriptions

	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.logAndCompleteExceptionally(AbstractRequest.java:73)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException: Position [
  line = 11
  character = 1
] text was : 

// same item descriptions

	at org.eclipse.xtext.ide.server.Document.getOffSet(Document.java:62)
	at org.eclipse.xtext.ide.server.contentassist.ContentAssistService.createCompletionList(ContentAssistService.java:74)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$23(LanguageServerImpl.java:555)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:438)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.completion(LanguageServerImpl.java:554)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$22(LanguageServerImpl.java:540)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:66)
	... 5 more

[Error - 10:34:49 PM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Position [
  line = 11
  character = 89
] text was : 

// same item descriptions
// and ongoing...
```
