### ISSUE TITLE
ConfigDescriptionsTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#2139]
This test failed in: https://ci.openhab.org/job/PR-openHAB-Core/3054/

```
TEST org.openhab.core.config.xml.test.ConfigDescriptionsTest#assertThatConfigDescriptionsAreLoadedProperly() <<< ERROR: 
Expected: is "Sekunden"
     but: was "seconds"
java.lang.AssertionError: 
Expected: is "Sekunden"
     but: was "seconds"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.config.xml.test.ConfigDescriptionsTest.lambda$1(ConfigDescriptionsTest.java:214)
	at org.openhab.core.config.xml.test.BindingInstaller.exec(BindingInstaller.java:53)
	at org.openhab.core.config.xml.test.ConfigDescriptionsTest.assertThatConfigDescriptionsAreLoadedProperly(ConfigDescriptionsTest.java:63)
```

**Comment by J-N-K** [comment]
I have not seen this test fail for a long time. Probably it has been fixed by some improvement to the tests in the past. If this re-occurs, we can open a new issue.
