### ISSUE TITLE
NPE in ChannelEventTriggerHandler

### ISSUE THREAD

**Issue by stefan-hoehn** [openhab/openhab-core#2239]
I defined a channel trigger like so

triggers:

  - id: "1"
    configuration:
      thingUID: nanoleaf:lightpanel:D81E7A7E424E:19209
      event: SHORT_PRESSED
      channelUID: nanoleaf:lightpanel:D81E7A7E424E:19209:tap
    type: core.ChannelEventTrigger
conditions: []
actions: []

which is actually processed but in the background a null pointer exception occurs at [ChannelEventTriggerHandler.java](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ChannelEventTriggerHandler.java) in line 91

`if (cte.getTopic().contains(this.channelUID)) {
`
which is reflected in the following stacktrace (I set the logging to "trace")

```
2021-03-13 17:50:24.057 [TRACE] [e.handler.ChannelEventTriggerHandler] - ->FILTER: openhab/channels/nanoleaf:lightpanel:D81E7A7E424E:19209:tap/triggered:openhab/channels/*/triggered

2021-03-13 17:50:24.057 [TRACE] [e.handler.ChannelEventTriggerHandler] - Received Event: Source: null Topic: openhab/channels/nanoleaf:lightpanel:D81E7A7E424E:19209:tap/triggered Type: ChannelTriggeredEvent  Payload: {"event":"SHORT_PRESSED","channel":"nanoleaf:lightpanel:D81E7A7E424E:19209:tap"}

2021-03-13 17:50:24.058 [ERROR] [internal.events.ThreadedEventHandler] - Error on event handling.

java.lang.NullPointerException: null
	at java.lang.String.contains(String.java:2036) ~[?:?]
	at org.openhab.core.automation.internal.module.handler.ChannelEventTriggerHandler.apply(ChannelEventTriggerHandler.java:91) ~[?:?]
	at org.openhab.core.internal.events.EventHandler.dispatchEvent(EventHandler.java:143) ~[bundleFile:?]
	at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:111) ~[bundleFile:?]
	at org.openhab.core.internal.events.EventHandler.handleEvent(EventHandler.java:84) ~[bundleFile:?]
	at org.openhab.core.internal.events.ThreadedEventHandler.lambda$0(ThreadedEventHandler.java:67) [bundleFile:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
To me it looks like for some reason the topic in this case is unexpectedly NULL as you can see from this trace output

> Received Event: Source: null Topic

Does anyone have an idea what a topic in this case is, where it comes from and why it is NULL in this case?

TIA
Stefan

**Comment by kaikreuzer** [comment]
The topic is correctly set, see the log: `Topic: openhab/channels/nanoleaf:lightpanel:D81E7A7E424E:19209:tap/triggered`

If it were not, the NPE would have occurred in `ChannelEventTriggerHandler.java:91` and not in `String.java:2036`.
It hence means that `channelUID` is null. As it is a mandatory parameter, this should never happen.
Can you debug, why the configuration does not contain a value for `channelUID`?

**Comment by cweitkamp** [comment]
Sounds similar to https://github.com/openhab/openhab-core/issues/2231.

**Comment by Confectrician** [comment]
>Sounds similar to #2231.

Thanks @cweitkamp just wanted to jump in and ask about it.

If there is anything i can help with debugging please tell me and i will try to get some more data.

**Comment by kaikreuzer** [comment]
Indeed a duplicate. Let's close this.
