### ISSUE TITLE
[monitor] Micrometer raises unchecked exception during OH start

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-core#2389]
This exception causes the task in `StartLevelService` to terminate when processing the callbacks of startlevel 40. The exception is swallowed. I added a temporary catch clause to log it. The only visible sympthom I noticed is that the rule engine is not started sometimes.
```
23:29:07.993 [DEBUG] [.internal.DefaultMetricsRegistration] - Registering meters...
23:29:08.010 [DEBUG] [o.monitor.internal.metrics.JVMMetric] - JVMMetric is being bound...
23:29:28.660 [WARN ] [enhab.core.service.StartLevelService] - 
java.lang.NoClassDefFoundError: javax/management/ListenerNotFoundException
	at org.openhab.core.io.monitor.internal.metrics.JVMMetric.bindTo(JVMMetric.java:57) ~[?:?]
	at org.openhab.core.io.monitor.internal.DefaultMetricsRegistration.lambda$0(DefaultMetricsRegistration.java:96) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.openhab.core.io.monitor.internal.DefaultMetricsRegistration.registerMeters(DefaultMetricsRegistration.java:96) ~[?:?]
	at org.openhab.core.io.monitor.internal.DefaultMetricsRegistration.onReadyMarkerAdded(DefaultMetricsRegistration.java:105) ~[?:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.lambda$0(ReadyServiceImpl.java:52) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.notifyTrackers(ReadyServiceImpl.java:79) ~[?:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.markReady(ReadyServiceImpl.java:52) ~[?:?]
	at org.openhab.core.service.StartLevelService.setStartLevel(StartLevelService.java:249) ~[?:?]
	at org.openhab.core.service.StartLevelService.lambda$0(StartLevelService.java:125) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.management.ListenerNotFoundException cannot be found by org.openhab.core.io.monitor_3.1.0.202105270818
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 26 more
```

I'm under Windows and I'm using the `openhab-distro` eclipse environment.

@pravussum

**Comment by pravussum** [comment]
Hey @fwolter, which JDK are you running this on?

**Comment by fwolter** [comment]
Oracle JDK 11.0.8 or 11.0.11. I don't know which version as I made an update during this time.

**Comment by fwolter** [comment]
I just encountered the exception again with Oracle JDK 11.0.11. It seems reproducible. Well, as reproducible a race condition can be.

**Comment by pravussum** [comment]
@fwolter Would it be possible for you to test my fix attempt from https://github.com/pravussum/openhab-core/tree/issue-2389?
Since I'm running Ubuntu and use IntelliJ it's kind of hard for me to reproduce...

**Comment by fwolter** [comment]
Hm, when I click on the bnd resolve button in eclipse, I get the following message:
```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.openhab.core.io.monitor)
          ⇒ [org.openhab.core.io.monitor version=3.1.0.202106121042]
              ⇒ osgi.wiring.package: (osgi.wiring.package=javax.sql.DataSource)
```

**Comment by pravussum** [comment]
Could you try it again, please? I didn't get a new Eclipse installation to successfully build the freshly checked-out project and have a hard time to get this OSGI/bnd stuff right :-(
I usually use IntelliJ and there the build runs successfully and I didn't get any errors during my tests. They don't have such a sophisticated bnd & OSGI support, though.

**Comment by fwolter** [comment]
I don't get behind the magic of bnd, sometimes. There seems to be a circular dependency, now. The log file is growing rapidly, and the resolution stucks at org.apache.servicemix.specs.jaxb-api-2.3. I tried it several times and it seems reproducible.
```
Log too large. Split from C:\Users\FABIAN~1\AppData\Local\Temp\tmp886089682887772692.log
size 3323 Kb
===================
INFO: Using frameowork org.eclipse.osgi;null

DEBUG: for osgi.identity;filter:='(osgi.identity=org.eclipse.equinox.metatype)' found [Provide[osgi.identity]{osgi.identity=org.eclipse.equinox.metatype, type=osgi.bundle, version=1.4.500.v20180827-1235}{}]

DEBUG: for osgi.wiring.package;filter:='(osgi.wiring.package=javax.xml.parsers)';osgi.wiring.package='javax.xml.parsers' found [Provide[osgi.wiring.package]{version=0.0.0, osgi.wiring.package=javax.xml.parsers}{}]

DEBUG: for osgi.wiring.package;filter:='(&(osgi.wiring.package=org.eclipse.osgi.util)(version>=1.1.0)(!(version>=2.0.0)))';osgi.wiring.package='org.eclipse.osgi.util' found [Provide[osgi.wiring.package]{bundle-symbolic-name=org.eclipse.osgi, bundle-version=3.16.200.v20210226-1447, version=1.1.0, osgi.wiring.package=org.eclipse.osgi.util, bnd.hashes=[-1590903379, 1546647487, 77397, -20915771]}{}]

DEBUG: for osgi.wiring.package;filter:='(&(osgi.wiring.package=org.osgi.framework)(version>=1.6.0)(!(version>=2.0.0)))';osgi.wiring.package='org.osgi.framework' found [Provide[osgi.wiring.package]{bundle-symbolic-name=org.eclipse.osgi, bundle-version=3.16.200.v20210226-1447, version=1.10.0, osgi.wiring.package=org.osgi.framework, bnd.hashes=[-1739641231, -1582817297, 322684510, 582841244, 2020069064, 2000952482, -1749687149, -1919773011, 1398930200, -472454707, -1764916362, -964568047, -719960689, 1415731401, 1067411795, -1546814169, 1890845477, 1335028569, 1581691183, 2104342424, -382080164, 181304498, -1542623884, 67115090, 917115616, -2029030736, 1588126669, -2050817629, -1416388428, 1571408324, -1812965632, 835705045, 1664677525, 958466835, 252453431, 500431109, 135145786, 162580661, 1579819625, -405185345, 691178052, -1227550718, 2023331894, 661742574, 1367323455, -857658657, 713485465, 2016261304, 49268581, -1923478059]}{}]

DEBUG: for osgi.wiring.package;filter:='(&(osgi.wiring.package=org.osgi.framework.wiring)(version>=1.0.0)(!(version>=2.0.0)))';osgi.wiring.package='org.osgi.framework.wiring' found [Provide[osgi.wiring.package]{bundle-symbolic-name=org.eclipse.osgi, bundle-version=3.16.200.v20210226-1447, version=1.2.0, osgi.wiring.package=org.osgi.framework.wiring, bnd.hashes=[-1230619814, -607154623, 923104925, -1448518282, -924180409, 920864580, 1544118144, -1923478059]}{uses=org.osgi.framework,org.osgi.resource}]

DEBUG: for osgi.wiring.package;filter:='(&(osgi.wiring.package=org.osgi.service.cm)(version>=1.2.1)(!(version>=2.0.0)))';osgi.wiring.package='org.osgi.service.cm' found [Provide[osgi.wiring.package]{bundle-symbolic-name=org.osgi.service.cm, bundle-version=1.6.0.201802012106, version=1.6.0, osgi.wiring.package=org.osgi.service.cm, bnd.hashes=[595867238, -1563253546, -1675361255, 160505113, -1671138460, 2064407577, -851798102, 368751429, 2132978627, 40470441, 1045830198, -14948876, 1655325979, -1419216863, -1923478059]}{uses=org.osgi.framework}, Provide[osgi.wiring.package]{bundle-symbolic-name=org.apache.felix.configadmin, bundle-version=1.9.22, version=1.6.0, osgi.wiring.package=org.osgi.service.cm, bnd.hashes=[595867238, -1563253546, -1675361255, 160505113, -1671138460, 2064407577, -851798102, 368751429, 2132978627, 40470441, 1045830198, -14948876, 1655325979, -1419216863, -1923478059]}{uses=org.osgi.framework}, Provide[osgi.wiring.package]{bundle-symbolic-name=tx-control-provider-jdbc-xa, bundle-version=1.0.0, version=1.5.0, osgi.wiring.package=org.osgi.service.cm, bnd.hashes=[-1563253546, -1675361255, -1671138460, 2064407577, -851798102, 368751429, 2132978627, 40470441, 1045830198, -14948876, -1419216863, -1923478059]}{uses=org.osgi.framework}, Provide[osgi.wiring.package]{bundle-symbolic-name=tx-control-provider-jpa-xa, bundle-version=1.0.0, version=1.5.0, osgi.wiring.package=org.osgi.service.cm, bnd.hashes=[-1563253546, -1675361255, -1671138460, 2064407577, -851798102, 368751429, 2132978627, 40470441, 1045830198, -14948876, -1419216863, -1923478059]}{uses=org.osgi.framework}]

DEBUG: for osgi.wiring.package;filter:='(&(osgi.wiring.package=org.osg^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
and org.apache.servicemix.specs.stax-api-1.0 [org.apache.servicemix.specs.stax-api-1.0 version=2.9.0] via two dependency chains.

Chain 1:
  org.apache.cxf.cxf-rt-frontend-jaxrs [org.apache.cxf.cxf-rt-frontend-jaxrs version=3.4.3]
    import: (osgi.wiring.package=javax.xml.stream)
     |
    export: osgi.wiring.package: javax.xml.stream
  org.apache.servicemix.specs.stax-api-1.2 [org.apache.servicemix.specs.stax-api-1.2 version=2.9.0]

Chain 2:
  org.apache.cxf.cxf-rt-frontend-jaxrs [org.apache.cxf.cxf-rt-frontend-jaxrs version=3.4.3]
    import: (&(osgi.wiring.package=javax.ws.rs)(version>=1.0.0)(!(version>=3.0.0)))
     |
    export: osgi.wiring.package=javax.ws.rs; uses:=javax.ws.rs.core
  org.apache.aries.javax.jax.rs-api [org.apache.aries.javax.jax.rs-api version=1.0.1]
    import: (&(osgi.wiring.package=javax.ws.rs.core)(version>=2.1.0)(!(version>=3.0.0)))
     |
    export: osgi.wiring.package=javax.ws.rs.core; uses:=javax.xml.bind.annotation
  org.apache.aries.javax.jax.rs-api [org.apache.aries.javax.jax.rs-api version=1.0.1]
    import: (osgi.wiring.package=javax.xml.bind.annotation)
     |
    export: osgi.wiring.package=javax.xml.bind.annotation; uses:=javax.xml.bind
  jaxb-api [jaxb-api version=2.3.0]
    import: (&(osgi.wiring.package=javax.xml.bind)(version>=2.3.0)(!(version>=3.0.0)))
     |
    export: osgi.wiring.package=javax.xml.bind; uses:=javax.xml.stream
  org.apache.servicemix.specs.jaxb-api-2.3 [org.apache.servicemix.specs.jaxb-api-2.3 version=2.3.0.1]
    import: (&(osgi.wiring.package=javax.xml.stream)(version>=1.0.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package: javax.xml.stream
  org.apache.servicemix.specs.stax-api-1.0 [org.apache.servicemix.specs.stax-api-1.0 version=2.9.0])

DEBUG: Candidate permutation failed due to a conflict between imports; will try another if possible. (Uses constraint violation. Unable to resolve resource org.openhab.core.io.monitor [org.openhab.core.io.monitor version=3.1.0.202106171953] because it is exposed to package 'javax.annotation' from resources javax.annotation-api [javax.annotation-api version=1.3.2] and org.jsr-305 [org.jsr-305 version=3.0.2] via two dependency chains.

Chain 1:
  org.openhab.core.io.monitor [org.openhab.core.io.monitor version=3.1.0.202106171953]
    import: (&(osgi.wiring.package=javax.annotation)(version>=1.2.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package: javax.annotation
  javax.annotation-api [javax.annotation-api version=1.3.2]

Chain 2:
  org.openhab.core.io.monitor [org.openhab.core.io.monitor version=3.1.0.202106171953]
    import: (osgi.wiring.package=javax.annotation.meta)
     |
    export: osgi.wiring.package: javax.annotation.meta; uses:=javax.annotation
    export: osgi.wiring.package=javax.annotation
  org.jsr-305 [org.jsr-305 version=3.0.2])

DEBUG: Candidate permutation failed due to a conflict between imports; will try another if possible. (Uses constraint violation. Unable to resolve resource org.openhab.core.io.monitor [org.openhab.core.io.monitor version=3.1.0.202106171953] because it is exposed to package 'javax.annotation' from resources org.apache.servicemix.specs.annotation-api-1.3 [org.apache.servicemix.specs.annotation-api-1.3 version=1.3.0.1] and org.jsr-305 [org.jsr-305 version=3.0.2] via two dependency chains.

Chain 1:
  org.openhab.core.io.monitor [org.openhab.core.io.monitor version=3.1.0.202106171953]
    import: (&(osgi.wiring.package=javax.annotation)(version>=1.2.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package: javax.annotation
  org.apache.servicemix.specs.annotation-api-1.3 [org.apache.servicemix.specs.annotation-api-1.3 version=1.3.0.1]

Chain 2:
  org.openhab.core.io.monitor [org.openhab.core.io.monitor version=3.1.0.202106171953]
    import: (osgi.wiring.package=javax.annotation.meta)
     |
    export: osgi.wiring.package: javax.annotation.meta; uses:=javax.annotation
    export: osgi.wiring.package=javax.annotation
  org.jsr-305 [org.jsr-305 version=3.0.2])
```

**Comment by fwolter** [comment]
When building addons, I receive the following error message, which might be more useful:
```
[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-irobot; type=karaf.feature; version=3.1.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-binding-irobot)(type=karaf.feature)(version>=3.1.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-irobot/3.1.0.SNAPSHOT: missing requirement [openhab-binding-irobot/3.1.0.SNAPSHOT] osgi.identity; osgi.identity=openhab-runtime-base; type=karaf.feature [caused by: Unable to resolve openhab-runtime-base/3.1.0.SNAPSHOT: missing requirement [openhab-runtime-base/3.1.0.SNAPSHOT] osgi.identity; osgi.identity=openhab-core-io-http-auth; type=karaf.feature [caused by: Unable to resolve openhab-core-io-http-auth/3.1.0.SNAPSHOT: missing requirement [openhab-core-io-http-auth/3.1.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.core.io.http.auth; type=osgi.bundle; version="[3.1.0.202106150303,3.1.0.202106150303]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.io.http.auth/3.1.0.202106150303: missing requirement [org.openhab.core.io.http.auth/3.1.0.202106150303] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core.io.http)(version>=3.1.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core.io.http/3.1.0.202106150301: missing requirement [org.openhab.core.io.http/3.1.0.202106150301] osgi.identity; osgi.identity="root#openhab-core-base-3.1.0.SNAPSHOT"; type=karaf.subsystem; version="[0,0.0.0]"; resolution:=mandatory [caused by: Unable to resolve root#openhab-core-base-3.1.0.SNAPSHOT: missing requirement [root#openhab-core-base-3.1.0.SNAPSHOT] osgi.identity; osgi.identity=openhab-core-base; type=karaf.feature; version="[3.1.0.SNAPSHOT,3.1.0.SNAPSHOT]" [caused by: Unable to resolve openhab-core-base/3.1.0.SNAPSHOT: missing requirement [openhab-core-base/3.1.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.core.io.monitor; type=osgi.bundle; version="[3.1.0.202106171953,3.1.0.202106171953]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.io.monitor/3.1.0.202106171953: missing requirement [org.openhab.core.io.monitor/3.1.0.202106171953] osgi.wiring.package; filter:="(osgi.wiring.package=com.sun.management)"]]]]]]]]
```

Seems like `com.sun.management` is missing`.

**Comment by fwolter** [comment]
Any progress on that?
