### ISSUE TITLE
OpenHAB 3.1 docker - ecmascripts are not working

### ISSUE THREAD

**Issue by pboettch** [openhab/openhab-core#2441]
I recently started using OpenHAB (coming from FHEM) and was happy to find a working docker-image for a RPI4.

I tried out JavaScript (ECMAScript) rules and I noticed it was crashing even for "hello-world"-tests:

```
2021-07-27 17:10:46.841 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error while creating ScriptEngine
org.graalvm.polyglot.PolyglotException: Error: Invalid CommonJS root folder: /openhab/conf/automation/lib/javascript/personal
	at org.graalvm.polyglot.Context.eval(Context.java:345) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.evalInternal(GraalJSScriptEngine.java:319) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSBindings.initGlobal(GraalJSBindings.java:94) ~[?:?]
[...]	
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) [bundleFile:9.4.40.v20210413]
	at java.lang.Thread.run(Thread.java:829) [?:?]

2021-07-27 17:10:46.872 [WARN ] [e.automation.internal.RuleEngineImpl] - Fail to execute action: script
java.lang.NullPointerException: null
	at com.oracle.truffle.js.scriptengine.GraalJSBindings.put(GraalJSBindings.java:128) ~[?:?]
	at javax.script.SimpleScriptContext.setAttribute(SimpleScriptContext.java:246) ~[java.scripting:?]
	at org.openhab.core.automation.module.script.internal.handler.AbstractScriptModuleHandler.setExecutionContext(AbstractScriptModuleHandler.java:117) ~[?:?]
	at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:60) ~[?:?]
[...]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) [bundleFile:9.4.40.v20210413]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

The solution I found was to enter the container and to create the missing folder manually and then to restart the container:

```Bash
docker exec -it openhab_openhab_1 /bin/bash
mkdir -p /openhab/conf/automation/lib/javascript/personal/
chown -R openhab.openhab /openhab/conf
```

I think this should be fixed within the Dockerfile. It seems that this directory is not created in a docker-volume so it disappears each time the container is re-created.

Hmm, while writing this, I realize that maybe this is the actual problem and the ecmascript addon should use another path.

**Comment by pboettch** [comment]
I just found the root-cause: I installed the javascript-language-addon. Which is not needed actually. 

https://community.openhab.org/t/migrated-to-3-1-from-2-blocky-not-working-dependency-missing/124751
