### ISSUE TITLE
Exceptions when features are installed before KAR installation completed

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#2571]
Major issue with snapshot 2441 (first startup), apparently a problem to install rrd4j.
What is strange is that I am using the kar file which normally contains everything and so nothing should require a download. This looks like a "corrupted" kar file.
```
org.apache.karaf.features.internal.util.MultiException: Error:
        Error downloading mvn:org.openhab.addons.bundles/org.openhab.persistence.rrd4j/3.1.0-SNAPSHOT
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Suppressed: java.io.IOException: Error downloading mvn:org.openhab.addons.bundles/org.openhab.persistence.rrd4j/3.1.0-SNAPSHOT
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
                ... 3 more
        Caused by: java.io.IOException: Error resolving artifact org.openhab.addons.bundles:org.openhab.persistence.rrd4j:jar:3.1.0-SNAPSHOT: [Could not find artifact org.openhab.addons.bundles:org.openhab.persistence.rrd4j:jar:3.1.0-SNAPSHOT]
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
                at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
                ... 6 more
                Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.openhab.addons.bundles:org.openhab.persistence.rrd4j:jar:3.1.0-SNAPSHOT
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:403)
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
                        at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
                        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
                        ... 11 more
        Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.openhab.addons.bundles:org.openhab.persistence.rrd4j:jar:3.1.0-SNAPSHOT
                at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
                at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
                at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
                at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
                ... 11 more
```
@kaikreuzer : certainly something critical for the final 3.1.

**Comment by lolodomo** [comment]
Results with my last installations. 
The first startup never works  even if I wait for many minutes. 
At the second startup, I still have the exception but this time, if I wait for few minutes, it finally succeeds installing all the bindings.

**Comment by lolodomo** [comment]
@J-N-K : I am relatively annoyed because trying with the snapshot 2764, the first startup works well ! So, either the problem is not systematic or it has been mysteriously resolved ?

**Comment by J-N-K** [comment]
I don't think this whole issue is my fault, so I don't understand why you tag me here.

**Comment by lolodomo** [comment]
> I don't think this whole issue is my fault, so I don't understand why you tag me here.

Of course not. I tagged you because you made the effort to provide a fix. I am now asking myself if the fix is still required or not. As you investigated it, I assume you have an opinion.

**Comment by J-N-K** [comment]
My assumption would be that it can re-appear at any time, so the fix should probably be merged.

**Comment by lolodomo** [comment]
Just to mention that with snaposhot 2783, the first startup was successful (with around 2 minutes between the first log entry and the next ones).
