### ISSUE TITLE
[marketplace] Failed reinstalling add-on from cache on restart

### ISSUE THREAD

**Issue by andan67** [openhab/openhab-core#2614]
I'm getting an `Failed reinstalling add-on from cache` error for binding addons installed from community marketplace when restarting OH. After restart, the bindings are not availble in the main UI, and the linked things are in `UNINITIALIZED` status.

Error log:
```
2021-12-14 20:42:14.799 [INFO ] [community.CommunityKarafAddonHandler] - Reinstalling missing marketplace KAR: marketplace:
2021-12-14 20:42:14.801 [WARN ] [community.CommunityKarafAddonHandler] - Failed reinstalling add-on from cache
org.openhab.core.addon.marketplace.MarketplaceHandlerException: The local cache folder doesn't contain a single file: /var/lib/openhab/marketplace/kar
	at org.openhab.core.addon.marketplace.karaf.internal.community.CommunityKarafAddonHandler.installFromCache(CommunityKarafAddonHandler.java:155) ~[?:?]
	at org.openhab.core.addon.marketplace.karaf.internal.community.CommunityKarafAddonHandler.lambda$7(CommunityKarafAddonHandler.java:177) ~[?:?]
```
The installed bindings are available in the file system under
```
/var/lib/openhab/marketplace/kar/129036/org.openhab.binding.skyq-3.2.0-alpha3.kar
/var/lib/openhab/marketplace/kar/128262/org.openhab.binding.sony-3.2.0.kar
```

and can be manually installed from there with `kar:install`.

It seems that the addonid is not considered when looking up the kar in the file cache.

```
runtimeInfo:
  version: 3.2.0.M5
  buildString: Milestone Build
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+100-CA
  osName: Linux
  osVersion: 5.10.17-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 51777456
  totalMemory: 259522560
```

**Comment by J-N-K** [comment]
That's my fault. I'll fix that immediately.
