### ISSUE TITLE
SNAPSHOP.kar not installing

### ISSUE THREAD

**Issue by arkansas-coder** [openhab/openhab-core#2616]
I'm running the latest snapshot, build 2626 and am running into the following:
```
16:05:16.881 [ERROR] [org.apache.felix.fileinstall         ] - Failed to install artifact: /openhab/addons/openhab-addons-3.2.0-SNAPSHOT.kar
java.lang.RuntimeException: Error extracting kar file file:/openhab/addons/openhab-addons-3.2.0-SNAPSHOT.kar into dir /openhab/userdata/tmp/kar/openhab-addons-3.2.0-SNAPSHOT: Unexpected end of ZLIB input stream
	at org.apache.karaf.kar.internal.Kar.extract(Kar.java:142) ~[?:?]
	at org.apache.karaf.kar.internal.KarServiceImpl.install(KarServiceImpl.java:108) ~[?:?]
	at org.apache.karaf.kar.internal.KarServiceImpl.install(KarServiceImpl.java:95) ~[?:?]
	at org.apache.karaf.kar.internal.KarServiceImpl.install(KarServiceImpl.java:87) ~[?:?]
	at org.apache.karaf.deployer.kar.KarArtifactInstaller.install(KarArtifactInstaller.java:50) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:950) [bundleFile:3.7.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:884) [bundleFile:3.7.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:489) [bundleFile:3.7.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.7.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.7.0]
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245) ~[?:?]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) ~[?:?]
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:197) ~[?:?]
	at java.util.jar.JarInputStream.read(JarInputStream.java:207) ~[?:?]
	at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[?:?]
	at org.apache.karaf.util.StreamUtils.copy(StreamUtils.java:56) ~[?:?]
	at org.apache.karaf.kar.internal.Kar.extract(Kar.java:165) ~[?:?]
	at org.apache.karaf.kar.internal.Kar.extract(Kar.java:123) ~[?:?]
	... 9 more
16:05:17.039 [WARN ] [.core.karaf.internal.FeatureInstaller] - The misc add-on 'ruleengine' does not exist - ignoring it.
16:05:17.052 [WARN ] [.core.karaf.internal.FeatureInstaller] - The ui add-on 'restdocs' does not exist - ignoring it.
16:05:17.057 [WARN ] [.core.karaf.internal.FeatureInstaller] - The ui add-on 'habmin' does not exist - ignoring it.
16:05:17.066 [WARN ] [.core.karaf.internal.FeatureInstaller] - The ui add-on 'paper' does not exist - ignoring it.
```
```addons.cfg``` is
```
package = minimal
remote = true
binding = astro,gpstracker,kodi,lifx,mqtt,network,ntp,zwave,zigbee
ui = basic,paper,habmin,habpanel,restdocs
misc=ruleengine
```

**Comment by splatch** [comment]
Seems your archive is corrupted. Can you check if it opens using regular archive manager?

**Comment by wborn** [comment]
Yes these are typically issues due to failed KAR file downloads.
Also make sure you have enough free disk space left so the complete file can be downloaded. :slightly_smiling_face:
