### ISSUE TITLE
OH3.2 shutdown after SocketException

### ISSUE THREAD

**Issue by Gifford47** [openhab/openhab-core#2666]
hi!

i have the problem that OH runs only a few hours until a "**SocketException**" error is raised in the log. **After that I can't access the UI or use OH in any other way....**`
i have upgraded to OH3.2 10 days ago

the following is the log with the first error appearing:
```
2022-01-05 05:35:29.588 [ERROR] [org.openhab.core.net.NetUtil        ] - Could not find interface IP addresses: Zu viele offene Dateien (Socket creation failed)
java.net.SocketException: Zu viele offene Dateien (Socket creation failed)
	at java.net.NetworkInterface.getAll(Native Method) ~[?:?]
	at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:359) ~[?:?]
	at org.openhab.core.net.NetUtil.getAllInterfaceAddresses(NetUtil.java:332) ~[?:?]
	at org.openhab.core.net.NetUtil.pollAndNotifyNetworkInterfaceAddress(NetUtil.java:525) ~[?:?]
	at org.openhab.core.net.NetUtil.lambda$2(NetUtil.java:521) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-01-05 05:35:30.613 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/NovelanLAD7_warmwatertemperature.rrd': /var/lib/openhab/persistence/rrd4j/NovelanLAD7_warmwatertemperature.rrd: Zu viele offene Dateien
2022-01-05 05:35:30.615 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/alarm_state.rrd': /var/lib/openhab/persistence/rrd4j/alarm_state.rrd: Zu viele offene Dateien
2022-01-05 05:35:30.618 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/NovelanLAD7_Aussentemperatur.rrd': /var/lib/openhab/persistence/rrd4j/NovelanLAD7_Aussentemperatur.rrd: Zu viele offene Dateien
2022-01-05 05:35:34.567 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'http://192.168.1.100:9990/JKSDZIUZBKJopiu8/monitor/xnwN5jCZS6/rpi_cam_floor' (method='GET', content='null') failed: Could not connect to /192.168.1.100:9990
2022-01-05 05:35:37.691 [WARN ] [concurrent.SingleThreadEventExecutor] - Unexpected exception from an event executor: 
java.lang.NoClassDefFoundError: io/netty/channel/AbstractChannel$AbstractUnsafe$8
	at io.netty.channel.AbstractChannel$AbstractUnsafe.deregister(AbstractChannel.java:822) ~[bundleFile:4.1.68.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.fireChannelInactiveAndDeregister(AbstractChannel.java:782) ~[bundleFile:4.1.68.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:765) ~[bundleFile:4.1.68.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620) ~[bundleFile:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:769) ~[bundleFile:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526) ~[bundleFile:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [bundleFile:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bundleFile:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [bundleFile:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: io.netty.channel.AbstractChannel$AbstractUnsafe$8 cannot be found by io.netty.transport_4.1.68.Final
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170) ~[org.eclipse.osgi-3.16.300.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 10 more
2022-01-05 05:35:37.761 [ERROR] [Events.Framework                    ] - FrameworkEvent ERROR
java.io.IOException: Exception in opening zip file: /var/lib/openhab/cache/org.eclipse.osgi/333/0/bundleFile
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:358) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.doOpen(ZipBundleFile.java:51) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.open(CloseableBundleFile.java:135) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.lockOpen(CloseableBundleFile.java:77) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.getEntry(CloseableBundleFile.java:274) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathEntry.findEntry(ClasspathEntry.java:195) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:623) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:609) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:589) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:568) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:401) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:480) ~[org.eclipse.osgi-3.16.300.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170) ~[org.eclipse.osgi-3.16.300.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.deregister(AbstractChannel.java:822) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.fireChannelInactiveAndDeregister(AbstractChannel.java:782) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:765) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:769) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.io.FileNotFoundException: /var/lib/openhab/cache/org.eclipse.osgi/333/0/bundleFile (Zu viele offene Dateien)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:345) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:214) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1305) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1271) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:248) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:177) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:191) ~[?:?]
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:337) ~[org.eclipse.osgi-3.16.300.jar:?]
	... 24 more
2022-01-05 05:35:39.750 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'NetworkAddressChangeListener.onChanged()' on 'org.openhab.io.homekit.internal.HomekitImpl@17e96ca0': failed to create a child event loop
java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60) ~[?:?]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:97) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:92) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:73) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:53) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:45) ~[?:?]
	at io.github.hapjava.server.impl.http.impl.NettyHomekitHttpService.<init>(NettyHomekitHttpService.java:36) ~[?:?]
	at io.github.hapjava.server.impl.http.impl.NettyHomekitHttpService.create(NettyHomekitHttpService.java:32) ~[?:?]
	at io.github.hapjava.server.impl.http.impl.HomekitHttpServer.start(HomekitHttpServer.java:31) ~[?:?]
	at io.github.hapjava.server.impl.HomekitRoot.start(HomekitRoot.java:119) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitImpl.startBridge(HomekitImpl.java:202) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitImpl.startHomekitServer(HomekitImpl.java:236) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitImpl.onChanged(HomekitImpl.java:298) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:183) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:38) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[?:?]
	... 24 more
Caused by: java.io.IOException: Zu viele offene Dateien
	at sun.nio.ch.IOUtil.makePipe(Native Method) ~[?:?]
	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:83) ~[?:?]
	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:183) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:38) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[?:?]
	... 24 more
2022-01-05 05:36:00.612 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/NovelanLAD7_warmwatertemperature.rrd': /var/lib/openhab/persistence/rrd4j/NovelanLAD7_warmwatertemperature.rrd: Zu viele offene Dateien
2022-01-05 05:36:00.616 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/alarm_state.rrd': /var/lib/openhab/persistence/rrd4j/alarm_state.rrd: Zu viele offene Dateien
2022-01-05 05:36:00.618 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/NovelanLAD7_Aussentemperatur.rrd': /var/lib/openhab/persistence/rrd4j/NovelanLAD7_Aussentemperatur.rrd: Zu viele offene Dateien
2022-01-05 05:36:04.568 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'http://192.168.1.100:9990/JKSDZIUZBKJopiu8/monitor/xnwN5jCZS6/rpi_cam_floor' (method='GET', content='null') failed: Could not connect to /192.168.1.100:9990
2022-01-05 05:36:30.612 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/NovelanLAD7_warmwatertemperature.rrd': /var/lib/openhab/persistence/rrd4j/NovelanLAD7_warmwatertemperature.rrd: Zu viele offene Dateien
2022-01-05 05:36:30.614 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/alarm_state.rrd': /var/lib/openhab/persistence/rrd4j/alarm_state.rrd: Zu viele offene Dateien
2022-01-05 05:36:30.615 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/NovelanLAD7_Aussentemperatur.rrd': /var/lib/openhab/persistence/rrd4j/NovelanLAD7_Aussentemperatur.rrd: Zu viele offene Dateien
2022-01-05 05:36:34.568 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'http://192.168.1.100:9990/JKSDZIUZBKJopiu8/monitor/xnwN5jCZS6/rpi_cam_floor' (method='GET', content='null') failed: Could not connect to /192.168.1.100:9990
2022-01-05 05:36:39.762 [ERROR] [org.openhab.core.net.NetUtil        ] - Could not find interface IP addresses: Zu viele offene Dateien (Socket creation failed)
java.net.SocketException: Zu viele offene Dateien (Socket creation failed)
	at java.net.NetworkInterface.getAll(Native Method) ~[?:?]
	at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:359) ~[?:?]
	at org.openhab.core.net.NetUtil.getAllInterfaceAddresses(NetUtil.java:332) ~[?:?]
	at org.openhab.core.net.NetUtil.pollAndNotifyNetworkInterfaceAddress(NetUtil.java:525) ~[?:?]
	at org.openhab.core.net.NetUtil.lambda$2(NetUtil.java:521) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-01-05 05:37:00.611 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/NovelanLAD7_warmwatertemperature.rrd': /var/lib/openhab/persistence/rrd4j/NovelanLAD7_warmwatertemperature.rrd: Zu viele offene Dateien
2022-01-05 05:37:00.613 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/alarm_state.rrd': /var/lib/openhab/persistence/rrd4j/alarm_state.rrd: Zu viele offene Dateien

``

**Comment by wborn** [comment]
Looks like your OS is running out of disk space or exceeding the max open files limit.
Maybe you can find the perpetrator using the `lsof` command or disabling add-ons or rules?

**Comment by Gifford47** [comment]
> Looks like your OS is running out of disk space, exceeding the max open files limit or mounted the file system as read only due to disk errors.
> 
> Maybe you can find the perpetrator using the `lsof` command or disabling add-ons or rules?

i have now analyzed the memory, deleted or deactivated unnecessary rules and bindings. unfortunately, the error is still there.
It can not be the memory or disk space, there are several gigabytes still free.

the only thing that was noticeable was that openhab has a lot of the following entries in lsof:
`java 1384383 1386811 upnp-remo openhab 750u REG 0,24 0 642648 /run/lock/tmpcM5QlM (deleted)
`

**Comment by wborn** [comment]
> the only thing that was noticeable was that openhab has a lot of the following entries in lsof:
> java 1384383 1386811 upnp-remo openhab 750u REG 0,24 0 642648 /run/lock/tmpcM5QlM (deleted)

There is a known bug in the serial communications library used by openHAB which can cause many of these open lock files, see https://github.com/openhab/openhab-core/issues/1842 and https://github.com/NeuronRobotics/nrjavaserial/issues/111.

**Comment by Gifford47** [comment]
ok, i have come one step further: 
I think there is a basic problem with the provisioning of items in txt files.
the error is gone for about 2 days now.

What I did:
i had a rule that after a restart of openhab moves all item files in /etc/openhab/items to another folder and then moves them back to the original items folder. with this i achieve that also the txt items are shown again in the symantic model correctly under their groups (see #2117 or #2106). 
i deactivated this rule. however, the error was still present. after restarting the host, the errors were gone.

but now all txt items are displayed wrong in the symantic model again.

can someone please check how we can fix this issue #2117 or #2106?

**Comment by Gifford47** [comment]
i rejoiced too soon, i just received the error again ... what can i do now?

**Comment by Gifford47** [comment]
i have multiple mqtt jsonpath-transformation failures form my shutter because i have subscribed another topic in my thing configuration. could that cause the issue?
``` 
2022-01-07 10:07:36.296 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JSONPATH-transformation failed: Invalid path '$.Shutter1.Position' in '{"Event":"Done"}'
2022-01-07 10:07:36.306 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JSONPATH-transformation failed: Invalid path '$.Shutter1.Position' in '{"Event":"Done"}'
2022-01-07 10:07:36.307 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JSONPATH-transformation failed: Invalid path '$.Shutter1.Position' in '{"Event":"Done"}'
2022-01-07 10:07:36.311 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JSONPATH-transformation failed: Invalid path '$.Shutter1.Position' in '{"Event":"Done"}'

```

**Comment by wborn** [comment]
> what can i do now?

How about disabling some add-ons or rules to find the perpetrator?

**Comment by Gifford47** [comment]
ok, i have disabled every rules and things but the error was still there.
after that i had purged openhab und reinstalled with all standard configs and now the error is gone.
i dont know what the cause was but thanks to all that tried to help me!

**Comment by Gifford47** [comment]
ok, now i have found the failure (thx @wborn) :
two days after reinstalling OH3.2 i installed the smartmeter binding. after a half day i got also the java lock failure again. the log shows the smartmeter binding as failure (when it tries to reconnect the usb device).

is there already a fixed nrjavaserial jar file existing, that i can import to openhab?

**Comment by wborn** [comment]
> is there already a fixed nrjavaserial jar file existing, that i can import to openhab?

There is no official release containing the latest fixes but I made a JAR based on the latest code which you can use by using the following command on the [Console](https://www.openhab.org/docs/administration/console.html):

`bundle:update nrjavaserial https://github.com/wborn/nrjavaserial/releases/download/5.2.1-20220113/nrjavaserial-5.2.1.202201130000.jar`

After that you probably need to restart openHAB.

**Comment by Gifford47** [comment]
> > is there already a fixed nrjavaserial jar file existing, that i can import to openhab?
> 
> There is no official release containing the latest fixes but I made a JAR based on the latest code which you can use by using the following command on the [Console](https://www.openhab.org/docs/administration/console.html):
> 
> `bundle:update nrjavaserial https://github.com/wborn/nrjavaserial/releases/download/5.2.1-20220113/nrjavaserial-5.2.1.202201130000.jar`
> 
> After that you probably need to restart openHAB.

Thanks for your patched binary! Not it works!

**Comment by wborn** [comment]
Let's close this as it duplicates #1842.
