### ISSUE TITLE
Missing channels since last update

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-core#2831]
I'm on milestone 3.3.0 Build 2797, updated this morning.
Many channels have disappeared from things.
Here's an example for Telegram Bot : 
![image](https://user-images.githubusercontent.com/3328789/157896594-11b1c3b9-18f1-4ecc-8c12-cacf84bf0ffb.png)

Many bindings seems impacted (openuv, telegram, logreader, astro...) and the log is full of this error : 
```
2022-03-11 14:28:04.392 [WARN ] [ig.xml.osgi.XmlDocumentBundleTracker] - The XML document '/OH-INF/thing/channels.xml' in module 'org.openhab.binding.astro' could not be parsed: ChannelType 'itemType' must not be null or empty.
---- Debugging information ----
message             : ChannelType 'itemType' must not be null or empty.
class               : org.openhab.core.thing.xml.internal.ChannelTypeXmlResult
required-type       : org.openhab.core.thing.xml.internal.ChannelTypeXmlResult
converter-type      : org.openhab.core.thing.xml.internal.ChannelTypeConverter
path                : /thing-descriptions/channel-type[10]
line number         : 126
class[1]            : java.util.ArrayList
required-type[1]    : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[2]            : org.openhab.core.thing.xml.internal.ThingDescriptionList
required-type[2]    : org.openhab.core.thing.xml.internal.ThingDescriptionList
converter-type[2]   : org.openhab.core.thing.xml.internal.ThingDescriptionConverter
version             : 1.4.19
-------------------------------
com.thoughtworks.xstream.converters.ConversionException: ChannelType 'itemType' must not be null or empty.
---- Debugging information ----
message             : ChannelType 'itemType' must not be null or empty.
class               : org.openhab.core.thing.xml.internal.ChannelTypeXmlResult
required-type       : org.openhab.core.thing.xml.internal.ChannelTypeXmlResult
converter-type      : org.openhab.core.thing.xml.internal.ChannelTypeConverter
path                : /thing-descriptions/channel-type[10]
line number         : 126
class[1]            : java.util.ArrayList
required-type[1]    : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[2]            : org.openhab.core.thing.xml.internal.ThingDescriptionList
required-type[2]    : org.openhab.core.thing.xml.internal.ThingDescriptionList
converter-type[2]   : org.openhab.core.thing.xml.internal.ThingDescriptionConverter
version             : 1.4.19
-------------------------------
	at org.openhab.core.config.xml.util.GenericUnmarshaller.requireNonEmpty(GenericUnmarshaller.java:95) ~[?:?]
	at org.openhab.core.thing.xml.internal.ChannelTypeConverter.readItemType(ChannelTypeConverter.java:77) ~[?:?]
	at org.openhab.core.thing.xml.internal.ChannelTypeConverter.unmarshalType(ChannelTypeConverter.java:175) ~[?:?]
	at org.openhab.core.thing.xml.internal.ChannelTypeConverter.unmarshalType(ChannelTypeConverter.java:1) ~[?:?]
	at org.openhab.core.thing.xml.internal.AbstractDescriptionTypeConverter.unmarshal(AbstractDescriptionTypeConverter.java:193) ~[?:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:117) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:99) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:92) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:86) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:81) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52) ~[bundleFile:1.4.19]
	at org.openhab.core.thing.xml.internal.ThingDescriptionConverter.unmarshal(ThingDescriptionConverter.java:56) ~[?:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:136) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1421) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1399) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1350) ~[bundleFile:1.4.19]
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1304) ~[bundleFile:1.4.19]
	at org.openhab.core.config.xml.util.XmlDocumentReader.readFromXML(XmlDocumentReader.java:105) ~[bundleFile:?]
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker.parseDocuments(XmlDocumentBundleTracker.java:396) [bundleFile:?]
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker.processBundle(XmlDocumentBundleTracker.java:382) [bundleFile:?]
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker$2.run(XmlDocumentBundleTracker.java:347) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

I suspect a change in core.
Same behaviour observed in my dev environment on eclipse.

**Comment by clinique** [comment]
Progressing in my search. This seems related to channel-types of kind trigger that has no item-type, witch seems normal.

**Comment by clinique** [comment]
I wonder how this could be linked to [Add a profile for linking trigger channels to String items](https://github.com/openhab/openhab-core/pull/2769). 
Adding 
` <item-type>String</item-type>`
to trigger channel-types I stopped having errors in log at start.

**Comment by J-N-K** [comment]
This error message was introduced in https://github.com/openhab/openhab-core/pull/2775.

**Comment by clinique** [comment]
Yes, but it is not only an error message, it prevents things from loading their channels.

**Comment by J-N-K** [comment]
Yes, but the newly introduced `requireNonEmpty` throws an exception if the element is empty. This prevents the channel from loading.

**Comment by wborn** [comment]
Yes it is probably caused by my PR. I'll have a look after some coffee. 😉
