### ISSUE TITLE
ThingManagerOSGiTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#3020]
This test often fails on Windows builds:

```
TEST org.openhab.core.thing.internal.ThingManagerOSGiTest#thingManagerConsidersUNKNOWNasReadyToUseAndForwardsCommand() <<< ERROR: 
Expected: is <true>
     but: was <false>
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.thing.internal.ThingManagerOSGiTest.lambda$102(ThingManagerOSGiTest.java:2084)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:245)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:213)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:166)
	at org.openhab.core.thing.internal.ThingManagerOSGiTest.thingManagerConsidersUNKNOWNasReadyToUseAndForwardsCommand(ThingManagerOSGiTest.java:2083)
```

**Comment by wborn** [comment]
Still unstable, see: https://github.com/wborn/openhab-core/actions/runs/4217807817/jobs/7328632270

```
TEST org.openhab.core.thing.internal.ThingManagerOSGiTest#thingManagerConsidersUNKNOWNasReadyToUseAndForwardsCommand() <<< ERROR: 
Expected: is <true>
     but: was <false>
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.thing.internal.ThingManagerOSGiTest.lambda$100(ThingManagerOSGiTest.java:2053)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:245)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:213)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:166)
	at org.openhab.core.thing.internal.ThingManagerOSGiTest.thingManagerConsidersUNKNOWNasReadyToUseAndForwardsCommand(ThingManagerOSGiTest.java:2052)
```

**Comment by wborn** [comment]
I've spotted another one: https://ci.openhab.org/job/PR-openHAB-Core/5509/

```
TEST org.openhab.core.thing.internal.ThingManagerOSGiTest#thingManagerCallsChildHandlerInitializedAndChildHandlerDisposedOnBridgeHandlerCorrectlyEvenIfChildRegistrationTakesTooLong() <<< ERROR: 
Expected: is <org.openhab.core.thing.internal.ThingImpl@c7a74f8e>
     but: was null
java.lang.AssertionError: 
Expected: is <org.openhab.core.thing.internal.ThingImpl@c7a74f8e>
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.thing.internal.ThingManagerOSGiTest.thingManagerCallsChildHandlerInitializedAndChildHandlerDisposedOnBridgeHandlerCorrectlyEvenIfChildRegistrationTakesTooLong(ThingManagerOSGiTest.java:1981)
```
