### ISSUE TITLE
OAUTH2 Datetime parse error from google

### ISSUE THREAD

**Issue by resetpointer** [openhab/openhab-core#3198]
Hi, I am using OH-3.3.0.1 and observing that there is an issue with OH reading the access-token response from google.  Here is the trace log (keys are masked out):

```

11:02:16.418 [ERROR] [client.internal.OAuthStoreHandlerImpl] - Unable to deserialize json, discarding AccessTokenResponse.  Please check json against standard or with oauth provider. json:
{
  "accessToken": "<my access token>",
  "tokenType": "Bearer",
  "expiresIn": 3599,
  "refreshToken": "<my refresh token>",
  "scope": "https://www.googleapis.com/auth/sdm.service",
  "createdOn": "2022-12-04T05:10:37.332318Z"
}
java.time.format.DateTimeParseException: Text '2022-12-04T05:10:37.332318Z' could not be parsed, unparsed text found at index 26
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2049) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[?:?]
	at java.time.LocalDateTime.parse(LocalDateTime.java:492) ~[?:?]
	at java.time.LocalDateTime.parse(LocalDateTime.java:477) ~[?:?]
	at org.openhab.core.auth.oauth2client.internal.OAuthStoreHandlerImpl$StorageFacade.lambda$0(OAuthStoreHandlerImpl.java:243) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:63) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[?:?]
	at org.openhab.core.auth.oauth2client.internal.OAuthStoreHandlerImpl$StorageFacade.get(OAuthStoreHandlerImpl.java:283) ~[?:?]
	at org.openhab.core.auth.oauth2client.internal.OAuthStoreHandlerImpl.loadAccessTokenResponse(OAuthStoreHandlerImpl.java:119) ~[?:?]
	at org.openhab.core.auth.oauth2client.internal.OAuthClientServiceImpl.getAccessTokenResponse(OAuthClientServiceImpl.java:326) ~[?:?]
	at org.openhab.binding.nest.internal.sdm.api.SDMAPI.getAuthorizationHeader(SDMAPI.java:135) ~[?:?]
	at org.openhab.binding.nest.internal.sdm.api.SDMAPI.checkAccessTokenValidity(SDMAPI.java:114) ~[?:?]
	at org.openhab.binding.nest.internal.sdm.handler.SDMAccountHandler.initializeSDMAPI(SDMAccountHandler.java:203) ~[?:?]
	at org.openhab.binding.nest.internal.sdm.handler.SDMAccountHandler.lambda$0(SDMAccountHandler.java:181) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

As the result: nest binding is showing this error:

```
Status:
OFFLINE
CONFIGURATION_ERROR
No SDM access token. Client may not have been authorized. 
```
As you can see, the access token was provided but the method _"client.internal.OAuthStoreHandlerImpl"_ failed to decode it.
Would someone look at this please?  thank you

**Comment by J-N-K** [comment]
This should not happen in OH3.4 since we switched from `LocalDateTime` to `Instant`. Can you check with a recent milestone/snapshot if you still run into this error?

**Comment by resetpointer** [comment]
> This should not happen in OH3.4 since we switched from `LocalDateTime` to `Instant`. Can you check with a recent milestone/snapshot if you still run into this error?


Earlier today, I upgraded to version 3.4M7 and also 3.5M7 but ran into a problem for which OH failed to load a lot of add-ons because cometvisu couldn't be included or found (something like that).  Not sure how to fix that error, but if u want, I can test earlier version like OH 3.4M0 or M4.

Are there plans to fix this in the stable release, version 3.3?

**Comment by J-N-K** [comment]
I wonder which versions you used. There is neither a 3.4M7 nor a 3.5M5. 

I don’t think the fix will be backported to 3.3, we are only three weeks away from 3.4 release, so in any case: if there is a serious issue that should be fixed. Please provide more details on your issue with 3.4.

**Comment by resetpointer** [comment]
M minor versions are listed under "tags" of the OH-core git tree.  They are also the corresponding release tags on  Ubuntu "testing" branch.  Here is the listing of the releases on Ubuntu-20.04 LTS in case if you are curious:

```
root@iot:/etc/openhab# apt policy openhab
openhab:
  Installed: 3.3.0-1
  Candidate: 3.4.0~M5-1
  Version table:
     3.4.0~M5-1 500
        500 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing/main amd64 Packages
     3.4.0~M4-1 500
        500 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing/main amd64 Packages
     3.4.0~M3-1 500
        500 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing/main amd64 Packages
     3.4.0~M2-1 500
        500 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing/main amd64 Packages
     3.4.0~M1-1 500
        500 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing/main amd64 Packages
 *** 3.3.0-1 500
        500 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing/main amd64 Packages
        100 /var/lib/dpkg/status
     3.3.0~RC1-1 500
        500 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing/main amd64 Packages
     3.3.0~M7-1 500
        500 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing/main amd64 Packages
     3.3.0~M6-1 500

```

As shown, the only versions newer than 3.3.0 are  3.4.0~M1 to  3.4.0~M5.  It was my mistake in my earlier post, I did not test version 3.4M7; it was version 3.4M5 that I tested.  


Anyway, I am able to pull the trace log of the previous upgrade (to M5), let me know if you know what the problem was so that I can test on the version 3.4.  Thanks

```
2022-12-03 23:28:18.766 [WARN ] [core.karaf.internal.FeatureInstaller] - The ui add-on 'classic' does not exist - ignoring it.
2022-12-03 23:28:18.766 [WARN ] [core.karaf.internal.FeatureInstaller] - The ui add-on 'habmin' does not exist - ignoring it.
2022-12-03 23:28:18.767 [WARN ] [core.karaf.internal.FeatureInstaller] - The ui add-on 'paper' does not exist - ignoring it.
2022-12-03 23:28:19.993 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-hue, openhab-binding-exec, openhab-binding-bluetooth, openhab-voice-mactts, openhab-voice-marytts, openhab-binding-ftpupload, openhab-binding-nest, openhab-misc-openhabcloud, openhab-voice-picotts, openhab-binding-network, openhab-ui-cometvisu, openhab-ui-habpanel, openhab-binding-chromecast, openhab-binding-mqtt, openhab-transformation-map, openhab-binding-ipcamera, openhab-binding-telegram, openhab-transformation-exec, openhab-voice-voicerss, openhab-voice-googletts, openhab-binding-tplinksmarthome, openhab-transformation-javascript, openhab-transformation-regex, openhab-transformation-jsonpath, openhab-binding-wifiled, openhab-persistence-jdbc-sqlite, openhab-ui-basic, openhab-binding-http, openhab-binding-astro, openhab-binding-unifi': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-ui-cometvisu; type=karaf.feature; version="[3.4.0.M5,3.4.0.M5]"; filter:="(&(osgi.identity=openhab-ui-cometvisu)(type=karaf.feature)(version>=3.4.0.M5)(version<=3.4.0.M5))" [caused by: Unable to resolve openhab-ui-cometvisu/3.4.0.M5: missing requirement [openhab-ui-cometvisu/3.4.0.M5] osgi.identity; osgi.identity=org.openhab.ui.cometvisu; type=osgi.bundle; version="[3.4.0.M5,3.4.0.M5]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.ui.cometvisu/3.4.0.M5: missing requirement [org.openhab.ui.cometvisu/3.4.0.M5] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.annotation)(version>=2.14.0)(!(version>=3.0.0)))"]]

```

**Comment by J-N-K** [comment]
Did you disable remote access (Settings/Add-on Management/Remote Access)? If not, please use the console to show `feature:repo-list`.

**Comment by resetpointer** [comment]
I do not think so, here is the settings that's on the current functional version, 3.3.0.

```
openhab> feature:repo-list                                                                                                                                                                                         
Repository               │ URL
─────────────────────────┼───────────────────────────────────────────────────────────
standard-4.3.7           │ mvn:org.apache.karaf.features/standard/4.3.7/xml/features
org.ops4j.pax.web-7.3.25 │ mvn:org.ops4j.pax.web/pax-web-features/7.3.25/xml/features
distro-3.3.0             │ mvn:org.openhab.distro/distro/3.3.0/xml/features
openhab-addons-3.3.0     │ mvn:org.openhab.distro/openhab-addons/3.3.0/xml/features
framework-4.3.7          │ mvn:org.apache.karaf.features/framework/4.3.7/xml/features

```

**Comment by J-N-K** [comment]
The interesting question is if 

```
openhab-addons-3.4.0-M5  │ mvn:org.openhab.distro/openhab-addons/3.4.0-M5/xml/features
```

is missing or not.

**Comment by resetpointer** [comment]
good question, I checked the trace log and I did upgraded addons to version 3.4.0-M5.


```
cat /var/log/apt/history
...
Start-Date: 2022-12-03  23:10:25
Commandline: apt install openhab
Upgrade: openhab:amd64 (3.3.0-1, 3.4.0~M5-1)
End-Date: 2022-12-03  23:13:12

Start-Date: 2022-12-03  23:17:23
Commandline: apt install openhab-addons
Install: openhab-addons:amd64 (3.4.0~M5-1)
End-Date: 2022-12-03  23:17:36
...
```

**Comment by J-N-K** [comment]
If - at all - there should be a command for that, it should be a console command on the Karaf console. I'm closing here because I think this issue is solved in latest code and we won't release a new 3.3.
