### ISSUE TITLE
TimerImplTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#3217]
This test failed in a GHA Windows build: https://github.com/wborn/openhab-core/actions/runs/3669407664/jobs/6203216538

```
Expected: is <false>
     but: was <true>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.automation.module.script.TimerImplTest.testTimerHasTerminatedAndReschedule(TimerImplTest.java:94)
```

**Comment by J-N-K** [comment]
I think this one and #2862 have the same root cause: the system running the tests is too slow for the tests to complete within the limits. I'm not sure that increasing the limit again and again to accommodate for slower builds is the correct way to solve these issues.

**Comment by wborn** [comment]
What may work better is to rewrite the test to use a `Scheduler` mock instead of a `SchedulerImpl`.
It's the `TimerImpl` that should be tested, not the `SchedulerImpl`.
