### ISSUE TITLE
ThreadPoolManagerTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#3254]
This test failed in a GHA Windows build: https://github.com/wborn/openhab-core/actions/runs/3758246710/jobs/6386349876

```
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.194 s <<< FAILURE! - in org.openhab.core.common.ThreadPoolManagerTest
[ERROR] org.openhab.core.common.ThreadPoolManagerTest.testGetPoolShutdown  Time elapsed: 1.57 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Checking if thread pool Test works ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210)
	at org.openhab.core.common.ThreadPoolManagerTest.checkThreadPoolWorks(ThreadPoolManagerTest.java:128)
	at org.openhab.core.common.ThreadPoolManagerTest.testGetPoolShutdown(ThreadPoolManagerTest.java:108)
```

**Comment by wborn** [comment]
Still unstable, see: https://github.com/wborn/openhab-core/actions/runs/4217807817/jobs/7321851087
