### ISSUE TITLE
Basic UI locked up: java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by jscottnz** [openhab/openhab-core#332]
Hello, I went though a period of having a very unstable openhab installation. I fixed some issues with locks etc and its been very stable for 20 days.

The issues that caused me problems in the past was the UI would lock up. This made me think that it was a thread issue with Jetty.

I added a cron (actual cron) on my mac to call the api every minute and the call would be logged to influxdb. This has worked for 20 days.

Early this morning that api call started to fail. looking in the log I can see that its unable to create a thread. So something has been chewing it up.

I'm well aware that it could be my own rules, but I'm posting the log and hopefully someone will spot something. 

I'm happy enough to try fix the issue, just some pro pointers would be excellent.

Thanks

osX 10.116
Jeremys-MacBook:Downloads jeremyscott$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

openhab 2.2.0

```
# A comma-separated list of bindings to install (e.g. "sonos,knx,zwave")
binding = chromecast, hue, icloud, network, weather1, expire1
# A comma-separated list of UIs to install (e.g. "basic,paper")
ui = basic, habmin, habpanel, paper
# A comma-separated list of persistence services to install (e.g. "rrd4j,jpa")
persistence = influxdb
# A comma-separated list of actions to install (e.g. "mail,pushover")
#action = 
# A comma-separated list of transformation services to install (e.g. "map,jsonpath")
transformation = jsonpath
# A comma-separated list of voice services to install (e.g. "marytts,freetts")
voice = mactts
# A comma-separated list of miscellaneous services to install (e.g. "myopenhab")
misc = openhabcloud, market

```

[outofthreads.log](https://github.com/openhab/openhab-core/files/1904809/outofthreads.log)

and this in the openhab console
```
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at su.litvak.chromecast.api.v2.Channel$ResultProcessor.get(Channel.java:239)
	at su.litvak.chromecast.api.v2.Channel.send(Channel.java:367)
	at su.litvak.chromecast.api.v2.Channel.sendStandard(Channel.java:336)
	at su.litvak.chromecast.api.v2.Channel.getStatus(Channel.java:451)
	at su.litvak.chromecast.api.v2.ChromeCast.getStatus(ChromeCast.java:179)
	at org.openhab.binding.chromecast.internal.ChromecastCommander.handleRefresh(ChromecastCommander.java:87)
	at org.openhab.binding.chromecast.handler.ChromecastHandler$Coordinator$1.run(ChromecastHandler.java:231)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at su.litvak.chromecast.api.v2.Channel$ResultProcessor.get(Channel.java:239)
	at su.litvak.chromecast.api.v2.Channel.send(Channel.java:367)
	at su.litvak.chromecast.api.v2.Channel.sendStandard(Channel.java:336)
	at su.litvak.chromecast.api.v2.Channel.getStatus(Channel.java:451)
	at su.litvak.chromecast.api.v2.ChromeCast.getStatus(ChromeCast.java:179)
	at org.openhab.binding.chromecast.internal.ChromecastCommander.handleRefresh(ChromecastCommander.java:87)
	at org.openhab.binding.chromecast.handler.ChromecastHandler$Coordinator$1.run(ChromecastHandler.java:231)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at su.litvak.chromecast.api.v2.Channel$ResultProcessor.get(Channel.java:239)
	at su.litvak.chromecast.api.v2.Channel.send(Channel.java:367)
	at su.litvak.chromecast.api.v2.Channel.sendStandard(Channel.java:336)
	at su.litvak.chromecast.api.v2.Channel.getStatus(Channel.java:451)
	at su.litvak.chromecast.api.v2.ChromeCast.getStatus(ChromeCast.java:179)
	at org.openhab.binding.chromecast.internal.ChromecastCommander.handleRefresh(ChromecastCommander.java:87)
	at org.openhab.binding.chromecast.handler.ChromecastHandler$Coordinator$1.run(ChromecastHandler.java:231)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at su.litvak.chromecast.api.v2.Channel$ResultProcessor.get(Channel.java:239)
	at su.litvak.chromecast.api.v2.Channel.send(Channel.java:367)
	at su.litvak.chromecast.api.v2.Channel.sendStandard(Channel.java:336)
	at su.litvak.chromecast.api.v2.Channel.getStatus(Channel.java:451)
	at su.litvak.chromecast.api.v2.ChromeCast.getStatus(ChromeCast.java:179)
	at org.openhab.binding.chromecast.internal.ChromecastCommander.handleRefresh(ChromecastCommander.java:87)
	at org.openhab.binding.chromecast.handler.ChromecastHandler$Coordinator$1.run(ChromecastHandler.java:231)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-207755" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at org.apache.commons.exec.PumpStreamHandler.start(PumpStreamHandler.java:153)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:330)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:46)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:188)
Exception in thread "ESH-discovery-35665" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinvw** [comment]
If you run out of threads the most useful thing would of course be a thread dump or a full jvm dump. Searching with your os and jvm type/ version should give you some pointers how to do that.

**Comment by jscottnz** [comment]
thanks @martinvw . I actually did that yesterday and was about to report that the first suspect is this:

https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/463

I'm going to close this and look at that.

Thanks for your help
