### ISSUE TITLE
ItemChannelLinkOSGiTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#3380]
This test failed in a GHA build: https://github.com/openhab/openhab-core/actions/runs/4201120561/jobs/7287810287

```
TEST org.openhab.core.thing.link.ItemChannelLinkOSGiTest#assertThatAllLinksForItemCanBeDeleted() <<< ERROR: 
Expected: a collection with size <27>
     but: collection size was <21>
java.lang.AssertionError: 
Expected: a collection with size <27>
     but: collection size was <21>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.core.thing.link.ItemChannelLinkOSGiTest.lambda$12(ItemChannelLinkOSGiTest.java:230)
```

**Comment by J-N-K** [comment]
How can this test fail? It just checks if all links have been added to the registry...

**Comment by wborn** [comment]
Perhaps the test depends on some logic being executed in another thread which sometimes has not yet finished running.
