### ISSUE TITLE
ExpireManagerTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#3485]
This test failed in a macOS GHA build: https://github.com/wborn/openhab-core/actions/runs/4523616789/jobs/7966877526

```
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 46.204 s <<< FAILURE! - in org.openhab.core.internal.items.ExpireManagerTest
[ERROR] org.openhab.core.internal.items.ExpireManagerTest.testIgnoreStateUpdateExtendsExpiryOnCommand  Time elapsed: 4.429 s  <<< FAILURE!
org.mockito.exceptions.verification.NeverWantedButInvoked: 

eventPublisherMock.post(<any>);
Never wanted here:
-> at org.openhab.core.internal.items.ExpireManagerTest.testIgnoreStateUpdateExtendsExpiryOnCommand(ExpireManagerTest.java:164)
But invoked here:
-> at org.openhab.core.internal.items.ExpireManager.postUpdate(ExpireManager.java:196) with arguments: [Item 'Test' updated to UNDEF]

	at org.openhab.core.internal.items.ExpireManagerTest.testIgnoreStateUpdateExtendsExpiryOnCommand(ExpireManagerTest.java:164)
```

**Comment by wborn** [comment]
This still an issue, see: https://ci.openhab.org/job/PR-openHAB-Core/6180

**Comment by wborn** [comment]
Today as well: https://ci.openhab.org/job/PR-openHAB-Core/6192/

```
Wanted but not invoked:
eventPublisherMock.post(<any>);
-> at org.openhab.core.internal.items.ExpireManagerTest.testIgnoreCommandDoesNotExtendExpiryOnStateUpdate(ExpireManagerTest.java:237)
Actually, there were zero interactions with this mock.

	at org.openhab.core.internal.items.ExpireManagerTest.testIgnoreCommandDoesNotExtendExpiryOnStateUpdate(ExpireManagerTest.java:237)
```
