### ISSUE TITLE
openHAB does no longer start after update to 2.2

### ISSUE THREAD

**Issue by Larx** [openhab/openhab-core#357]
I had a running, not very complex, 2.2 installation using RPMs for openSUSE. After the update to 2.3, starting the openHAB service fails. I already tried with a clean installation (also removing everything unter /var/lib/openhab2).

The error is
`Jun 09 06:24:49 computer.local systemd[1]: Started The openHAB 2 Home Automation Bus Solution.
Jun 09 06:24:49 computer.local start.sh[6307]: Launching the openHAB runtime...
Jun 09 06:24:49 computer.local start.sh[6307]: mkdir: das Verzeichnis „“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gef>
Jun 09 06:24:49 computer.local start.sh[6307]: null
Jun 09 06:24:49 computer.local start.sh[6307]: Error occurred shutting down framework: java.lang.NumberFormatException: null
Jun 09 06:24:49 computer.local start.sh[6307]: java.lang.NumberFormatException: null
Jun 09 06:24:49 computer.local start.sh[6307]:         at java.lang.Integer.parseInt(Integer.java:542)
Jun 09 06:24:49 computer.local start.sh[6307]:         at java.lang.Integer.parseInt(Integer.java:615)
Jun 09 06:24:49 computer.local start.sh[6307]:         at org.apache.karaf.main.ConfigProperties.<init>(ConfigProperties.java:214)
Jun 09 06:24:49 computer.local start.sh[6307]:         at org.apache.karaf.main.Main.updateInstancePidAfterShutdown(Main.java:228)
Jun 09 06:24:49 computer.local start.sh[6307]:         at org.apache.karaf.main.Main.main(Main.java:193)
Jun 09 06:24:49 computer.local systemd[1]: openhab2.service: Main process exited, code=exited, status=254/n/a
Jun 09 06:24:49 computer.local systemd[1]: openhab2.service: Unit entered failed state.
Jun 09 06:24:49 computer.local systemd[1]: openhab2.service: Failed with result 'exit-code'.
Jun 09 06:24:49 computer.local systemd[1]: openhab2.service: Service hold-off time over, scheduling restart.
Jun 09 06:24:49 computer.local systemd[1]: Stopped The openHAB 2 Home Automation Bus Solution.
Jun 09 06:24:49 computer.local systemd[1]: openhab2.service: Start request repeated too quickly.
Jun 09 06:24:49 computer.local systemd[1]: Failed to start The openHAB 2 Home Automation Bus Solution.
Jun 09 06:24:49 computer.local systemd[1]: openhab2.service: Unit entered failed state.
Jun 09 06:24:49 computer.local systemd[1]: openhab2.service: Failed with result 'exit-code'.`

The (German) error message says that a folder named "" (empty) could not be created, file or folder not found.

**Comment by BClark09** [comment]
Hi @Larx, this looks like an issue specific to the https://github.com/openhab/openhab-linuxpkg repo

However, it looks like its using a non standard service file. The service file doesn't call start.sh could you confirm using `systemctl status openhab2` that you're using a system file located in `/usr/lib/...`. 

If you are, please raise an issue on the above issue and we can debug further 🙂
