### ISSUE TITLE
OH makes unsolicited `handleCommand()` calls to bindings when channel is showing in Main UI and value is PercentType(BigDecimal)

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#3571]
EDIT: it seems that this issue is a bug in the OH Main UI. So maintainers can you move it from OH core to OH to UI?

Following are two scenarios, one where the bug does occur, and one where is does NOT occur.

### Bug Scenario

- Open a Main UI page that shows a channel value (example below).
- From some other source (e.g. the App of the respective binding) issue a command to change the same channel value.
- The new value will be updated on the Main UI screen.
- And (BUG) then OH makes a `handleCommand()` call to the binding with the respective new value.

### Non Bug Scenario

- DO NOT open a Main UI page
- From some other source (e.g. the App of the respective binding) issue a command to change the same channel value.
- Then OH does NOT make a `handleCommand()` call to the binding with the respective new value.

![image](https://user-images.githubusercontent.com/893994/233844908-5c068edf-a455-480f-a349-da2652a514a2.png)

**Comment by J-N-K** [comment]
I created a deconz thing with a brightness channel and linked it to a dimmer item (which should be very similar to your hue setup above). I then used the console to `openhab:send TestItem 20`, the light changed, the item also changed, but I did only receive one call to `handleCommand`.

**Comment by andrewfg** [comment]
^
I only see the issue when the respective channel / item is displayed in Main UI (as on my screen shot)

**Comment by J-N-K** [comment]
Yes, I has the same view as above. I'll check with update state, BUT I did update the state from remote and I also did not see it.

**Comment by andrewfg** [comment]
> Do you see the same with other bindings or only with hue?

I don't know any other bindings where I can simulate the same test case; so can we please focus on the one where I can?

The test case is if Main UI is showing a dimmer slider for a channel, and the Hue app sends an update for that dimmer channel then handleCommand() is called with the following forced stat trace. Whereas if I close the browser, and the Hue app sends another update for that same dimmer channel, the handleCommand() is NOT called, so no stack trace occurs. (stack trace line numbers refer to OH v4.x)

```
2023-04-25 14:36:53.645 [DEBUG] [e.internal.handler.Clip2ThingHandler] - handleCommand() FORCE STACK TRACE
java.lang.IllegalStateException: null
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.handleCommand(Clip2ThingHandler.java:285) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) ~[?:?]
	at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) ~[?:?]
	at jdk.proxy233.$Proxy335.handleCommand(Unknown Source) ~[?:?]
	at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:85) ~[?:?]
	at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) ~[?:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by andrewfg** [comment]
^
I was doing some `Wiresharking' today, and I captured the following three messages between the OH server (on 192.168.1.38) and OH page script running in my browser (on 192.168.1.197). The first and last messages are the OH server sending SSE state updates to the browser with status update values. The first status update value (66.14) was triggered by sliding the brightness in the Hue app. Then the second message is a POST from the OH page script on the browser where it sends the (rounded) value '66' back to the OH sever. And finally the last status update value (66) is the response to the middle message. **_=> IMHO the middle message should NOT have been sent_** .. and therefore the last message would not have been triggered..

```
17:26:02.019728	192.168.1.38 => 192.168.1.197	TCP	`data: {"Test_Lamp_Brightness":{"state":"66.14"}}`

17:26:02.357439	192.168.1.197 => 192.168.1.38	HTTP	`POST /rest/items/Test_Lamp_Brightness HTTP/1.1 Content:=> 66`

17:26:02.372887	192.168.1.38 => 192.168.1.197	TCP	`data: {"Test_Lamp_Brightness":{"state":"66"}}`
```

.. so (given our recent discussions about PercentType with BigDecimal values) it may may be something odd, round-trip related, and integer rounding related, in the OH page script .. this is just a **_hypothesis_** at the moment, but I will run some more tests.

**Comment by andrewfg** [comment]
> may be something odd, round-trip related, and integer rounding related, in the OH page script .. this is just a hypothesis at the moment, but I will run some more tests

Yup! It is a rounding problem. I made a rudimentary binding that calls `updateState()` with either `PercentType(int)` or `PercentType(BigDecimal)`, and I can see that in case of the latter only, the browser page script calls `handleCommand()`.

```
public class aardvarkHandler extends BaseThingHandler {

    private final Logger logger = LoggerFactory.getLogger(aardvarkHandler.class);

    private Random random = new Random();
    private boolean useInt;
    private PercentType lastUpdate = PercentType.ZERO;

    private @Nullable ScheduledFuture<?> task;

    public aardvarkHandler(Thing thing) {
        super(thing);
    }

    @Override
    public void handleCommand(ChannelUID channelUID, Command command) {
        if (!(command instanceof RefreshType)) {
            if (useInt) {
                // this code is never called because command and lastUpdate are equal
                logger.info("handleCommand({}, {}=={})", channelUID.getId(), command, lastUpdate);
            } else {
                // this code is always called because command and lastUpdate are not equal
                logger.info("handleCommand({}, {}!={})", channelUID.getId(), command, lastUpdate);
            }
        }
    }

    @Override
    public void initialize() {
        updateStatus(ThingStatus.ONLINE);
        task = scheduler.scheduleWithFixedDelay(() -> {
            useInt = !useInt;
            if (useInt) {
                int valueInt = random.nextInt(100);
                PercentType valueIntPercent = new PercentType(valueInt);
                updateState(aardvarkBindingConstants.CHANNEL_1, valueIntPercent);
                lastUpdate = valueIntPercent;
            } else {
                BigDecimal valueBig = new BigDecimal(random.nextDouble(100f)).setScale(5, RoundingMode.HALF_UP);
                PercentType valueBigPercent = new PercentType(valueBig);
                updateState(aardvarkBindingConstants.CHANNEL_1, valueBigPercent);
                lastUpdate = valueBigPercent;
            }
        }, 10, 10, TimeUnit.SECONDS);
    }

```

```
2023-04-26 19:15:10.389 [INFO ] [ng.aardvark.internal.aardvarkHandler] - handleCommand(channel1, 52!=51.96842)
2023-04-26 19:15:30.393 [INFO ] [ng.aardvark.internal.aardvarkHandler] - handleCommand(channel1, 46!=45.85151)
2023-04-26 19:15:50.402 [INFO ] [ng.aardvark.internal.aardvarkHandler] - handleCommand(channel1, 76!=76.06227)
2023-04-26 19:16:10.406 [INFO ] [ng.aardvark.internal.aardvarkHandler] - handleCommand(channel1, 87!=86.99985)
2023-04-26 19:16:50.397 [INFO ] [ng.aardvark.internal.aardvarkHandler] - handleCommand(channel1, 45!=44.99633)
2023-04-26 19:17:10.396 [INFO ] [ng.aardvark.internal.aardvarkHandler] - handleCommand(channel1, 48!=47.56714)
```

**Comment by J-N-K** [comment]
That's an UI bug. UI should either truncate the value to an int before setting it to the slider or (better) correctly handle the "exact" value.

**Comment by andrewfg** [comment]
^
Shall I open a new Issue in UI? Or can you transfer this issue to UI?

**Comment by J-N-K** [comment]
I can't, but @ghys or @kaikreuzer can.

**Comment by kaikreuzer** [comment]
As https://github.com/openhab/openhab-webui/issues/1862 has been created, I guess this issue no longer needs to be transferred - hence I close it.
