### ISSUE TITLE
mvn:org.openhab.addons.bundles/org.openhab.binding.exec/4.0.0 does not contain a manifest

### ISSUE THREAD

**Issue by dwrobel** [openhab/openhab-core#3728]
I'm trying to do a fresh installation of `openhab-4.0.0` on a fully updated Fedora 38 Server on raspberry Pi 4 (4GB).

The installation is done using ansible playbook and the scenario is as follows _(the relevant part)_:
- install openhab dependencies (e.g. openjdk-17, etc..)
- install openhab and openhab-addons rpm packages
- provision openhab _(by installing all configuration in /etc/openhab)_, see addons.cfg:
 ```
# cat /etc/openhab/services/addons.cfg
remote = false
binding = exec,mqtt,telegram
persistence = influxdb
transformation = regex,map
ui = basic
```
- start openhab.service

- /var/log/openhab/openhab.log contains:
```
[INFO ] [org.openhab.core.Activator          ] - Starting openHAB 4.0.0 (build Release Build)
[INFO ] [.core.internal.i18n.I18nProviderImpl] - Locale set to 'en_PL'.
[WARN ] [org.openhab.core.net.NetUtil        ] - Found multiple local interfaces - ignoring 192.168.160.43
[ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-exec, openhab-binding-mqtt, openhab-transformation-map, openhab-ui-basic, openhab-binding-telegram,
        Resource mvn:org.openhab.addons.bundles/org.openhab.binding.exec/4.0.0 does not contain a manifest
```

- journalctl -b  -u openhab excerpt:
```
Jul 24 15:15:58 rpi44 systemd[1]: Started openhab.service - openHAB - empowering the smart home.
Jul 24 15:31:22 rpi44 karaf[588]: org.apache.karaf.features.internal.util.MultiException: Error:
Jul 24 15:31:22 rpi44 karaf[588]:         Resource mvn:org.openhab.addons.bundles/org.openhab.binding.exec/4.0.0 does not contain a manifest
Jul 24 15:31:22 rpi44 karaf[588]:         at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
Jul 24 15:31:22 rpi44 karaf[588]:         at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
Jul 24 15:31:22 rpi44 karaf[588]:         at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:474)
Jul 24 15:31:22 rpi44 karaf[588]:         at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:469)
Jul 24 15:31:22 rpi44 karaf[588]:         at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:223)
Jul 24 15:31:22 rpi44 karaf[588]:         at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
Jul 24 15:31:22 rpi44 karaf[588]:         at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
Jul 24 15:31:22 rpi44 karaf[588]:         at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
Jul 24 15:31:22 rpi44 karaf[588]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jul 24 15:31:22 rpi44 karaf[588]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Jul 24 15:31:22 rpi44 karaf[588]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Jul 24 15:31:22 rpi44 karaf[588]:         at java.base/java.lang.Thread.run(Thread.java:833)
Jul 24 15:31:22 rpi44 karaf[588]:         Suppressed: java.lang.IllegalArgumentException: Resource mvn:org.openhab.addons.bundles/org.openhab.binding.exec/4.0.0 does not contain a manifest
Jul 24 15:31:22 rpi44 karaf[588]:                 at org.apache.karaf.features.internal.region.Subsystem.getMetadata(Subsystem.java:691)
Jul 24 15:31:22 rpi44 karaf[588]:                 at org.apache.karaf.features.internal.region.Subsystem.lambda$downloadBundles$1(Subsystem.java:516)
Jul 24 15:31:22 rpi44 karaf[588]:                 at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.lambda$download$0(MavenDownloadManager.java:138)
Jul 24 15:31:22 rpi44 karaf[588]:                 at org.apache.karaf.features.internal.download.impl.DefaultFuture.notifyListener(DefaultFuture.java:350)
Jul 24 15:31:22 rpi44 karaf[588]:                 at org.apache.karaf.features.internal.download.impl.DefaultFuture.notifyListeners(DefaultFuture.java:335)
Jul 24 15:31:22 rpi44 karaf[588]:                 at org.apache.karaf.features.internal.download.impl.DefaultFuture.setValue(DefaultFuture.java:259)
Jul 24 15:31:22 rpi44 karaf[588]:                 at org.apache.karaf.features.internal.download.impl.AbstractDownloadTask.setFile(AbstractDownloadTask.java:61)
Jul 24 15:31:22 rpi44 karaf[588]:                 at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:61)
Jul 24 15:31:22 rpi44 karaf[588]:                 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
Jul 24 15:31:22 rpi44 karaf[588]:                 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jul 24 15:31:22 rpi44 karaf[588]:                 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
Jul 24 15:31:22 rpi44 karaf[588]:                 ... 3 more
```

FYI, similar worked for me last week for version `3.4.4`.

## Your Environment
Fully updated FedoraServer 38 on aarch64 architecture:
```
# rpm -qv java-17-openjdk-headless openhab openhab-addons
java-17-openjdk-headless-17.0.7.0.7-5.fc38.aarch64
openhab-4.0.0-1.noarch
openhab-addons-4.0.0-1.noarch
```

**Comment by wborn** [comment]
I extracted the Exec Binding JAR from the KAR in the [RPM](https://openhab.jfrog.io/artifactory/openhab-linuxpkg-rpm/stable/4.0.0/openhab-addons-4.0.0-1.noarch.rpm) and the manifest is in it. So it is probably some local hiccup on your system. Maybe clean the cache or remove/install the openhab-addons package again?

**Comment by dwrobel** [comment]
>Maybe clean the cache or remove/install the openhab-addons package again?

**Comment by dwrobel** [comment]
>Maybe clean the cache or remove/install the openhab-addons package again?

That was actually a complete fresh installation _(including operating system)_, so no leftovers.

Moreover, rpm confirms that the installation is correct _(file is intact)_:
```
# rpm -Va openhab-addons-4.0.0-1.noarch
#
```
For the record:
```
# rpm -ql openhab-addons
/usr/share/openhab/addons/openhab-addons-4.0.0.kar
# sha256sum /usr/share/openhab/addons/openhab-addons-4.0.0.kar
fec9aac5b6add6bcd388c9174ccf8bb402714bbeeef983e9f9a9aea7c3d38464  /usr/share/openhab/addons/openhab-addons-4.0.0.kar
# rpm -qv java-17-openjdk-headless
java-17-openjdk-headless-17.0.7.0.7-5.fc38.aarch64
```

I've tried to reproduce, but I couldn't. So, I'll close it.
I'm sorry for the trouble.

**Comment by dwrobel** [comment]
>Maybe clean the cache or remove/install the openhab-addons package again?

That was actually a complete fresh installation _(including operating system)_, so no leftovers.

Moreover, rpm confirms that the installation is correct _(file is intact)_:
```
# rpm -Va openhab-addons-4.0.0-1.noarch
#
```
For the record:
```
# rpm -ql openhab-addons
/usr/share/openhab/addons/openhab-addons-4.0.0.kar
# sha256sum /usr/share/openhab/addons/openhab-addons-4.0.0.kar
fec9aac5b6add6bcd388c9174ccf8bb402714bbeeef983e9f9a9aea7c3d38464  /usr/share/openhab/addons/openhab-addons-4.0.0.kar
# rpm -qv java-17-openjdk-headless
java-17-openjdk-headless-17.0.7.0.7-5.fc38.aarch64
```

I've tried to reproduce, but I couldn't. So, I'll close it.
I'm sorry for the trouble.

**Comment by dwrobel** [comment]
It looks like I can't close it.

**Comment by wborn** [comment]
Perhaps something went wrong while Karaf was extracting the add-ons from the KAR file.
