### ISSUE TITLE
after upgrade to 4.0.1 - java.io.IOException: Failed to bind to /192.168.0.22:8443

### ISSUE THREAD

**Issue by thomas-roos** [openhab/openhab-core#3731]
after upgrading from latest 3.4.4. to 4.0.1 I get this error message:
```

2023-07-26 10:00:06.425 [ERROR] [j.pax.web.service.internal.Activator] - Unable to start Pax Web server: Failed to bind to /192.168.0.22:8443
java.io.IOException: Failed to bind to /192.168.0.22:8443
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[?:?]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.start(JettyServerWrapper.java:623) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.start(JettyServerController.java:109) ~[?:?]
	at org.ops4j.pax.web.service.internal.Activator.performConfiguration(Activator.java:555) ~[?:?]
	at org.ops4j.pax.web.service.internal.Activator.updateController(Activator.java:445) ~[?:?]
	at org.ops4j.pax.web.service.internal.Activator.lambda$updateServerControllerFactory$1(Activator.java:347) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[?:?]
	... 17 more

```
If I do an 
```
lsof -i :8443 I see
java    13924 openhab  101u  IPv4 301522      0t0  TCP *:8443 (LISTEN)
```
But web access is not possible.
After stopping openhab there is no process bind to this port so I guess it's something wrong in the code?

**Comment by rkoshak** [comment]
This isn't a bug. Something else is running on that machine which is already bound to port 8443. Perhaps the old OH 3.4.4 is still running or you are trying to run two instances of OH 4 somehow.

**Comment by thomas-roos** [comment]
why that sure?
As said `systemctl stop openhab` will stop the one and one java process that try to bind that port. When changing the configured port the error change to the other port. When rebooting same issue.
I did just revert the upgrade and everything is just fine again.

**Comment by rkoshak** [comment]
> why that sure?

Because the only way a bind exception can occur is when a process attempts to connect to a port that is already in use by another process. 

> As said systemctl stop openhab will stop the one and one java process that try to bind that port.

Well sure, because the second Java instance crashed with the bind exception. You'd only ever see the one Java process that managed to start first and grab the port and the other one will crash. A bind exception is a terminal exception. OH exits on that error. So if you still see a Java process running and bound to that port, it means that was the one that came up first and got the port. That's not the instance generating the bind exception.

You've not mentioned how it's installed nor how you upgraded. All I can say with the evidence presented is you've got two instances of OH trying to run. The first one manages to bind to the port and continue running and the second one fails because the port is already in use.

**Comment by thomas-roos** [comment]
Sounds like the right direction, but still don't know who is starting the two instances?
Any advice on how to debug?

I do upgrade and downgrade my Ubuntu 22.04. with apt. openhab and openhab-addons package. And just could reproduce it.

**Comment by rkoshak** [comment]
First thing I'd do is reboot and verify it's not just some latent weirdness. 

Then look at the openhab.service file (I'm not sure where it resides, either somewhere under /etc/systemd or under /var/lib/systemd) Make sure there isn't more than one of them, no repeated lines in the files, etc.

Make sure there are no Java processes running and see what happens if you kick off OH using the start.sh script.

**Comment by thomas-roos** [comment]
ok, this is basically what I did. 
I just did try the start.sh thing - no difference. (The start_debug.sh is not working in both versions)
And when starting openhab with start.sh with version 4.0.1 there is no webinterface...

```
tro@mother:~$ sudo -u openhab /usr/share/openhab/start_debug.sh 
Launching the openHAB runtime...
ERROR: transport error 202: socket creation failed: Address family not supported by protocol
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
tro@mother:~$ sudo -u openhab /usr/share/openhab/start.sh 
Launching the openHAB runtime...

                           _   _     _     ____  
   ___   ___   ___   ___  | | | |   / \   | __ ) 
  / _ \ / _ \ / _ \ / _ \ | |_| |  / _ \  |  _ \ 
 | (_) | (_) |  __/| | | ||  _  | / ___ \ | |_) )
  \___/|  __/ \___/|_| |_||_| |_|/_/   \_\|____/ 
       |_|       3.4.4 - Release Build

Use '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
To exit, use '<ctrl-d>' or 'logout'.



tro@mother:~$ sudo -u openhab /usr/share/openhab/start_debug.sh 
Launching the openHAB runtime...
ERROR: transport error 202: socket creation failed: Address family not supported by protocol
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
tro@mother:~$ sudo -u openhab /usr/share/openhab/start.sh 
Launching the openHAB runtime...

                           _   _     _     ____  
   ___   ___   ___   ___  | | | |   / \   | __ ) 
  / _ \ / _ \ / _ \ / _ \ | |_| |  / _ \  |  _ \ 
 | (_) | (_) |  __/| | | ||  _  | / ___ \ | |_) )
  \___/|  __/ \___/|_| |_||_| |_|/_/   \_\|____/ 
       |_|       4.0.0 - Release Build

Use '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
To exit, use '<ctrl-d>' or 'logout'.
```
The error occurs right after start, so no log of any other start between.
```
2023-07-27 07:04:20.751 [INFO ] [org.openhab.core.Activator          ] - Starting openHAB 4.0.0 (build Release Build)
2023-07-27 07:04:20.840 [ERROR] [j.pax.web.service.internal.Activator] - Unable to start Pax Web server: Failed to bind to /192.168.0.22:8443
java.io.IOException: Failed to bind to /192.168.0.22:8443
```

**Comment by rkoshak** [comment]
So, usually a bind error means something else has a lock on that port. But the error you are seeing outside of openhab.log seems to indicate something else is the problem. 

Searching for that error message indicates it's one of:

- malware on the machine (e.g. Relevant Knowledge)
- antivirus software on the machine
- IPv6 doesn't work that well with Java all the time

I'm going to assume the first two are not at issue here so try to disable IP6 on the machine or, if you can't do that pass the following argument to the JVM to start OH 4:

    -Djava.net.preferIPv4Stack=true

**Comment by rkoshak** [comment]
>  can it be the case that 4.0.0 only support IPv6 ?

No, it definitely supports IPv4.

> still no luck, did again upgrade, enable IPv6 then again disable by setting that env - but still PAX has issues, the cmd line issues are gone.

Well that is indeed some progress. We now know that's not an issue.  

Is there a host based firewall or other controls in place.

Ultimately what's happen is OH is saying to the OS "hey, I want to listen on port 8443" and the OS is saying "Sorry, someone else got to it first, not allowed."

**Comment by thomas-roos** [comment]
Did save my config, apt purge openhab -addons and reinstalled. Restored config. Its working.
So my guess is some java lib cache etc that was broken...
