### ISSUE TITLE
Openhab 4.0.1 Crashes on Startup

### ISSUE THREAD

**Issue by TheTrueRandom** [openhab/openhab-core#3741]
## Expected Behavior
Openhab doesn't crash on startup

## Current Behavior
Openhab tries to start, many services are starting, then the following exception is printed and openhab restarts itself (endless loop). 
```
Aug 03 22:52:35 openhabian karaf[11735]: Exception in thread "Thread-125" java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
Aug 03 22:52:35 openhabian karaf[11735]:         at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
Aug 03 22:52:35 openhabian karaf[11735]:         at org.openhab.core.model.thing.internal.GenericThingProvider$1.lambda$1(GenericThingProvider.java:989)
Aug 03 22:52:35 openhabian karaf[11735]:         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Aug 03 22:52:35 openhabian karaf[11735]:         at org.openhab.core.model.thing.internal.GenericThingProvider$1.run(GenericThingProvider.java:1005)
Aug 03 22:52:35 openhabian karaf[11735]:         at java.base/java.lang.Thread.run(Thread.java:833)
```

All my things/items configuration is textual. I tried to rollback some versions of the (things/items) configuration without luck. I can't really access the UI, as just when it gets accessible, openhab crashes.

## Steps to Reproduce (for Bugs)
Unknown

## Context
I upgraded from openhab 4.0.0 to openhab 4.0.1 today with openhabian-config. This is when the error occured. I tried to downgrade to 4.0.0 again but the error is still occurring. 

## Your Environment
Openhabian on raspberry-pi

**Comment by TheTrueRandom** [comment]
Update: Recovered after some time, though I cannot tell what seems to have fixed the issue. I only tried thing/item configuration changes and restarting openhab/the whole system. 

The exception is still shown with `systemctl status openhab` so I'm not sure if it was the cause. Besides the whole thread dumps contained in the logs I think this might be an interesting section:

```
Aug 03 22:44:52 openhabian systemd[1]: openhab.service: State 'stop-sigterm' timed out. Killing.
Aug 03 22:44:52 openhabian systemd[1]: openhab.service: Killing process 5082 (java) with signal SIGKILL.
Aug 03 22:44:53 openhabian systemd[1]: openhab.service: Main process exited, code=killed, status=9/KILL
Aug 03 22:44:53 openhabian systemd[1]: openhab.service: Failed with result 'timeout'.
Aug 03 22:44:53 openhabian systemd[1]: Stopped openHAB - empowering the smart home.
Aug 03 22:44:53 openhabian systemd[1]: Started openHAB - empowering the smart home.
Aug 03 22:46:35 openhabian karaf[9532]: Exception in thread "Thread-102" java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
Aug 03 22:46:35 openhabian karaf[9532]:         at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
Aug 03 22:46:35 openhabian karaf[9532]:         at org.openhab.core.model.thing.internal.GenericThingProvider$1.lambda$1(GenericThingProvider.java:989)
Aug 03 22:46:35 openhabian karaf[9532]:         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Aug 03 22:46:35 openhabian karaf[9532]:         at org.openhab.core.model.thing.internal.GenericThingProvider$1.run(GenericThingProvider.java:1005)
Aug 03 22:46:35 openhabian karaf[9532]:         at java.base/java.lang.Thread.run(Thread.java:833)
Aug 03 22:48:30 openhabian systemd[1]: Stopping openHAB - empowering the smart home...
Aug 03 22:49:06 openhabian karaf[9532]: org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="3.18.0.v20220516-2155"; osgi.identity="org.eclipse.osgi"; singleton:="true" [id=0] STOPPED [STOPPED]
Aug 03 22:49:06 openhabian karaf[9532]:         at org.eclipse.osgi.container.Module.lockStateChange(Module.java:350)
Aug 03 22:49:06 openhabian karaf[9532]:         at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.asyncStop(EquinoxBundle.java:217)
Aug 03 22:49:06 openhabian karaf[9532]:         at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle.stop(EquinoxBundle.java:324)
Aug 03 22:49:06 openhabian karaf[9532]:         at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle.stop(EquinoxBundle.java:329)
Aug 03 22:49:06 openhabian karaf[9532]:         at org.eclipse.osgi.launch.Equinox.stop(Equinox.java:149)
Aug 03 22:49:06 openhabian karaf[9532]:         at org.apache.karaf.main.Main.lambda$registerSignalHandler$0(Main.java:387)
Aug 03 22:49:06 openhabian karaf[9532]:         at java.base/java.lang.Thread.run(Thread.java:833)
Aug 03 22:49:06 openhabian karaf[9532]: Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 30 seconds to acquire the lock.
Aug 03 22:49:06 openhabian karaf[9532]:         at org.eclipse.osgi.container.Module.lockStateChange(Module.java:347)
Aug 03 22:49:06 openhabian karaf[9532]:         ... 6 more
Aug 03 22:49:06 openhabian karaf[9532]: Caused by: org.eclipse.osgi.framework.util.ThreadInfoReport: Thread dump
```

**Comment by J-N-K** [comment]
Please send a ZIP of your .things to github@klug.nrw. And show a list of all your installed bindings.

**Comment by TheTrueRandom** [comment]
Will close the issue, openhab is running stable since, however the exception is still printed on every startup but seems to not cause openhab to crash.
