### ISSUE TITLE
Exception when using console.trace("..."); in application/javascript;version=ECMAScript-2021

### ISSUE THREAD

**Issue by kuczerek** [openhab/openhab-core#3745]
Using console.trace("..."); in a JavaScript rule (application/javascript;version=ECMAScript-2021) results in in this exception:
`2023-08-08 18:09:26.081 [ERROR] [b.automation.script.javascript.stack] - Failed to execute script:
org.graalvm.polyglot.PolyglotException: java.lang.ClassFormatError: Unexpected error from weaving hook.
        at org.eclipse.osgi.internal.weaving.WeavingHookConfigurator.processClass(WeavingHookConfigurator.java:86) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.processClass(ClasspathManager.java:735) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:706) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:639) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:607) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:587) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:566) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168) ~[org.eclipse.osgi-3.18.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.oracle.truffle.js.builtins.RegExpPrototypeBuiltins.createNode(RegExpPrototypeBuiltins.java:197) ~[?:?]
        at com.oracle.truffle.js.builtins.RegExpPrototypeBuiltins.createNode(RegExpPrototypeBuiltins.java:117) ~[?:?]
        at com.oracle.truffle.js.builtins.JSBuiltinsContainer$SwitchEnum$1FactoryImpl.createObject(JSBuiltinsContainer.java:196) ~[?:?]
        at com.oracle.truffle.js.nodes.function.BuiltinNodeFactory.createNode(BuiltinNodeFactory.java:50) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltin.createNodeImpl(JSBuiltin.java:241) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltin.createNode(JSBuiltin.java:229) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltinNode$LazyBuiltinNode.createBuiltinNode(JSBuiltinNode.java:192) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltinNode$LazyBuiltinNode.materialize(JSBuiltinNode.java:187) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltinNode$LazyBuiltinNode.tryCreateInlined(JSBuiltinNode.java:202) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.tryInlineBuiltinFunctionCall(JSFunctionCallNode.java:1003) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.createCallableNode(JSFunctionCallNode.java:959) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.specializeDirectCallShared(JSFunctionCallNode.java:384) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.specializeDirectCall(JSFunctionCallNode.java:347) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:280) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:248) ~[?:?]
        at com.oracle.truffle.js.builtins.StringPrototypeBuiltins$JSStringOperationWithRegExpArgument.call(StringPrototypeBuiltins.java:518) ~[?:?]
        at com.oracle.truffle.js.builtins.StringPrototypeBuiltins$JSStringReplaceNode.replaceGeneric(StringPrototypeBuiltins.java:1270) ~[?:?]
        at com.oracle.truffle.js.builtins.StringPrototypeBuiltinsFactory$JSStringReplaceNodeGen.executeAndSpecialize(StringPrototypeBuiltinsFactory.java:2372) ~[?:?]
        at com.oracle.truffle.js.builtins.StringPrototypeBuiltinsFactory$JSStringReplaceNodeGen.execute(StringPrototypeBuiltinsFactory.java:2298) ~[?:?]
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:143) ~[?:?]
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:92) ~[?:?]
        at <js>.trace(@jsscripting-globals.js:130) ~[?:?]
        at <js>.:program(<eval>:54) ~[?:?]
        at org.graalvm.polyglot.Context.eval(Context.java:399) ~[?:?]
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458) ~[?:?]
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:426) ~[?:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) ~[java.scripting:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.eval(DelegatingScriptEngineWithInvocableAndAutocloseable.java:53) ~[?:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.eval(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:78) ~[?:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.eval(DelegatingScriptEngineWithInvocableAndAutocloseable.java:53) ~[?:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.eval(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:78) ~[?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:71) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.execute(ScriptActionHandler.java:68) ~[?:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1188) ~[?:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.runRule(RuleEngineImpl.java:997) ~[?:?]
        at org.openhab.core.automation.internal.TriggerHandlerCallbackImpl$TriggerData.run(TriggerHandlerCallbackImpl.java:87) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-08-08 18:09:26.108 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'RobaertRegenpause' failed: org.graalvm.polyglot.PolyglotException: java.lang.ClassFormatError: Unexpected error from weaving hoo>
2023-08-08 18:09:26.089 [ERROR] [Events.Framework                    ] - FrameworkEvent ERROR
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.getResourceAsStream(String)" because "this.loader" is null
        at org.apache.aries.spifly.dynamic.OSGiFriendlyClassWriter.getCommonSuperClass(OSGiFriendlyClassWriter.java:82) ~[?:?]
        at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202) ~[?:?]
        at org.objectweb.asm.Frame.merge(Frame.java:1299) ~[?:?]
        at org.objectweb.asm.Frame.merge(Frame.java:1213) ~[?:?]
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1611) ~[?:?]
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1547) ~[?:?]
        at org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:786) ~[?:?]
        at org.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(LocalVariablesSorter.java:147) ~[?:?]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2665) ~[?:?]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514) ~[?:?]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:744) ~[?:?]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424) ~[?:?]
        at org.apache.aries.spifly.dynamic.ClientWeavingHook.weave(ClientWeavingHook.java:60) ~[?:?]
        at org.eclipse.osgi.internal.weaving.WovenClassImpl.call(WovenClassImpl.java:187) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.weaving.WovenClassImpl.call(WovenClassImpl.java:1) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1349) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHooksPrivileged(ServiceRegistry.java:1322) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.weaving.WovenClassImpl.callHooks(WovenClassImpl.java:249) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.weaving.WeavingHookConfigurator.processClass(WeavingHookConfigurator.java:80) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.processClass(ClasspathManager.java:735) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:706) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:639) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:607) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:587) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:566) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168) ~[org.eclipse.osgi-3.18.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.oracle.truffle.js.builtins.RegExpPrototypeBuiltins.createNode(RegExpPrototypeBuiltins.java:197) ~[?:?]
        at com.oracle.truffle.js.builtins.RegExpPrototypeBuiltins.createNode(RegExpPrototypeBuiltins.java:117) ~[?:?]
        at com.oracle.truffle.js.builtins.JSBuiltinsContainer$SwitchEnum$1FactoryImpl.createObject(JSBuiltinsContainer.java:196) ~[?:?]
        at com.oracle.truffle.js.nodes.function.BuiltinNodeFactory.createNode(BuiltinNodeFactory.java:50) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltin.createNodeImpl(JSBuiltin.java:241) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltin.createNode(JSBuiltin.java:229) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltinNode$LazyBuiltinNode.createBuiltinNode(JSBuiltinNode.java:192) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltinNode$LazyBuiltinNode.materialize(JSBuiltinNode.java:187) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSBuiltinNode$LazyBuiltinNode.tryCreateInlined(JSBuiltinNode.java:202) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.tryInlineBuiltinFunctionCall(JSFunctionCallNode.java:1003) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.createCallableNode(JSFunctionCallNode.java:959) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.specializeDirectCallShared(JSFunctionCallNode.java:384) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.specializeDirectCall(JSFunctionCallNode.java:347) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:280) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:248) ~[?:?]
        at com.oracle.truffle.js.builtins.StringPrototypeBuiltins$JSStringOperationWithRegExpArgument.call(StringPrototypeBuiltins.java:518) ~[?:?]
        at com.oracle.truffle.js.builtins.StringPrototypeBuiltins$JSStringReplaceNode.replaceGeneric(StringPrototypeBuiltins.java:1270) ~[?:?]
        at com.oracle.truffle.js.builtins.StringPrototypeBuiltinsFactory$JSStringReplaceNodeGen.executeAndSpecialize(StringPrototypeBuiltinsFactory.java:2372) ~[?:?]
        at com.oracle.truffle.js.builtins.StringPrototypeBuiltinsFactory$JSStringReplaceNodeGen.execute(StringPrototypeBuiltinsFactory.java:2298) ~[?:?]
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:143) ~[?:?]
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:92) ~[?:?]
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85) ~[?:?]
        at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UnboundJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1277) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:303) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:248) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:732) ~[?:?]
at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:88) ~[?:?]
        at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73) ~[?:?]
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:143) ~[?:?]
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:92) ~[?:?]
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85) ~[?:?]
        at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UnboundJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1277) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:303) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:248) ~[?:?]
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:732) ~[?:?]
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:162) ~[?:?]
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:85) ~[?:?]
        at com.oracle.truffle.js.nodes.control.IfNode.execute(IfNode.java:167) ~[?:?]
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:162) ~[?:?]
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:85) ~[?:?]
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:316) ~[?:?]
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80) ~[?:?]
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55) ~[?:?]
        at com.oracle.truffle.api.impl.DefaultBlockNode.executeGeneric(DefaultBlockNode.java:63) ~[?:?]
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:75) ~[?:?]
        at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:125) ~[?:?]
        at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73) ~[?:?]
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:143) ~[?:?]
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:92) ~[?:?]
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85) ~[?:?]
        at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59) ~[?:?]
        at com.oracle.truffle.js.lang.JavaScriptLanguage$ParsedProgramRoot.execute(JavaScriptLanguage.java:240) ~[?:?]
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85) ~[?:?]
        at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102) ~[?:?]
        at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1296) ~[?:?]
        at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63) ~[?:?]
        at org.graalvm.polyglot.Context.eval(Context.java:399) ~[?:?]
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458) ~[?:?]
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:426) ~[?:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) ~[java.scripting:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.eval(DelegatingScriptEngineWithInvocableAndAutocloseable.java:53) ~[?:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.eval(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:78) ~[?:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.eval(DelegatingScriptEngineWithInvocableAndAutocloseable.java:53) ~[?:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.eval(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:78) ~[?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:71) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.execute(ScriptActionHandler.java:68) ~[?:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1188) ~[?:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.runRule(RuleEngineImpl.java:997) ~[?:?]
        at org.openhab.core.automation.internal.TriggerHandlerCallbackImpl$TriggerData.run(TriggerHandlerCallbackImpl.java:87) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.oracle.truffle.api.TruffleStackTrace$LazyStackTrace`

## Expected Behavior

It should be possible to use console.trace() as described in https://www.openhab.org/addons/automation/jsscripting/#console

## Current Behavior
Using console.trace() triggers an exception

## Possible Solution
?

## Steps to Reproduce (for Bugs)
1. Create a rule with JavaScript, type application/javascript;version=ECMAScript-2021
2. put console.trace("xyz"); in the rule
3. run the rule

## Your Environment

* Version used: OpenHAB 4.0.1, Zulu Java 17

**Comment by rkoshak** [comment]
This is almost certainly not a core issue. It's either a JS Scripting add-on issue or an openhab-js issue. I suspect. Unless you can reproduce the error in another language this should be moved. I'd start in openhab-js.

**Comment by kuczerek** [comment]
OK, moved to openhab-js.
