### ISSUE TITLE
ConcurrentModificationException during startup from AddonSuggestionService

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#3946]
I saw this in my log file after starting openHAB 4.1.0.RC1:

```
2023-12-21 07:53:42.038 [ERROR] [scovery.addon.AddonSuggestionService] - bundle org.openhab.core.config.discovery.addon:4.1.0.RC1 (167)[org.openhab.core.config.discovery.addon.AddonSuggestionService(127)] : The addAddonFinder method has thrown an exception
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1631) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at org.openhab.core.config.discovery.addon.AddonSuggestionService.changed(AddonSuggestionService.java:189) ~[?:?]
        at org.openhab.core.config.discovery.addon.AddonSuggestionService.addAddonFinder(AddonSuggestionService.java:177) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
```

**Comment by andrewfg** [comment]
@mherwege / @kaikreuzer  for info .. I am working on a fix already..
