### ISSUE TITLE
JuPnP NPE - Cannot invoke "Object.toString()" because the return value of "org.jupnp.model.state.StateVariableValue.getValue()" is null

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-core#4037]
I updated to snapshot 3838 this morning and now I'm getting the following flooding out my logs.  Nothing on my network has changed recently.  I was on 3820 (I believe) prior to this and I did not have this issue.  I cleared cache and that had no effect.

openhab> bundle:list -s | grep pnp
246 │ Active │  80 │ 2.7.1.OH1              │ org.jupnp
247 │ Active │  80 │ 4.2.0.202401130308     │ org.openhab.core.config.discovery.addon.upnp
290 │ Active │  80 │ 4.2.0.202401130310     │ org.openhab.core.config.discovery.upnp
291 │ Active │  80 │ 4.2.0.202401130303     │ org.openhab.core.io.transport.upnp

```
2024-01-14 10:05:04.257 [ERROR] [port.upnp.internal.UpnpIOServiceImpl] - Participant threw an exception onValueReceived
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "org.jupnp.model.state.StateVariableValue.getValue()" is null
        at org.openhab.core.io.transport.upnp.internal.UpnpIOServiceImpl$UpnpSubscriptionCallback.eventReceived(UpnpIOServiceImpl.java:160) [bundleFile:?]
        at org.jupnp.controlpoint.SubscriptionCallback$2.eventReceived(SubscriptionCallback.java:222) [bundleFile:?]
        at org.jupnp.model.gena.RemoteGENASubscription.receive(RemoteGENASubscription.java:114) [bundleFile:?]
        at org.jupnp.protocol.sync.ReceivingEvent$2.run(ReceivingEvent.java:130) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

```

**Comment by morph166955** [comment]
@wborn this may be related to #4003
