### ISSUE TITLE
AbstractRemoteAddonServiceTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#4045]
This test failed in a Jenkins PR build: https://ci.openhab.org/job/PR-openHAB-Core/6816/

```
[ERROR] Tests run: 19, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.063 s <<< FAILURE! -- in org.openhab.core.addon.marketplace.AbstractRemoteAddonServiceTest
[ERROR] org.openhab.core.addon.marketplace.AbstractRemoteAddonServiceTest.testAddonUninstallRemovesStorageEntryOnUninstalledAddon -- Time elapsed: 0.031 s <<< FAILURE!
org.mockito.exceptions.verification.TooManyActualInvocations: 

eventPublisher.post(<Capturing argument>);
Wanted 1 time:
-> at org.openhab.core.addon.marketplace.AbstractRemoteAddonServiceTest.checkResult(AbstractRemoteAddonServiceTest.java:302)
But was 2 times:
-> at org.openhab.core.addon.marketplace.AbstractRemoteAddonService.postFailureEvent(AbstractRemoteAddonService.java:331)
-> at org.openhab.core.addon.marketplace.AbstractRemoteAddonService.postFailureEvent(AbstractRemoteAddonService.java:331)


	at org.openhab.core.addon.marketplace.AbstractRemoteAddonServiceTest.checkResult(AbstractRemoteAddonServiceTest.java:302)
	at org.openhab.core.addon.marketplace.AbstractRemoteAddonServiceTest.testAddonUninstallRemovesStorageEntryOnUninstalledAddon(AbstractRemoteAddonServiceTest.java:255)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AbstractRemoteAddonServiceTest.testAddonUninstallRemovesStorageEntryOnUninstalledAddon:255->checkResult:302
```

**Comment by J-N-K** [comment]
I wonder where l. 331 in `AbstractRemoteAddonService` comes from, the file only has 301 lines in my code.

**Comment by wborn** [comment]
Maybe you have changes on your local branch:

https://github.com/openhab/openhab-core/blob/d3d0fe3995b2b950e253d782efbda33b31eebeec/bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java#L331

**Comment by wborn** [comment]
Same issue in a GHA build in my fork: https://github.com/wborn/openhab-core/actions/runs/7547938703
