### ISSUE TITLE
NPE in Upgrade Tool

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#4127]
I just updated to 4.2.0 Milestone 1 and found this exception when doing the update:

```
[main] INFO org.openhab.core.tools.internal.Upgrader - Upgrading script profile configuration in database '/Applications/openhab4/userdata/jsondb/org.openhab.core.thing.link.ItemChannelLink.json'
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.matches(String)" because "profileName" is null
        at org.openhab.core.tools.internal.Upgrader.lambda$6(Upgrader.java:263)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.openhab.core.tools.internal.Upgrader.linkUpgradeScriptProfile(Upgrader.java:259)
        at org.openhab.core.tools.UpgradeTool.main(UpgradeTool.java:87)
Update tool failed, please check the openHAB website (www.openhab.org) for manual update instructions.
```

**Comment by wborn** [comment]
Fixed by https://github.com/openhab/openhab-core/pull/4128
