### ISSUE TITLE
ThreadPoolManagerTest unstable, affecting all CI builds

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab-core#4287]
Currently, we see the builds failing more frequently than before.
PR builds are affected as well as the merge build.

Typical errors look like this:
```
Error:  org.openhab.core.common.ThreadPoolManagerTest.testSchedulingDoesSpawnNewThreads -- Time elapsed: 0.171 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
	at org.openhab.core.common.ThreadPoolManagerTest.testSchedulingDoesSpawnNewThreads(ThreadPoolManagerTest.java:205)
```

It seems to be a timing issue, as a rebuild typically works fine.

**Comment by holgerfriedrich** [comment]
@joerg1985 could you please have a look? It seems this was introduced by PR #4247. Thanks!

**Comment by joerg1985** [comment]
@holgerfriedrich okay, will have a look the next days.
