### ISSUE TITLE
Nightly openHAB builds failing to start 

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-core#4374]
Tried updating my system today to the latest nightly,  when the system starts up much of the bundles fail to load due to a missing maven dependency `ch.obermuhlner:big-math:jar:2.3.2` 

```
	Suppressed: java.io.IOException: Error downloading mvn:ch.obermuhlner/big-math/2.3.2
openhab  | 		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
openhab  | 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
openhab  | 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
openhab  | 		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
openhab  | 		... 3 more
openhab  | 	Caused by: java.io.IOException: Error resolving artifact ch.obermuhlner:big-math:jar:2.3.2: [Could not find artifact ch.obermuhlner:big-math:jar:2.3.2 in openhab (https://openhab.jfrog.io/openhab/libs-snapshot/)]
openhab  | 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
openhab  | 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
openhab  | 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
openhab  | 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
openhab  | 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
openhab  | 		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
openhab  | 		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
openhab  | 		... 6 more
openhab  | 		Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact ch.obermuhlner:big-math:jar:2.3.2 in openhab (https://openhab.jfrog.io/openhab/libs-snapshot/)
openhab  | 			at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
openhab  | 			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:401)
openhab  | 			at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73)
openhab  | 			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:669)
openhab  | 			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:290)
openhab  | 			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
openhab  | 			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:408)
openhab  | 			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
openhab  | 			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
openhab  | 			at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:272)
openhab  | 			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
openhab  | 			... 11 more
```

And indeed, that jar version does not exist on jfrog  `https://openhab.jfrog.io/ui/native/libs-snapshot/ch/obermuhlner/big-math/`  .   I'm guessing this a build server issue, but not sure the right place to report, so starting here.

**Comment by holgerfriedrich** [comment]
Thanks for the report!

There was a recent change to introduce Jinjava as OSGI package,
https://github.com/openhab/openhab-osgiify/pull/48

https://github.com/openhab/openhab-addons/pull/17358 indroduced this dependency in ```transform.jinja```. ```binding.mqtt.homeassistant``` is affected as well.

@J-N-K could you please have a look, seems we have to upload the artifact....

**Comment by J-N-K** [comment]
I can't do that.

**Comment by kaikreuzer** [comment]
I've deployed the new version of the jar to our Artifactory.
