### ISSUE TITLE
IDE installation fails for ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.

### ISSUE THREAD

**Issue by amosk** [openhab/openhab-core#454]
Greenfield IDE installation on OS X Majove following https://www.openhab.org/docs/developer/development/ide.html, step 6 fails with: 

```
Executing bootstrap tasks
Renamed existing configuration folder to /Users/amosk/Workspace/openhab2-dev-master/Eclipse.app/Contents/Eclipse/configuration.1545627845903
Java(TM) SE Runtime Environment 1.8.0_191-b12
Product org.eclipse.products.epp.package.java.latest.released
Workspace /Users/amosk/Workspace/openhab2-dev-master/ws
Project com.github.openhab2.1_infra.master
Bundle org.eclipse.oomph.setup 1.10.0.v20180914-1031, build=3784, branch=d5b911e1f3bc20f8e0c54af3126d8150fbc53bdf
Bundle org.eclipse.oomph.setup.core 1.11.0.v20181203-0741, build=3784, branch=d5b911e1f3bc20f8e0c54af3126d8150fbc53bdf
Bundle org.eclipse.oomph.setup.installer 1.11.0.v20181107-1003, build=3784, branch=d5b911e1f3bc20f8e0c54af3126d8150fbc53bdf
Bundle org.eclipse.oomph.setup.p2 1.10.0.v20180706-1242, build=3784, branch=d5b911e1f3bc20f8e0c54af3126d8150fbc53bdf
Performing P2 Director (Eclipse IDE for Java Developers (2018-12))
Offline = false
Mirrors = true
Resolving 32 requirements from 5 repositories to /Users/amosk/Workspace/openhab2-dev-master/Eclipse.app/Contents/Eclipse
Requirement org.eclipse.wst.xml_ui.feature.feature.group
Requirement org.eclipse.mylyn.java_feature.feature.group
Requirement org.codehaus.groovy.eclipse.feature.feature.group
Requirement org.eclipse.mylyn.git.feature.group
Requirement org.eclipse.pde.feature.group
Requirement org.eclipse.wst.jsdt.feature.feature.group
Requirement org.eclipse.wst.web_ui.feature.feature.group
Requirement epp.package.java [4.10.0,5.0.0)
Requirement org.eclipse.platform.feature.group [4.10.0,5.0.0)
Requirement org.eclipse.rcp.feature.group [4.10.0,5.0.0)
Requirement org.eclipse.buildship.feature.group
Requirement org.eclipse.eclemma.feature.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.egit.mylyn.feature.group
Requirement org.eclipse.epp.mpc.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement org.eclipse.jgit.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.m2e.logback.feature.feature.group
Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
Requirement org.eclipse.mylyn.context_feature.feature.group
Requirement org.eclipse.mylyn.hudson.feature.group
Requirement org.eclipse.mylyn.ide_feature.feature.group
Requirement org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.mylyn_feature.feature.group
Requirement org.eclipse.tips.feature.feature.group
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Requirement org.eclipse.oomph.setup.projects.feature.group
Requirement org.eclipse.oomph.setup.pde.feature.group
Repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.8
Repository http://download.eclipse.org/technology/epp/packages/2018-12
Repository http://download.eclipse.org/releases/2018-12/201812191000
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Repository http://download.eclipse.org/egit/updates
Adding repository http://download.eclipse.org/technology/epp/packages/2018-12
Adding repository http://download.eclipse.org/releases/2018-12/201812191000
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://download.eclipse.org/egit/updates
Adding repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.8
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:733)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3334)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3262)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3243)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3143)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1545627847607
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.14.0.xx-201812211534-e48 (org.eclipse.jdt.core 3.14.0.xx-201812211534-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.16.0.v20181130-1748 (org.eclipse.jdt.core 3.16.0.v20181130-1748)
    ERROR: org.eclipse.equinox.p2.director code=0 Object Teams Development Tooling Core 3.16.0.OTDT_r272_201812061254 (org.eclipse.jdt.core 3.16.0.OTDT_r272_201812061254)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1545627847607
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1545627847607
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Compilerless feature 3.2.0.xx-201812211534-e48 (org.codehaus.groovy.compilerless.feature.feature.group 3.2.0.xx-201812211534-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [3.2.0.xx-201812211534-e48,3.2.0.xx-201812211534-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Groovy Development Tools 3.2.0.xx-201812211534-e48 (org.codehaus.groovy.eclipse.feature.feature.group 3.2.0.xx-201812211534-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [3.2.0.xx-201812211534-e48,3.2.0.xx-201812211534-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Headless feature 3.2.0.xx-201812211534-e48 (org.codehaus.groovy.headless.feature.feature.group 3.2.0.xx-201812211534-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [3.2.0.xx-201812211534-e48,3.2.0.xx-201812211534-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: JDI Debug UI 3.10.100.v20181120-0542 (org.eclipse.jdt.debug.ui 3.10.100.v20181120-0542)
    ERROR: org.eclipse.equinox.p2.director code=0 To: osgi.bundle; org.eclipse.jdt.core [3.15.0,4.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Java Development Tools 3.16.0.v20181206-1038 (org.eclipse.jdt.feature.group 3.16.0.v20181206-1038)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.debug.ui [3.10.100.v20181120-0542,3.10.100.v20181120-0542]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From Patch: org.codehaus.groovy.jdt.patch.feature.group 3.2.0.xx-201812211534-e48 Eclipse Java Development Tools 3.16.0.v20181206-1038 (org.eclipse.jdt.feature.group 3.16.0.v20181206-1038)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.14.0.xx-201812211534-e48,3.14.0.xx-201812211534-e48]
```

Tried deleting ~/.eclipse.

Eclipse 2018-12
java version "1.8.0_191"
Apache Maven 3.6.0

Following https://www.eclipse.org/smarthome/documentation/development/ide.html on the same platform completed successfully.

**Comment by amosk** [comment]
Apologies if this issue should go somewhere else. Not sure where develement install issues are tracked. 

See also https://community.openhab.org/t/conflicting-dependencies-fresh-ide-install-on-mac-mojave/60715.
