### ISSUE TITLE
CNFE when launching app.bndrun

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#576]
When launching app.bndrun after a successful setup, I see the following in the console log at startup:

```
! Failed to start bundle org.openhab.core.io.rest.sse-2.5.0.201902141241, exception activator error null from: org.eclipse.smarthome.io.rest.sse.internal.SseActivator:start#49
org.osgi.framework.BundleException: Exception in org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start() of bundle org.openhab.core.io.rest.sse.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:803)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:732)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	at org.eclipse.osgi.container.Module.doStart(Module.java:584)
	at org.eclipse.osgi.container.Module.start(Module.java:452)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:431)
	at aQute.launcher.Launcher.startBundles(Launcher.java:519)
	at aQute.launcher.Launcher.activate(Launcher.java:425)
	at aQute.launcher.Launcher.run(Launcher.java:303)
	at aQute.launcher.Launcher.main(Launcher.java:149)
Caused by: java.lang.ExceptionInInitializerError
	at org.eclipse.smarthome.io.rest.sse.internal.SseActivator.start(SseActivator.java:49)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:782)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:775)
	... 10 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.server.internal.RuntimeDelegateImpl cannot be found by org.apache.aries.javax.jax.rs-api_1.0.0
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:64)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:48)
	at javax.ws.rs.core.MediaType.valueOf(MediaType.java:101)
	at org.glassfish.jersey.media.sse.SseFeature.<clinit>(SseFeature.java:62)
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.server.internal.RuntimeDelegateImpl cannot be found by org.apache.aries.javax.jax.rs-api_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at javax.ws.rs.ext.RuntimeDelegateFinder.newInstance(RuntimeDelegateFinder.java:113)
	at javax.ws.rs.ext.RuntimeDelegateFinder.find(RuntimeDelegateFinder.java:86)
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:58)
	... 18 more
```

**Comment by maggu2810** [comment]
Remove that line: https://github.com/openhab/openhab-core/blob/d590bba/demo/app/app.bndrun#L143

The jersey all bundle contains a lot of stuff and also the RS API.

**Comment by kaikreuzer** [comment]
That helps, thanks. Is there a special reason that this line is in or shall I create a PR to remove it?

**Comment by maggu2810** [comment]
No "special" reason. It is added on "resolve" by bnd.
