### ISSUE TITLE
NPE in automation.core bundle 

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#593]
OH 2.4

A user on the community has experienced this NPE: The `ConfigUtil` class apparently has problems to understand a condition configuration.

This is serious actually: The entire rule engine bundle does not start, because of an invalid configuration in a rule. There should be safe-guards to isolate and invalidate only that single rule.

Just want to notice this here, I have not yet verified if the current revision is also affected.

```
2019-02-20 03:14:45.406 [ERROR] [rg.eclipse.smarthome.automation.core] - bundle org.eclipse.smarthome.automation.core:0.10.0.oh240 (199)[org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl(277)] : The activate method has thrown an exception
java.lang.NullPointerException: null
	at org.eclipse.smarthome.config.core.ConfigUtil.normalizeCollection(ConfigUtil.java:156) ~[?:?]
	at org.eclipse.smarthome.config.core.ConfigUtil.normalizeType(ConfigUtil.java:78) ~[?:?]
	at org.eclipse.smarthome.config.core.ConfigUtil.normalizeTypes(ConfigUtil.java:54) ~[?:?]
	at org.eclipse.smarthome.config.core.Configuration.<init>(Configuration.java:78) ~[?:?]
	at org.eclipse.smarthome.config.core.Configuration.<init>(Configuration.java:62) ~[?:?]
	at org.eclipse.smarthome.automation.core.dto.ConditionDTOMapper.mapDto(ConditionDTOMapper.java:40) ~[?:?]
	at org.eclipse.smarthome.automation.core.dto.ConditionDTOMapper.mapDto(ConditionDTOMapper.java:61) ~[?:?]
	at org.eclipse.smarthome.automation.core.dto.RuleDTOMapper.map(RuleDTOMapper.java:37) ~[?:?]
	at org.eclipse.smarthome.automation.core.ManagedRuleProvider.toElement(ManagedRuleProvider.java:60) ~[?:?]
	at org.eclipse.smarthome.automation.core.ManagedRuleProvider.toElement(ManagedRuleProvider.java:1) ~[?:?]
	at org.eclipse.smarthome.core.common.registry.AbstractManagedProvider.lambda$0(AbstractManagedProvider.java:70) ~[?:?]
```

**Comment by openhab-5iver** [comment]
For some reason the mention in the forum didn't create a link back here. So here is the thread... https://community.openhab.org/t/rule-tab-gone-in-paper-ui/68271. I've asked for a copy of the json file.

**Comment by openhab-5iver** [comment]
The resolution for the user that reported this was to remove faulty 'day of week' Conditions that contained:

        "days": [
          "SAT",
          "SUN",
          null
        ]

The user had originally setup the rules in OH 2.2. The 'day of week' conditions currently do not work... https://github.com/eclipse/smarthome/issues/6670. So, this exact issue is unlikely to reoccur, but handling of poorly formatted rule files should be handled.
