### ISSUE TITLE
CME: org.eclipse.xtext

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#772]
Some of that annoying race conditions that are only seen some time and cannot be reproduced:

```
2019-04-29T07:32:05,568 | ERROR | CM Event Dispatcher (Fire ConfigurationEvent: pid=org.eclipse.smarthome.folder) | CompositeEValidator              | 222 - org.eclipse.xtext - 2.17.0.v20190304-0545 | Error executing EValidator
java.util.ConcurrentModificationException: null
        at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:758) ~[?:?]
        at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:712) ~[?:?]
        at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:692) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
        at com.google.common.collect.Iterables$5.forEach(Iterables.java:621) ~[87:com.google.guava:21.0.0]
        at org.eclipse.xtext.xbase.validation.UniqueClassNameValidator.checkUniqueName(UniqueClassNameValidator.java:76) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:127) ~[222:org.eclipse.xtext:2.17.0.v20190304-0545]
        at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:318) ~[222:org.eclipse.xtext:2.17.0.v20190304-0545]
        at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71) ~[222:org.eclipse.xtext:2.17.0.v20190304-0545]
        at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:150) [222:org.eclipse.xtext:2.17.0.v20190304-0545]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171) [181:org.eclipse.emf.ecore:2.12.0.v20160420-0247]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158) [181:org.eclipse.emf.ecore:2.12.0.v20160420-0247]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137) [181:org.eclipse.emf.ecore:2.12.0.v20160420-0247]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108) [181:org.eclipse.emf.ecore:2.12.0.v20160420-0247]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.validateModel(ModelRepositoryImpl.java:282) [294:org.openhab.core.model.core:2.5.0.a4]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:95) [294:org.openhab.core.model.core:2.5.0.a4]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:241) [294:org.openhab.core.model.core:2.5.0.a4]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.addModelsToRepo(FolderObserver.java:188) [294:org.openhab.core.model.core:2.5.0.a4]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.activate(FolderObserver.java:131) [294:org.openhab.core.model.core:2.5.0.a4]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:340) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:440) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:316) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:118) [133:org.apache.felix.scr:2.1.16]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:1704) [9:org.apache.felix.configadmin:1.9.14]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:1646) [9:org.apache.felix.configadmin:1.9.14]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [9:org.apache.felix.configadmin:1.9.14]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [9:org.apache.felix.configadmin:1.9.14]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by maggu2810** [comment]
I assume it is the same as already reported [here](https://github.com/eclipse/smarthome/issues/6508) just using another Xtext version now.

**Comment by maggu2810** [comment]
```
2019-06-21T12:01:56,343 | ERROR | CM Event Dispatcher (Fire ConfigurationEvent: pid=org.eclipse.smarthome.folder) | CompositeEValidator              | 223 - org.eclipse.xtext - 2.17.0.v20190304-0545 | Error executing EValidator
java.util.ConcurrentModificationException: null
        at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:758) ~[181:org.eclipse.emf.common:2.12.0.v20160420-0247]
        at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:712) ~[181:org.eclipse.emf.common:2.12.0.v20160420-0247]
        at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:692) ~[181:org.eclipse.emf.common:2.12.0.v20160420-0247]
        at org.eclipse.emf.common.util.AbstractTreeIterator.next(AbstractTreeIterator.java:133) ~[181:org.eclipse.emf.common:2.12.0.v20160420-0247]
        at org.eclipse.xtext.resource.impl.DefaultResourceDescription.computeExportedObjects(DefaultResourceDescription.java:88) ~[?:?]
        at org.eclipse.xtext.resource.DerivedStateAwareResourceDescriptionManager$1.getLookUp(DerivedStateAwareResourceDescriptionManager.java:84) ~[?:?]
        at org.eclipse.xtext.resource.impl.AbstractResourceDescription.getExportedObjects(AbstractResourceDescription.java:50) ~[?:?]
        at org.eclipse.xtext.resource.impl.AbstractCompoundSelectable$4.apply(AbstractCompoundSelectable.java:75) ~[?:?]
        at org.eclipse.xtext.resource.impl.AbstractCompoundSelectable$4.apply(AbstractCompoundSelectable.java:71) ~[?:?]
        at com.google.common.collect.Iterators$7.transform(Iterators.java:750) ~[?:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[?:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[?:?]
        at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:52) ~[?:?]
        at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50) ~[?:?]
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42) ~[?:?]
        at com.google.common.collect.Iterators.addAll(Iterators.java:366) ~[?:?]
        at com.google.common.collect.Iterables.addAll(Iterables.java:332) ~[?:?]
        at com.google.common.collect.Sets.newLinkedHashSet(Sets.java:383) ~[?:?]
        at org.eclipse.xtext.xbase.lib.IterableExtensions.toSet(IterableExtensions.java:639) ~[?:?]
        at org.eclipse.xtext.xbase.validation.UniqueClassNameValidator.checkUniqueInIndex(UniqueClassNameValidator.java:102) ~[?:?]
        at org.eclipse.xtext.xbase.validation.UniqueClassNameValidator.doCheckUniqueName(UniqueClassNameValidator.java:95) ~[?:?]
        at org.eclipse.xtext.xbase.validation.UniqueClassNameValidator.doCheckUniqueName(UniqueClassNameValidator.java:87) ~[?:?]
        at org.eclipse.xtext.xbase.validation.UniqueClassNameValidator.lambda$checkUniqueName$0(UniqueClassNameValidator.java:74) ~[?:?]
        at com.google.common.collect.Iterables$5.lambda$forEach$0(Iterables.java:624) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.google.common.collect.Iterables$5.forEach(Iterables.java:621) ~[?:?]
        at org.eclipse.xtext.xbase.validation.UniqueClassNameValidator.checkUniqueName(UniqueClassNameValidator.java:76) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:127) ~[?:?]
        at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:318) ~[?:?]
        at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71) ~[?:?]
        at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:150) ~[?:?]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171) ~[182:org.eclipse.emf.ecore:2.12.0.v20160420-0247]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158) ~[182:org.eclipse.emf.ecore:2.12.0.v20160420-0247]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137) ~[182:org.eclipse.emf.ecore:2.12.0.v20160420-0247]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108) ~[182:org.eclipse.emf.ecore:2.12.0.v20160420-0247]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.lambda$2(ModelRepositoryImpl.java:290) ~[296:org.openhab.core.model.core:2.5.0.a10]
        at org.eclipse.smarthome.model.core.internal.SafeEMFImpl.call(SafeEMFImpl.java:30) [296:org.openhab.core.model.core:2.5.0.a10]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.validateModel(ModelRepositoryImpl.java:290) [296:org.openhab.core.model.core:2.5.0.a10]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:103) [296:org.openhab.core.model.core:2.5.0.a10]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:241) [296:org.openhab.core.model.core:2.5.0.a10]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.addModelsToRepo(FolderObserver.java:188) [296:org.openhab.core.model.core:2.5.0.a10]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.activate(FolderObserver.java:131) [296:org.openhab.core.model.core:2.5.0.a10]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:340) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:440) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:316) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:118) [134:org.apache.felix.scr:2.1.16]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:1704) [9:org.apache.felix.configadmin:1.9.14]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:1646) [9:org.apache.felix.configadmin:1.9.14]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [9:org.apache.felix.configadmin:1.9.14]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [9:org.apache.felix.configadmin:1.9.14]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by wborn** [comment]
I'm seeing it frequently when starting OH3, here is a Java 11 stacktrace:

```
[ERROR] [.xtext.validation.CompositeEValidator] - Error executing EValidator
java.util.ConcurrentModificationException: null
	at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:758) ~[?:?]
	at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:712) ~[?:?]
	at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:692) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
	at com.google.common.collect.Iterables$4.forEach(Iterables.java:565) ~[bundleFile:?]
	at org.eclipse.xtext.xbase.validation.UniqueClassNameValidator.checkUniqueName(UniqueClassNameValidator.java:76) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:127) ~[bundleFile:?]
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:318) ~[bundleFile:?]
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71) ~[bundleFile:?]
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:150) [bundleFile:?]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171) [bundleFile:?]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158) [bundleFile:?]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137) [bundleFile:?]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108) [bundleFile:?]
	at org.openhab.core.model.core.internal.ModelRepositoryImpl.lambda$2(ModelRepositoryImpl.java:289) [bundleFile:?]
	at org.openhab.core.model.core.internal.SafeEMFImpl.call(SafeEMFImpl.java:30) [bundleFile:?]
	at org.openhab.core.model.core.internal.ModelRepositoryImpl.validateModel(ModelRepositoryImpl.java:289) [bundleFile:?]
	at org.openhab.core.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:102) [bundleFile:?]
	at org.openhab.core.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:246) [bundleFile:?]
	at org.openhab.core.model.core.internal.folder.FolderObserver.addModelsToRepo(FolderObserver.java:193) [bundleFile:?]
	at org.openhab.core.model.core.internal.folder.FolderObserver.activate(FolderObserver.java:128) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:340) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:440) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:316) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:118) [bundleFile:?]
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:1709) [bundleFile:?]
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:1651) [bundleFile:?]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [bundleFile:?]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [bundleFile:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by kaikreuzer** [comment]
@wborn You have added that to the 3.0 tracking - is this still an issue? I personally never came across this exception.
I'd tend to remove it from the 3.0 milestone, since it does not seem to have the criticality to be fixed within the next 2 remaining weeks, wdyt?

**Comment by wborn** [comment]
Back then I ran into it often but I haven't seen it recently either. So I think it's not that important to fix before releasing 3.0.

**Comment by J-N-K** [comment]
@wborn Have you seen this issue lately? I have not seen it in the last year and would suggest to close it. Maybe it was fixed with one of the XText upgrades.

**Comment by wborn** [comment]
I haven't seen it for a while so let's close it.
