### ISSUE TITLE
fix audio tests

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#799]
-- updated --

It seems not to be caused by "PR-openHAB-Core" but by the audio tests.

-- old --

For me it seems that "PR-openHAB-Core" does not work reliable.
At least it fails very often.

I see two options:

* Fix the Jenkins job
* Disable the requirement for a successful "PR-openHAB-Core" and rely on Travis only

**Comment by maggu2810** [comment]
See e.g.

* https://github.com/openhab/openhab-core/pull/795
* https://github.com/openhab/openhab-core/pull/793
* https://github.com/openhab/openhab-core/pull/784
* https://github.com/openhab/openhab-core/pull/757
* https://github.com/openhab/openhab-core/pull/739
* https://github.com/openhab/openhab-core/pull/738

and so on

**Comment by maggu2810** [comment]
@openhab/core-maintainers I am very interested about your comments.

**Comment by maggu2810** [comment]
[consoleText-1258.txt](https://github.com/openhab/openhab-core/files/3147201/consoleText-1258.txt)
[consoleText-1284.txt](https://github.com/openhab/openhab-core/files/3147203/consoleText-1284.txt)

**Comment by maggu2810** [comment]
```
TEST requestToMultitimeStreamCannotBeDoneAfterTheTimeoutOfTheStreamHasExipred(org.eclipse.smarthome.core.audio.internal.AudioServletTest) <<< ERROR: The response status was not as expected
Expected: is <200>
     but: was <404>
java.lang.AssertionError: The response status was not as expected
Expected: is <200>
     but: was <404>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.eclipse.smarthome.core.audio.internal.AudioServletTest.requestToMultitimeStreamCannotBeDoneAfterTheTimeoutOfTheStreamHasExipred(AudioServletTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at aQute.junit.Activator.test(Activator.java:340)
	at aQute.junit.Activator.automatic(Activator.java:236)
	at aQute.junit.Activator.run(Activator.java:177)
	at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
	at aQute.launcher.Launcher.run(Launcher.java:352)
	at aQute.launcher.Launcher.main(Launcher.java:152)
```
