### ISSUE TITLE
Integrations tests - Semantics Tests failure

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#956]
Run on Windows 10:
```
[INFO] --- bnd-testing-maven-plugin:4.2.0:testing (default) @ org.openhab.core.semantics.tests ---
[INFO] Matching glob *
20:24:54.175 [main] DEBUG org.eclipse.smarthome.core.common.ThreadPoolManager - Created thread pool 'safeCall' with size 5
20:24:54.238 [main] DEBUG org.eclipse.smarthome.core.internal.i18n.I18nProviderImpl - No language set, setting locale to 'null'.
20:24:54.238 [main] DEBUG org.eclipse.smarthome.core.internal.i18n.I18nProviderImpl - Error setting measurement system for value 'null'.
20:24:54.300 [main] DEBUG org.eclipse.smarthome.core.common.ThreadPoolManager - Created scheduled thread pool 'scheduler' of size 5
20:24:54.332 [main] DEBUG org.eclipse.smarthome.core.common.ThreadPoolManager - Created thread pool 'ConfigStatusService' with size 5
20:24:54.332 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "org.eclipse.smarthome.core.semantics.internal.SemanticsMetadataProvider" has been added.
20:24:54.363 [main] DEBUG org.eclipse.smarthome.storage.json.internal.JsonStorageService - Json Storage Service: Activated.
20:24:54.363 [main] DEBUG org.eclipse.smarthome.storage.json.internal.JsonStorage - Json storage file at 'D:\dev\openhab2\git\openhab-core\itests\org.openhab.core.semantics.tests\target\test\tmp\testing\itest\userdata\jsondb\org.eclipse.smarthome.core.items.Metadata.json' does not exist - checking for a backup.
20:24:54.378 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "org.eclipse.smarthome.core.internal.items.ManagedMetadataProviderImpl" has been added.
20:24:54.378 [main] DEBUG org.eclipse.smarthome.storage.json.internal.JsonStorage - Json storage file at 'D:\dev\openhab2\git\openhab-core\itests\org.openhab.core.semantics.tests\target\test\tmp\testing\itest\userdata\jsondb\org.eclipse.smarthome.core.items.Item.json' does not exist - checking for a backup.
20:24:54.378 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "org.eclipse.smarthome.core.items.ManagedItemProvider" has been added.
TEST testByLabelOrSynonym(org.eclipse.smarthome.core.semantics.SemanticTagsTest) <<< ERROR: null
java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:854)
        at org.eclipse.smarthome.core.semantics.SemanticTagsTest.testByLabelOrSynonym(SemanticTagsTest.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
TEST testByLabel(org.eclipse.smarthome.core.semantics.SemanticTagsTest) <<< ERROR: expected:<interface org.eclipse.smarthome.core.semantics.model.location.Kitchen> but was:<null>
java.lang.AssertionError: expected:<interface org.eclipse.smarthome.core.semantics.model.location.Kitchen> but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.eclipse.smarthome.core.semantics.SemanticTagsTest.testByLabel(SemanticTagsTest.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
TEST testGetItemsInLocation(org.eclipse.smarthome.core.semantics.internal.SemanticsServiceImplTest) <<< ERROR: null
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.eclipse.smarthome.core.semantics.internal.SemanticsServiceImplTest.testGetItemsInLocation(SemanticsServiceImplTest.java:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
Tests run  : 7
Passed     : 4
Errors     : 3
Failures   : 0
[INFO] 3 Error(s)
```

**Comment by cweitkamp** [comment]
It fails on my local machine (Linux Ubuntu) too.

**Comment by lolodomo** [comment]
Is there someone with semantic stuff knowledge able to fix that ?
If not, I suggest to disable this integration test.
After my other provided fix, this is the last issue that prevents a full build of the core framework on Windows 10.

**Comment by lolodomo** [comment]
I finally analyzed the problem and found what's wrong.
When running `SemanticTags.getByLabel("Kitchen", Locale.ENGLISH)`, it certainly searchs the file tags_en.properties. While this file does not exist, rather than considering the default tags.properties, it considers tags_fr.properties. Note that my locale is french.
The problem is at this line:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.semantics/src/main/java/org/eclipse/smarthome/core/semantics/SemanticTags.java#L94
Is it the expected behavior of `ResourceBundle.getBundle(String baseName, Locale locale)` ?

**Comment by lolodomo** [comment]
I think the fix is to add a property file tags_en.properties.

The behavior of getBundle that I guess is that if it does not find the property file for the given locale, then it search one for the system locale and then if still not found use the default property file.

**Comment by lolodomo** [comment]
https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html#getBundle-java.lang.String-java.util.Locale-java.lang.ClassLoader-

> This continues until a result resource bundle is instantiated or the list of candidate bundle names is exhausted. If no matching resource bundle is found, the default control's getFallbackLocale method is called, which returns the current default locale. A new sequence of candidate locale names is generated using this locale and and searched again, as above.
> If still no result bundle is found, the base name alone is looked up. If this still fails, a MissingResourceException is thrown. 
It matches what I noticed and what I guessed yesterday.
So, yes, we have to add a file tags_en.properties or more complicated use a ResourceBundle.Control to override the defalut loading strategy.

**Comment by lolodomo** [comment]
I found an example how to change the default loading process:
https://docs.oracle.com/javase/tutorial/i18n/resbundle/control.html
In our case, we just have to "redirect" Locale.ENGLISH to Locale.ROOT.
I will provide a fix.

**Comment by lolodomo** [comment]
Just overriding getFallbackLocale in a dedicated ResourceBundle.Control so that it returns null should do what we need.
