### ISSUE TITLE
Integration tests - thing tests failure

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#961]
Build run on Windows 10:
```
22:35:59.961 [main] DEBUG org.eclipse.smarthome.core.thing.internal.profiles.SystemOffsetProfile - Configuring profile with offset parameter '3'
TEST testTimestampOnChange(org.eclipse.smarthome.core.thing.internal.profiles.TimestampProfileTest) <<< ERROR: null
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.eclipse.smarthome.core.thing.internal.profiles.TimestampProfileTest.testTimestampOnChange(TimestampProfileTest.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
...
Tests run  : 368
Passed     : 367
Errors     : 1
Failures   : 0
[INFO] 1 Error(s)
```

**Comment by lolodomo** [comment]
@clinique : the problem is in the test testTimestampOnChange.
 Sometimes, the test succceeds, most of the time it fails. When it fails, I veirified that the 2 dates are identical. I guess that my PC is fast and the two calls are done in the same millisecond !
I can solve the test by adding a thread.sleep between each call to timestampProfile.onStateUpdateFromItem.

But there is something I don't understand in this test. The second call to timestampProfile.onStateUpdateFromItem is done with the same value (23) as the previos call. I verified in TimestampChangeProfile:onStateUpdateFromItem that it is correctly detected and so there is no call to the callback done. So why are we expecting at least one call in the test: and why this call is done ??? Can you explain please ?
https://github.com/openhab/openhab-core/blob/master/itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/TimestampProfileTest.java#L67
